### ISSUE TITLE
Pinned sidebar Octotree might cause Firefox render SVG badly

### ISSUE THREAD

**Issue by Ding-Fan** [ovity/octotree#1000]
### Description

I turn on the extension [Octotree](https://www.octotree.io/) and pin it to left side, set the browser zoom to 200%. Then [this big SVG picture](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/01-FP-Philosophical-Foundations/assets/Composing-Types.svg) doesn't show up entirely.

### Environment (if bug)

* Octotree version: 5.4.1
* Browser & version: Firefox Version 79.0 (64-bit)
* OS & version: macOS Catalina 10.15.6
* Screenshot, if any (drag an image here)

![image](https://user-images.githubusercontent.com/26438549/91541456-faa41680-e94e-11ea-94b4-d555a8c87509.png)

* Console error log below this line

**Comment by buunguyen** [comment]
I run Firefox without Octotree and see the same problem. I think this issue has nothing to do with Octotree.
