### ISSUE TITLE
Login with Github failed

### ISSUE THREAD

**Issue by chenenyu** [ovity/octotree#1004]
### Description
The callback page shows a error after oauth.

### Environment (if bug)

* Octotree version: 6.0.0
* Browser & version: chrome latest
* OS & version: mac 10.15.6
* Screenshot, if any (drag an image here)

![1600341349199](https://user-images.githubusercontent.com/6647088/93463353-390f6e80-f91a-11ea-938a-eb2cd6001154.jpg)

* Console error log below this line

```
/api/v1.0/oauth/github:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
11138a794ef48f5af866.js:2 Uncaught (in promise) Error: Request failed with status code 400
    at t.exports (11138a794ef48f5af866.js:2)
    at t.exports (11138a794ef48f5af866.js:2)
    at XMLHttpRequest.d.<computed> (11138a794ef48f5af866.js:2)
```

**Comment by robSturcke** [comment]
@chenenyu I solved this for myself by the following steps:

- uninstalling Octotree 
- revoking permissions in github 
- then logging into [Octotree's official site](https://www.octotree.io/) to link GitHub
- Restart browser
- Install Octotree 
- Login with GitHub

Hope this helps!

**Comment by buunguyen** [comment]
We'll release a hot fix for this later today. Meanwhile, you can try the workaround by @robSturcke or by entering a name in your GitHub settings.

**Comment by buunguyen** [comment]
Should have been fixed. Please let me know if anyone still have this problem.
