### ISSUE TITLE
Octotree badge

### ISSUE THREAD

**Issue by jvmlet** [ovity/octotree#1005]
Would be great to provide "best viewed with octotree" badge, see sample  [here](https://github.com/LogNet/grpc-spring-boot-starter)
Well done, GitHub browsing can't be better with octotree

**Comment by buunguyen** [comment]
I clicked the link but not sure what sample you meant. Is there a badge you want us to see? Thanks.

**Comment by jvmlet** [comment]
Scroll down to the  see the bage...

**Comment by danhgit** [comment]
Great idea but we have to prioritize other items and this might not be feasible to build any time soon.

**Comment by jvmlet** [comment]
I think that the promotion of your work should not fall behind other functional  features , but the decision is all yours...
As you can see I've removed the pseudo badge from my repo ...
* Still think octotree is better than what GH has to offer.
