### ISSUE TITLE
Pro Account cannot validate with GitHub

### ISSUE THREAD

**Issue by jkyoutsey** [ovity/octotree#1007]
### Description
When I log in to octotree with my Pro account it still asks me to enter a token or validate with GitHub. When I try to validate with GitHub it shows me this: [image removed for privacy reason]

### Environment (if bug)

* Octotree version: 6
* Browser & version: Chrome latest
* OS & version: Mac OSX Catalina

**Comment by buunguyen** [comment]
Hi Jared, to protect your privacy, we'll reach out to you via email to support. I will remove the image from your post as it contains personal identification.

**Comment by buunguyen** [comment]
Responded via support channel.
