### ISSUE TITLE
Dark themes don't work properly in GitHub Enterprise

### ISSUE THREAD

**Issue by mengesb** [ovity/octotree#1008]
### Description
Prior to v6.0.0 the themes would match between github.com and my company GHES installation; now they're not matching. The body where repo files are shown isn't backgrounded in the black/charcoal color and is instead transparent/white. Both are using the same `GitHub Dark` theme, and no matter the theme chosen the code background always remains white.

GHES:
<img width="993" alt="Screen Shot 2020-09-17 at 09 19 18" src="https://user-images.githubusercontent.com/1378071/93499163-844c6180-f8c7-11ea-978d-722b1c889c34.png">

github.com:
<img width="1010" alt="Screen Shot 2020-09-17 at 09 23 40" src="https://user-images.githubusercontent.com/1378071/93499192-8f06f680-f8c7-11ea-8cd9-44caeaf31359.png">

Also button backgrounds are white/grey instead of dark themed, like the "Find repository" search box "Type" and "Language" buttons, branch buttons, etc.

### Environment (if bug)

* Octotree version: 6.0.0
* Browser & version: Brave Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
* OS & version: MacOS X 10.15.6
* Console error log below this line

**Comment by buunguyen** [comment]
Sorry about that. Would you mind if we contact you via email to ask for more information so that we can troubleshoot the issue?

**Comment by buunguyen** [comment]
Can you help inspect the GitHub file list and buttons with Chrome dev tool and capture a screenshot of all the styles being applied to those elements (one screenshot for the file list and another for the the button). We need to know exactly what styles causing the white out to address it. Thank you.

**Comment by robSturcke** [comment]
@buunguyen can you white out the `background-image: url()` in the CSS?  It's way too distracting with reading the code.  Either that or let us toggle it off.

**Comment by buunguyen** [comment]
@robSturcke how is background-image: url() have anything to do with this particular issue?

**Comment by robSturcke** [comment]
@buunguyen there's overlap in the design going into some elements, it also was never there before this update.  Not sure why it's there's a `!important` on the image

**Comment by buunguyen** [comment]
I'm still not sure how that would help fix this particular issue (styles don't get applied in GHE). But yes, we'll remove the background-image in body.

**Comment by bmoyer240** [comment]
Hopes this helps.. a quick compare.. looks  like enterprise renders using a table; however, I didn't have an issue until this last update

![image](https://user-images.githubusercontent.com/6550299/93617792-6dc80800-f9a4-11ea-933e-67360ded527e.png)

**Comment by bimp** [comment]
+1 on this. Seeing this as well in enterprise

**Comment by buunguyen** [comment]
Please upgrade to 6.0.1 and give it a try.

**Comment by bmoyer240** [comment]
looks good! 
![image](https://user-images.githubusercontent.com/6550299/93641840-fd80ad00-f9ca-11ea-8d7c-53c05a8f57a0.png)

**Comment by bimp** [comment]
much better... there is still a bit of a white border outline... see my screenshot comparing the enterprise styling versus the publci github styling for Github Datk theme
![image](https://user-images.githubusercontent.com/580277/93650722-28b3ce00-f9c4-11ea-89ec-91f2e45b04f7.png)

**Comment by bimp** [comment]
also just noticed that in a PR view, big white bar 

![image](https://user-images.githubusercontent.com/580277/93651174-6533f980-f9c5-11ea-916f-4a656fea52b3.png)

**Comment by buunguyen** [comment]
We don't have GHE to test (it was expired). GHE is lagging behind the GH re-design, these are likely places when the DOM is different between GHE and github.com. Unfortunately, we can only fix these issues on case by case before the theme functionality in 6.0 was completely rewritten to support more themes, reduce file size, load faster and improve the look on the re-designed github.com.

For elements that don't look correct, please inspect the DOM and send us screenshot of it + CSS styles being applied. Feel free to contact us at support@octotree.io to avoid sharing info here. The clearer we know the difference between GHE DOM and github.com DOM, the easier for us to fix it. Thanks everyone for your understanding and support.

**Comment by mengesb** [comment]
The update for 6.0.1 fixed this for me. I looked at the a merged PR diff screen, and the repo screens (we disable issues, projects, wiki, etc so I cannot comment there).

I'm amenable to closing this issue however others who shared the same issues may feel differently so I'll see what their input is. Thanks for the support and updates @buunguyen

**Comment by bmoyer240** [comment]
I am good for closing.. the background and bright white elements were rough.. white border here and dark text on dark background there are minor.

**Comment by bimp** [comment]
this issue has come back with version 7.0.2. are people seeing this again?

**Comment by danhgit** [comment]
@bimp please go to Octotree settings screen, scroll to the bottom and explicitly enter in the version of your GitHub Enterprise. If it still doesn't work, please send email support@octotree.io so that I can ask for more information about your GHE deployment. Thanks.

**Comment by bimp** [comment]
@danhgit not quite following your instructions. are you talking about the Octotree settings page that appears along the sidebar?
i don't see anything related to the version of github enterprise. 

I did go to my github enterprise profile setting and it says GitHub Enterprise Server 2.21.17

**Comment by danhgit** [comment]
@bimp sorry I wasn't clear. You need to be in a GitHub Enterprise repository to see that setting. It's in the last section of the setting screen, near the "Apply settings" button.

**Comment by danhgit** [comment]
Please input "2.21.17" into the GHE textbox. Then click "Apply Settings".

**Comment by bimp** [comment]
Ahhh... wasn't even aware of this setting. What is this setting doing? I looked at https://www.octotree.io/features#github-enterprise and didn't find any reference. Thanks

Everything looks good now.

**Comment by danhgit** [comment]
Glad to hear it works. It's a new setting of the latest release, I haven't got time to update the documentation. There are some major incompabibilities among different GHE versions. Octotree tries to retrieve the version from the DOM to do the right thing. But sometimes it can't because the version isn't in the right place in the DOM or isn't in the DOM at all. In the past we had to keep patching the version determination code but it was very fragile. It's easier making the setting for users to explicitly set if something doesn't work right.

**Comment by bimp** [comment]
@danhgit got it.... i can imagine keeping up with various version compatibility must be PITA.... appreciate the work and help
