### ISSUE TITLE
Remove or Ability to Remove Background Image on Dark Themes

### ISSUE THREAD

**Issue by robSturcke** [ovity/octotree#1009]
Background image is too distracting to read code, please allow us to remove the checkered background.

I also can't override this with any other plugin themes due to the `body` tag with a `background-image` rule with `!important` on it. 

![Screen Shot 2020-09-17 at 1 11 54 PM](https://user-images.githubusercontent.com/13204145/93504348-5d058c80-f8e7-11ea-916a-9c920867ee44.png)

Octotree version: 6.0.0
Browser & version: Brave Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)
OS & version: MacOS X 10.15.6
Console error log below this line

**Comment by buunguyen** [comment]
Sure. Will release together with some other hot fixes.

**Comment by robSturcke** [comment]
@buunguyen awesome my friends and I were trying to figure out why our plugins weren't overriding it.  Appreciated!
