### ISSUE TITLE
Attempting to install via Edge store CRX_HASH_VERIFICATION_FAILED

### ISSUE THREAD

**Issue by devhawk** [ovity/octotree#1011]
### Description
Attempted to install via edge store, but I get the error below

### Environment (if bug)

* Octotree version: whatever is in Edge extension store
* Browser & version: Edge 85
* OS & version: Windows 10 2004

![image](https://user-images.githubusercontent.com/8965/93718667-8c5c0980-fb32-11ea-9571-928d24a89097.png)

**Comment by buunguyen** [comment]
Thanks for reporting. I got the same error. I just checked, the exact binary runs fine in developer mode and it passed Edge verification. I'll contact Edge Support to see what's wrong.

**Comment by buunguyen** [comment]
Turn out, this will go away after upgrading Edge to the latest version.
