### ISSUE TITLE
[Pro] Octotree doesnt work for private org repos anymore

### ISSUE THREAD

**Issue by PetrykowskiM** [ovity/octotree#1012]
### Description
Hey there, I pay for octotree but it stopped working on private repos. The private repo belongs to an organization. Can you tell why it doesnt work anymore?

![image](https://user-images.githubusercontent.com/5831420/93761715-8e939600-fc0e-11ea-97fb-538beca46284.png)

### Environment (if bug)

* Octotree version: Not shown in settings
* Browser & version: Chrome 85.0.4183.102
* OS & version: MacOS

**Comment by amooz** [comment]
I have noticed the same behaviour

**Comment by buunguyen** [comment]
Hi, can you input token in the Settings page?

**Comment by PetrykowskiM** [comment]
@buunguyen  how should i do that? Where should the token come from?

**Comment by Sayvai** [comment]
> @buunguyen how should i do that? Where should the token come from?

Instructions are on the Octotree website, on the [Features](https://www.octotree.io/features#authentication) page.

**Comment by buunguyen** [comment]
Thanks @Sayvai for providing the link.

@PetrykowskiM if you need further assistant, please contact support@octotree.io.
