### ISSUE TITLE
[Feature Request] - Add Current Version To Sidebar

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1013]
### Description

It would be nice to include the current actively installed extension version number within the sidebar. Colour theme adaptable of course.

At the moment, for me to find out whether the extension has been updated, i'd need to go into the extensions list of my browser (i.e. Chrome), and search for the Octotree extension.

The benefit to displaying the version on the sidebar, is that i can at a glance notice whether the extension has been auto-updated, and can act accordingly (if necessary), such as reading up on what's changed by going through the GitHub [repository](https://github.com/ovity/octotree/), or reading through the official Octotree [website](https://www.octotree.io/). 

It can also be easier to pass on the version number for debugging purposes.

See placement suggestion below:

![Feature_Request_Octotree_Version](https://user-images.githubusercontent.com/7581546/93791609-5d29c300-fc2c-11ea-9606-d5bf388c23ae.png)

### Environment
* Pro Subsciber: **Yes**
* Octotree version: `6.0.1`
* Browser & version: `85.0.4183.102`
* OS & version: `Mac OSX Catalina 10.15.6`

**Comment by buunguyen** [comment]
Good idea. Thanks. Will do.

**Comment by buunguyen** [comment]
It's in 6.0.3, but show in Settings header as we thought most users most the time don't need to see that info.

**Comment by Sayvai** [comment]
I can see it now in version `6.0.4`. Looks good 👍 

![Screenshot 2020-10-01 at 09 33 49](https://user-images.githubusercontent.com/7581546/94786906-7ddedf00-03c9-11eb-874a-5a06420dd158.png)
