### ISSUE TITLE
Jump to file diff does not work when clicking the title

### ISSUE THREAD

**Issue by rossgardt** [ovity/octotree#1015]
### Description
When clicking the file name of a file in the sidebar, nothing happens. I would expect the 

### Environment (if bug)

* Github: GitHub Enterprise Server 2.21.7
* Octotree version: 6.0.1
* Browser & version: Chrome Canary 87.0.4272.0
* OS & version: Mac OS Catalina 10.15.6
* No errors in JS console
* See screen recording:
[Screen Recording 2020-09-24 at 10.55.22.mov.zip](https://github.com/ovity/octotree/files/5274787/Screen.Recording.2020-09-24.at.10.55.22.mov.zip)

**Comment by buunguyen** [comment]
Hi, we need some info. Feel free to send to us via support@octotree.io.

* Does it happen only in this PR, or every PR?
* Please send the hash fragment of the URL after you click a file in the sidebar and after you click the same file in GH's body
* Please open networking tab in dev console, check for an XHR request to "username/reponame/diffs?pull_number=${repo.pullNumber}&base_sha=..." What is the response from the server?

**Comment by rossgardt** [comment]
Hello @buunguyen .

I can see that OctoTree links to an anchor `#diff-0`
```
portal/pull/23114/files#diff-0
```

However, the anchors on the GitHub page are defined as
```
<div id="diff-c280bcbb090d235d55355c474da84028" ...
```

**Comment by buunguyen** [comment]
Thanks. The problem is some old GHE still use the index-based scheme. We need to determine the version of GHE being used. I wonder if you could help us:

* View the source of the GHE page, do you put the version of GHE somewhere?
* If not, is the version string shown somewhere in the UI? Can you capture the DOM for that UI element?

If we could know the specific version of GHE, we could have the code handle both the old index-based and new hash-based URLs. Appreciate any help.

**Comment by rossgardt** [comment]
I only have the version info rom the UI
> Github: GitHub Enterprise Server 2.21.7
Is that enough?

**Comment by buunguyen** [comment]
Does that appear in all pages? If so, please inspect the DOM element and send me the screenshot of it. I need that to write code to retrieve that value. Thank you.

**Comment by rossgardt** [comment]
Sure. Here you go!

![Screenshot 2020-09-28 at 09 18 28](https://user-images.githubusercontent.com/234840/94401926-9c479f00-016b-11eb-8f64-724e4dde7088.png)

**Comment by alxsimo** [comment]
Same happens for me using GHE. Really helpful feature was lost.

Issue confirmed

**Comment by rossgardt** [comment]
@alxsimo There is a fix coming soon from @buunguyen . I tested it this morning.

**Comment by buunguyen** [comment]
@alxsimo what is the version of your GH Enterprise?

**Comment by alxsimo** [comment]
> @alxsimo what is the version of your GH Enterprise?

It's 2.21.7

**Comment by rossgardt** [comment]
The fix was shipped! Thanks a lot @buunguyen !
