### ISSUE TITLE
GitHub login requests WRITE permission

### ISSUE THREAD

**Issue by kyeotic** [ovity/octotree#1018]
Login with GitHub requests permission not just to READ all repositories, but to WRITE them as well. This doesn't seem like it should be necessary.

### Environment (if bug)

* Octotree version: 6.0.1
* Browser & version: Firefox
* OS & version: MacOS Catalina
* Screenshot
![image](https://user-images.githubusercontent.com/1187432/94473318-dff8d380-0180-11eb-92b9-1b70560aedde.png)

**Comment by buunguyen** [comment]
https://www.octotree.io/features#authentication

>  GitHub doesn't have separate read and write permissions for repositories (see [GitHub OAuth scopes](https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps)), so it will prompt for both even though Octotree only needs the read permission.
