### ISSUE TITLE
Login Failure: `(destructured parameter) is null`

### ISSUE THREAD

**Issue by jameshounshell** [ovity/octotree#1019]
### Description
When attempting to log in with the correct username and password, Octotree responds with `(destructured parameter) is null` just below login button.

Incorrect username or password respond correctly by issuing username/password not correct error.

### Environment (if bug)

* Octotree version: 2.0.2
* Browser & version: Firefox 80.0.1 (64-bit)
* OS & version: mac os catalina 10.15.6 (19G2021)
* Screenshot: (github not uploading png, not sure what's wrong)
* Console error log below this line: no error message shows up in firefox console

**Comment by buunguyen** [comment]
Hi, please see this thread https://github.com/ovity/octotree/issues/1016

**Comment by jameshounshell** [comment]
Solution: uninstall Octotree Pro, install Octotree (pro and non-pro are merged)

Closing this now.
