### ISSUE TITLE
[Bug] octotree doesn't work in Firefox with private window

### ISSUE THREAD

**Issue by XOR-op** [ovity/octotree#1020]
### Description
Hi,

I'm a user of octotree for years. I have installed octotree in both Chrome and Firefox. In Firefox, octotree sidebar doesn't appear in private mode (either always private mode or normal privacy setting with private mode on). By contrast, octotree works well in Chrome whether it's in incognito mode or not. 

My Firefox and octotree are all up-to-date. An older issue is related to current bug: https://github.com/ovity/octotree/issues/251.

Hope this bug can be solved soon. Thanks!

### Environment (if bug)

* Octotree version: 6.0.2
* Browser & version: Firefox 81.0
* OS & version: Mac OS 10.15.6

**Comment by buunguyen** [comment]
I've just released a fix in 6.0.3. Please upgrade and try again.

**Comment by XOR-op** [comment]
Thanks. It works well now.
