### ISSUE TITLE
Sidebar weirdly hide after click at folder on Firefox

### ISSUE THREAD

**Issue by XOR-op** [ovity/octotree#1022]
### Description
Hi,
    Whenever a folder is clicked, it shows contents inside it correctly but collapses, which is a weird behavior I have never seen before.  It's incovenient for me to locate files. 
    I don't know if it's related to previous firefox bug fix, but I found the bug either in private window or in normal mode.
    Thanks!

### Environment (if bug)

* Octotree version: 6.0.4
* Browser & version: Firefox 81.0
* OS & version: mac os 10.15.6

**Comment by buunguyen** [comment]
So you click a folder, it expands, then it immediately collapses? Does it happen every time? Any log in the dev console? If you can give the exact step by step to reproduce would be great.

**Comment by buunguyen** [comment]
Please also try this:

* Uninstall Octotree completely from all browses
* Reinstall it

I'm afraid the setting storage might get messed up among the updates, causing this issue.

**Comment by XOR-op** [comment]
> Please also try this:
> 
> * Uninstall Octotree completely from all browses
> * Reinstall it
> 
> I'm afraid the setting storage might get messed up among the updates, causing this issue.

Yep it works on the reinstalled 6.0.4 version. Probably the storage issue.
