### ISSUE TITLE
Octotree plugin says that my trial has ended while I still have an active subscription

### ISSUE THREAD

**Issue by kirhgoff** [ovity/octotree#1023]
### Description
I paid for Octotree on April 17 for the year
[image removed]

it was properly working most of the time, but today I noticed that I lost the dark theme for Github and Octotree shows me that my trial period has ended
![image](https://user-images.githubusercontent.com/603097/95042589-2375b380-0726-11eb-81d9-a285a8557a5a.png)

This is the screenshot from the Chrome extensions page of Octotree
![image](https://user-images.githubusercontent.com/603097/95042661-5455e880-0726-11eb-8be7-46ce214bd1ef.png)

**Comment by buunguyen** [comment]
@kirhgoff please email support@octotree.io with the Octotree email address so that we can better support you.
I removed one image because it leaks your info.

**Comment by kirhgoff** [comment]
Thank you, sorry for that, but I did not find this email on the Octotree page :(
