### ISSUE TITLE
⚠️ READ THIS FIRST - Common Troubleshooting

### ISSUE THREAD

**Issue by buunguyen** [ovity/octotree#1025]
Below are the common problems many people have. Please check if your problem in the list and follow the steps to fix it. If your problem is different or doesn't go away please [Contact Us](https://www.octotree.io/contact). If you're unsure how a particular feature works, please check out the [User Guide](https://www.octotree.io/features).

### Issue: Octotree says the branch was deleted or access is denied
First, check you have either authenticated with GitHub or supplied a personal access token. Check [this guide](https://www.octotree.io/features#authentication) to learn how.

If you're authenticated with GitHub and the issue persists, the repository probably belongs to an org that Octotree doesn't have access to. Go to [this page](https://github.com/settings/connections/applications/746ccaaa555c27cb1f7a) to grant permission.

---

### Issue: Octotree sidebar doesn't stay in the pinned position
It's possible that you have multiple versions of Octotree running or the extension storage is messed up. To fix this:
* Uninstall all versions of Octotree and Octotree Pro from your browser (for Chrome, go to `chrome://extensions` and search for all occurrences of "Octotree"). Even if you only find one version of Octotree, go ahead uninstalling it.
* [Download](https://www.octotree.io/download) and install it again

---

### Issue: I cannot login to Octotree Pro
Octotree Pro is deprecated and its functionality is merged into Octotree. Go [here](https://www.octotree.io/download) to download and install Octotree, then login to your account. You must have an active [Pro subscription](https://www.octotree.io/pricing) to access Pro features.

---

### Issue: I'm a Pro subscriber but Octotree shows trial expires
Perform these steps in the extension:
* If you had linked GitHub with Octotree, go to Octotree's settings screen and unlink GitHub
* Logout of Octotree
* Login with your __Octotree email and password__ (not via GitHub OAuth)
* Go to settings screen to link with GitHub OAuth if needed

---

### Issue: Dark theme doesn't work with GitHub Enterprise
Perform these steps in the extension
* Navigate to a repository in your GHE
* Open the Octotree settings
* Find the "GHE" textbox and enter the version of your GHE
* Click "Apply Settings"
* Reload the page

If it still doesn't work, please send an email to support@octotree.io with the following information:
* Your GHE version
* Screenshot of one incorrectly styled element
* The applied styles of that element (inspect the element in Chrome dev tool then open the Styles tab, take screenshot of that)

---

### Issue: I cannot enable GitHub Enterprise in Safari
Octotree doesn't support GitHub Enterprise in Safari yet. We hope this will change when Safari 14+ fully supports Web Extensions.

**Comment by natasha1007** [comment]
IBH Mad weun Aftachttps://github.com/ovity/octotree/issues/1025#h dpndopping

**Comment by natasha1007** [comment]
[]([]([](https://github.com/ovity/octotree/iss[](https://github.com/ovity/octotree/issues/1027)ues/1030)))

**Comment by natasha1007** [comment]
](url)[https://github.com/ovity/octotree/issues/1021

**Comment by natasha1007** [comment]
spasibo bolshoye

**Comment by parallelser** [comment]
if you can send the email

**Comment by parallelser** [comment]
[[uberdevmobile@gmail.com](mailto:uberdevmobile@gmail.com)(url)
