### ISSUE TITLE
Octotree conflicts with Refined GitHub by pushing the repository header too far to the right when sidebar is pinned

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1026]
### Description
You said in https://github.com/ovity/octotree/issues/997#issuecomment-705164728 that you're not willing to address bugs (if they not break the extension), which I can understand. But given that Refined GitHub is a very widely used extension I'm reporting this glitch nonetheless.

Refined GitHub pushes the repository header to the right to align it with the content below [using this code](https://github.com/sindresorhus/refined-github/blob/20.10.1/source/features/align-repository-header.css). But this conflicts with how Octotree does this when the sidebar is pinned since `v6.1.0 `.

<br>

For the reference: [Gitako](https://github.com/EnixCoda/Gitako) apparently already had a similar problem: https://github.com/sindresorhus/refined-github/issues/3336

### Environment (if bug)

* Octotree version: v6.1.0
* Browser & version: 81.0 (64-Bit)
* OS & version: Windows 10 Pro 19.09

_Without_ Refined GitHub and with _unpinned_ sidebar: 
![grafik](https://user-images.githubusercontent.com/424602/95387819-92ebce80-08f1-11eb-91fc-be46b27db817.png)

_Without_ Refined GitHub and with _pinned_ sidebar: 
![grafik](https://user-images.githubusercontent.com/424602/95387903-b9aa0500-08f1-11eb-8f0a-c25d54b7c469.png)

_With_ Refined GitHub and with _unpinned_ sidebar: 
![grafik](https://user-images.githubusercontent.com/424602/95388029-dc3c1e00-08f1-11eb-8416-87f00b1a18fc.png)

**_With_ Refined GitHub and with _pinned_ sidebar:** 
![grafik](https://user-images.githubusercontent.com/424602/95388082-f0801b00-08f1-11eb-9d94-64d3bd5d01de.png)

**Comment by buunguyen** [comment]
Thanks for reporting. Please try 6.1.1, should be available shortly.

**Comment by jdreesen** [comment]
Thx for the quick fix!
But now it's too far on the left if Octotree is not wide enough to push the whole content to the right.

With RGH & unpnned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/95557894-bad45280-0a15-11eb-88c4-7e3daa309ef4.png)
![Bildschirmfoto von 2020-10-09 09-59-31](https://user-images.githubusercontent.com/424602/95558336-5b2a7700-0a16-11eb-9260-6a30d54ec776.png)

With RGH & pinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/95558469-9167f680-0a16-11eb-88e9-47fa3a49f77e.png)

**Comment by buunguyen** [comment]
Can you explain what the bug is? I don't see anything wrong in those screenshots.

**Comment by jdreesen** [comment]
Octotree now disables (when pinned) the "align repository headers" feature of RGH (Refined GitHub), so it's now too far to the left while it should be justified with the content below.

Here's another screenshot with a smaller Octotree sidebar:
![grafik](https://user-images.githubusercontent.com/424602/95651827-19203480-0aed-11eb-9525-5570e37f01bb.png)

**Comment by buunguyen** [comment]
You can go to Settings and enable "Shrink GitHub header" in Octotree. Kinda tough as both extension needs to control the layout.

**Comment by jdreesen** [comment]
Oh, yeah, right, that works for me, thx!

**Comment by fregante** [comment]
Update: this feature has been dropped in Refined GitHub https://github.com/refined-github/refined-github/pull/6247

**Comment by jdreesen** [comment]
Thx for the update @fregante!

Unfortunately, the same thing has been happening to the body for some time when both refined-github and octotree are installed.

Could you please have a look @buunguyen?

https://user-images.githubusercontent.com/424602/216623134-16324fa5-ee35-4175-bc89-a018fe51ec94.mp4

**Comment by jdreesen** [comment]
Note that this doesn't happen always. I don't really know when/on which pages yet.

**Comment by jdreesen** [comment]
I think I found where it comes from. Seems it has nothing to do with Refined GitHub, but with the new code view. See #1150
