### ISSUE TITLE
"Shrink GitHub header" should shrink the header only on pages with Octotree enabled and/or narrow layout

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1028]
### Description
It looks awkward on full-with pages (like the dashboard or notifications page), especially if there's no Octotree sidebar.

<br>

Also, there's a typo in the option's description: `Shrink Github header` => `Shrink GitHub header` (with a capital `H`)

### Environment (if bug)

* Octotree version: v6.1.1
* Browser & version: 81.0.1 (64-Bit)
* OS & version: Windows 10 Pro 19.09

**Comment by buunguyen** [comment]
Thanks for reporting. Please try 6.1.3, should be available shortly.
