### ISSUE TITLE
[Bug] Unable To Jump Between Files In Pull Request On Sidebar File Click

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1029]
### Description
I am currently unable to jump between files in a Pull Request page when clicking between files within the Octotree sidebar. The main page will not scroll, it's just static. Even after refreshing the page.

The main GitHub URL for reference: `https://github.com/`

I notice that on the rendered HTML markup, for example a href attribute value is set to:
```
#diff-5cf4576aa9f3c576714b8cea9b74b4517611af1179821735bd62abe82a5fb5f9
```
... but on the sidebar, for the link for the same file, the hash is smaller and does not even start with the same characters:

```
#diff-345c6deff5e12fbc96c5eb1d43931110
```

As you can see, the hashes are totally different for the same file. The sidebar link to an incorrect hash.

### Environment
* Subscriber: `Pro`
* Octotree version: `6.1.1`
* Browser & version: `Chrome 86.0.4240.80`
* OS & version: `OSX Catalina 10.15.7`
* Console error log below this line: `None`
* GIF: (see below)

The GIF below initially highlights which file i am currently viewing (marked in green circles). I then proceed to click between different files on the sidebar in an unsuccessful attempt to scroll between files on the main page (right-side)

![2020-10-13 16 37 45](https://user-images.githubusercontent.com/7581546/95884210-bd1b1180-0d73-11eb-9588-677a0e3418d0.gif)

**Comment by buunguyen** [comment]
Thanks. GitHub must have changed the format. We'll look into it.

**Comment by redusek** [comment]
I am having this same issue.  
Chrome 86.0.4240.80
Octotree 6.1.0
Catalina 10.15.6
Pro subscriber

**Comment by Sayvai** [comment]
@buunguyen Just received `6.1.2` update on Chrome with the hotfix, and I can confirm the browser now scrolls automatically between files within the Pull Request page when clicking on multiple files within the Octotree sidebar. 

Also tested on another Pull Request page to double verify the fix. 🎉
