### ISSUE TITLE
Browsable entirely by keyboard

### ISSUE THREAD

**Issue by Soulou** [ovity/octotree#103]
Hello,

I appreciated the addition of ctrl+b to toggle the tree, but it would be great to be able to browse the tree files using some shortcuts. Like giving the focus to the current item in the tree after a ctrl+b then use j/k or something like this.

What do you think of this?

**Comment by jvanbrug** [comment]
I use Vimium, but it does not work on GitHub (GitHub's keyboard shortcuts probably block it). Is there any way to focus and navigate the tree with the keyboard?

**Comment by Nolski** [comment]
Hate to be the guy to dig up an old issue but vimium key bindings will move you around a page and is a huge extension. I think the option to add key bindings to octotree would be pretty cool and isn't too crazy.
