### ISSUE TITLE
Icons not showing correctly on Github Enterprise

### ISSUE THREAD

**Issue by promid** [ovity/octotree#1031]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version: <INPUT HERE>
* Browser & version: <INPUT HERE>
* OS & version: <INPUT HERE>
* Screenshot, if any (drag an image here)
* Console error log below this line
<img width="221" alt="Snipaste_2020-10-20_10-39-57" src="https://user-images.githubusercontent.com/13310452/96533574-aa975f80-12c0-11eb-9c16-959c59fcff5b.png">

**Comment by buunguyen** [comment]
Hi, 
* What version of Octotree? Is it Chrome and on what OS?
* Does it work on github.com?
* Have you try re-installing the extension?

**Comment by promid** [comment]
@buunguyen 
I resinatalled it and it works! Thanks
