### ISSUE TITLE
[Feature Request] Display Files Changed On Octotree Sidebar On GitHub Commit Pages

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1032]
### Description
I would like to request a feature for the Octotree sidebar to reflect the actual **files changed** on a commit from within GitHubs' dedicated **commit pages**.

Currently, the Octoree sidebar displays the all directories / files off of the main repository, which makes it hard to tell what files were actually changed in the commit. 

Another benefit of such a feature is that i can easily click-jump to each of the changed files, and further filter (search) the changed files. Basically incorporating the same explorer tree view / features as i would currently experience when on a dedicated Pull Request page.

The GitHub commit page URL structure currently follows a familiar pattern `github.com/<ORGANISATION>/<REPO>/commit/<COMMIT_HASH>`.

I also attach an annotated screenshot visually describing the request for reference.

I would think this would benefit the developers like myself when interrogating historical commits far more easily, as well as enhancing the capabilities of the brilliant Octotree extension today 🙏 

![Screenshot 2020-10-20 at 19 22 29](https://user-images.githubusercontent.com/7581546/96630611-2fa86600-130d-11eb-8b05-0be4905c0470.png)

* Subscriber: `Pro`
* Octotree version: `6.1.3`
* Browser & version: `86.0.4240.80`
* OS & version: `MacOS Catalina 10.15.7`

**Comment by danhgit** [comment]
Just an update: v6.3.1 now shows only files that were changed in a specific PR commit instead of all files. 
We expect to build the same for normal (non-PR) commits in a future release.

**Comment by Sayvai** [comment]
> Just an update: v6.3.1 now shows only files that were changed in a specific PR commit instead of all files.
> We expect to build the same for normal (non-PR) commits in a future release.

Hi @danhgit thanks for making some progress on this, and can't wait for the non-PR part to be worked on in a future release!

However, i've been checking for updates to the Octotree extension for a week, and i'm still on `6.3.0`.

I suspect `6.3.1` is still yet to be rolled out?

**Comment by danhgit** [comment]
@Sayvai sorry, it's 6.3.0 in Chrome. Stay tuned for the non-PR update!

**Comment by danhgit** [comment]
This is in v7. Will be available shortly. Thanks for the suggestion @Sayvai!
