### ISSUE TITLE
"Watch" menu behind content when pinned + header shrunk

### ISSUE THREAD

**Issue by squatto** [ovity/octotree#1033]
### Description

When the sidebar is pinned *and* "Shrink GitHub Header" is enabled, the "Watch" dropdown menu shows behind the page content when the viewport is >=1760px wide.

At 1760px wide the `octotree-wide` class is being _removed_ from `<html>`, which is what is causing it to happen. If I manually add the class it makes the dropdown menu show on top of the page content again.

To easily see it happen:
1. Enable "Shrink GitHub Header"
2. Make your viewport >=1760px wide
3. Open the "Watch" dropdown menu
4. Toggle sidebar pinning on and off

I've included multiple annotated screenshots below.

### Environment (if bug)

* Octotree version: v6.1.3
* Browser & version: Google Chrome - Version 86.0.4240.80 (Official Build) (x86_64)
* OS & version: macOS Big Sur - Version 11 Beta 10 (20A5395g)
* Screenshots:

---
#### Pinned + "Shrink GitHub Header"

![image](https://user-images.githubusercontent.com/748444/96651902-0975cc80-12f3-11eb-965b-61969a30f3d7.png)

#### At <=1759px wide: `<html>` has `.octotree-wide`, "Watch" dropdown menu above content

![image](https://user-images.githubusercontent.com/748444/96652932-362ae380-12f5-11eb-8757-a062a954cd58.png)

#### At >=1760px wide: `.octotree-wide` removed from `<html>`, "Watch" dropdown menu below content

![image](https://user-images.githubusercontent.com/748444/96653127-9883e400-12f5-11eb-9e49-5be919d0185d.png)

**Comment by buunguyen** [comment]
@squatto thanks for reporting the bug with detailed steps to reproduce, it helps a lot!

We just released a fix to the stores (v6.1.4). Should be available shortly.

**Comment by squatto** [comment]
My pleasure! Thanks for getting that fixed so quickly, and for such a badass product 😁
