### ISSUE TITLE
White border around text fields/preview

### ISSUE THREAD

**Issue by macintacos** [ovity/octotree#1034]
### Description
There's a white border around a lot of elements when dark mode is selected. For context, I use the GitHub Dark theme. Screenshots are provided below.

### Environment (if bug)

* Octotree version: 6.1.4
* Browser & version: Chrome Version 87.0.4280.27
* OS & version: macOS 10.15.7
* Screenshot, if any (drag an image here):

![image](https://user-images.githubusercontent.com/8128941/97056149-4b527d00-1556-11eb-821d-cfb768276928.png)

<img width="1183" alt="New Issue · ovityoctotree 2020-10-23 at 17 38 42" src="https://user-images.githubusercontent.com/8128941/97056277-9b314400-1556-11eb-8107-93eb87bd5406.png">

<img width="1181" alt="New Issue · ovityoctotree 2020-10-23 at 17 39 30" src="https://user-images.githubusercontent.com/8128941/97056335-bb610300-1556-11eb-8cc8-be2efd589aa0.png">

**Comment by buunguyen** [comment]
Thanks for reporting. Looks like GitHub has changed its DOM again. We'll look into this.

**Comment by buunguyen** [comment]
Please check v6.1.5 (available in stores soon).

**Comment by macintacos** [comment]
Looks good! Closing this out, I don't see this anymore.
