### ISSUE TITLE
Dark mode - Can't see most text

### ISSUE THREAD

**Issue by kevnm67** [ovity/octotree#1037]
### Description

Using any dark mode theme makes github unusable.  The text is nearly impossible to see.  I've experienced this in a previous version and it showed up again 2 days ago.  Nothing I've tried helps:
- Restarted my computer
- Uninstalled/reinstalled octotree + restart
  - NOTE: Removed all leftovers from the system directories.
- Tried using every theme available.

### Environment (if bug)

* Octotree version:  6.1.5 (36)
* Browser & version: Safari 14.0 (15610.1.28.1.9, 15610)
* OS & version: 10.15.7 (19H2)
* Screenshot
<img width="1657" alt="Screen Shot 2020-10-27 at 8 52 46 AM" src="https://user-images.githubusercontent.com/2734154/97304333-f5215a80-1831-11eb-91f8-332782b15c85.png">

**Comment by buunguyen** [comment]
Thanks for reporting. This is due to recent major style changes in github.com and our dark mode code needs special handling for Safari. We've just submitted an update to the App Store. Hope it will be available soon.

**Comment by buunguyen** [comment]
It is available in the store now. Please update. I'm closing this now. Thanks again for reporting the issue.

**Comment by kevnm67** [comment]
@buunguyen updated yesterday.  Thanks for the quick turnaround 😉
