### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by Powersource** [ovity/octotree#1038]
Just a few months ago this project had a LICENSE file in it that said it was licensed under AGPL3 https://github.com/ovity/octotree/tree/56d13e8df5ecddc2f8c1f0afe80f35c654dd20ef

On AMO it still says the license is AGPL3 https://addons.mozilla.org/en-US/firefox/addon/octotree/

But I can't find the source code anywhere?

**Comment by buunguyen** [comment]
The source of a limited edition of Octotree is in the `master` branch and under AGPL3. Pro functionalities are not open-source. We've updated AMO listing to be clear.

**Comment by Powersource** [comment]
If the pro functionality is part of the same program as the AGPL3 code then the pro functionality code also needs to be published.

**Comment by buunguyen** [comment]
I don't think so.
