### ISSUE TITLE
Dark themes are broken, e.g. Dracula or Ambiance. No line numbers and white spaces(really white)

### ISSUE THREAD

**Issue by Darkvar** [ovity/octotree#1039]
### Description
1. Open any pull request, check the file with added lines - the original file will have lines with white background instead of grey or black.
2. No line numbers are visible by default, visible only at mouseover. 
### Environment (if bug)

* Octotree version: 6.1.7
* Browser & version: Google Chrome Version 86.0.4240.111 (Official Build) (x86_64)
* OS & version: Mac OS Mojave 10.14.6
* Screenshot 
![Screen Shot 2020-10-30 at 09 40 27](https://user-images.githubusercontent.com/1177519/97673214-11243680-1a94-11eb-9ffe-0c3d035bda40.png)

**Comment by potiuk** [comment]
Same for me!

**Comment by endyquang** [comment]
I’ve fixed the issue and submitted to the stores. Please look out for the update.
