### ISSUE TITLE
Accidentally deleted "Troll" comments were just critiques?

### ISSUE THREAD

**Issue by AlexandriaOL** [ovity/octotree#1042]
Hi! With respect to the thread #1040, it looks like you might have accidentally deleted some comments?

You called them "trolls", but as the internet archive of that thread shows, they were simply backing up their claim that the new code contains AGPL code and opinions by former contributors that you might have broken the terms of the license agreement?

The full thread is here: https://web.archive.org/web/20201031182128/https://github.com/ovity/octotree/issues/1040

Some examples of content that you (I assume) mistakenly deleted:

```
christianbundy commented 1 hour ago
> If you really examined the source, you would have seen the resemblance is because both use the same open-source libraries, which made up the bulk of the source bundle.
Nope. Here's a bit that was obviously based on src/view.tree.js:
[Source code removed but available on the internet archive]
```

and

```
christianbundy commented 1 hour ago 
> Over the years, it has been a waste of time to explain ourselves why we need to charge for our labor.
Just to be clear, you're more than welcome to charge money for your product. What you are not welcome to do is release a proprietary product built on AGPL-3.0-licensed code whose copyright is owned by people who are not you. That's literally the point of the AGPL, and I'm sure you know this (otherwise you wouldn't be claiming a "complete rewrite").
```

and this one contributor, that talked about the legality of the issue:

```
zacanger commented 1 hour ago
IANAL but I believe @christianbundy is correct and any change from a license like AGPL to an incompatible license or no license would at least require the consent of anyone who contributed under the previous license. Personally my contribution was insignificant and I don't claim any copyright over the code I contributed, but thanks for tagging me so I'd be aware.
```

I'm so sorry that this happened! I hope I could help by replicating them here. And I was wondering if you could comment on if this was deliberate obfuscation that you did, or mere accidental deletion? Thanks!

**Comment by buunguyen** [comment]
I deleted ALL of his comments (except the original post) because he made a blatant lie that Octotree "uses the same code from master with small changes" and continued spamming me and people after my first warning.

Everything needs saying was said [here](https://github.com/ovity/octotree/issues/1040#issuecomment-719973490). I will *really* appreciate if people stop asking me to explain myself. Octotree will not be open-sourced. That's the end of it.
