### ISSUE TITLE
You are obligated by law to release the source code for the proprietary version

### ISSUE THREAD

**Issue by ddevault** [ovity/octotree#1043]
You are obligated to release the source code for the proprietary version, including all of the paid features, under the terms of the AGPL. The "old" version on the master branch of this repository is not sufficient.

Opened this ticket to track the problem on the official bugtracker. There is further discussion at a fork, here: https://github.com/christianbundy/octotree/issues/1

If you want to make a proprietary version, then you can complete your rewrite properly and then do so. If you'd like to discuss that separately, let's do it in another thread. Ditto for any difficulties you have faced as a maintainer, problems with spam and trolling, and so on. These are unrelated to the problem.

**Comment by buunguyen** [comment]
Keep the discussion in the other repo. Please do not spam me.

**Comment by microsoft-sucks** [comment]
nice to have an **open source idol** like @ddevault here to help resolve this issue :)
