### ISSUE TITLE
Octotree and AGPL

### ISSUE THREAD

**Issue by buunguyen** [ovity/octotree#1046]
Hello everyone, you are probably aware of [a situation](https://github.com/christianbundy/octotree/issues/1) surrounding Octotree in the last few days. I write this post to clarify a few things in case you have questions. Any user can read this post, only prior contributors can respond to it.

Quick summary. Someone posted a ticket claiming the proprietary version of Octotree "uses the same code from `master` with small changes" and "it's easy to verify" that claim. I thought it was outrageous because if he had actually verified, he would have arrived at a different conclusion. Being badly trolled before, I immediately assumed bad faith and responded critically. When he and another person posted more comments, tagging a lot of people, I was ticked off, deleting all comments, posting an even more critical response and blocking the whole thread as "spam". After that, he posted the story in his repo and cross-posted on HN.

I will spare you from most of the details but the last few days have been some of the worst days of my life. I was called all sorts of not-so-nice names. This repo was spammed and I had to lock it. I have neglected my family because of the lack of time and energy. It has affected my job (the one that actually pays the bills, not Octotree). Having spent thousands of hours in last 6 years working on Octotree, which almost 100% of users use for free, I could never imagine this is one of the things I have to deal with.

But I can only blame myself. No matter how the original ticket was written, I should have ignored the irrelevant aspects to address the only thing that matters: does Octotree inappropriately use AGPL code by non-team members. Had I responded to that instead of throwing a tantrum, this whole ordeal probably wouldn't have happened. It was entirely on me. I want to apologize to everyone whose questions and feedback I dismissed, including the ticket poster. And I want to thank those who voiced constructive opinions in the linked conversation.

Now, some Q&A.

#### Did we rewrite the proprietary version of Octotree?

Yes, we did, with an entirely new architecture. When we wanted to reuse some legacy code, we reused those we believed were ours (or under MIT license) and rewrote others. It's worth noting that current and former Octotree team members (Buu Nguyen, NDQ/endyquang, Phi/nphi, Fahme, An/crashbell, Danh, duylam) own the [vast majority](https://github.com/christianbundy/octotree/issues/1#issuecomment-719981875) of code in the open-source version. Coupled with the rewrite, it's unlikely AGPL code from non-team members exists without having been rewritten. However, as I mentioned in the linked discussion thread, our team will review the entire codebase and if we detect any mistakes, we will fix them.

#### Can we prove it was rewritten?

Absolutely. If anyone having contributed some non-trivial code under AGPL wants to take a look (and agrees to sign an NDA), we'll walk you through our codebase. Send me an email at bn@octotree.io.

#### What's next for Octotree?

My team will continue working on Octotree. I will take a break to recharge myself and focus on my job and family. (Let's hope GitHub won't do a major re-design anytime soon.)

After the break, a couple of things on my mind.

* A few people suggest re-licensing from AGPL back to MIT. Others say going with unlicensed. We'll think about that.
* Octotree has been my main hobby project for the last 6 years. Even before this, I haven't felt excited working on the project as I used to. Besides, my job has become more demanding. So have my little kids. It's probably time to move on. I'll have a conversation with my team. Regardless, I'll make sure Octotree will be in good hands.

That's it for now. Thanks for reading and thanks for your contribution.

**Comment by buunguyen** [comment]
@endyquang @Fahme @ricosmall @zacanger @danhnguyen30041975 @jdreesen @nphi @duylam @stevennoto @widyakumara @rheaditi @crashbell @enizor @samvel1024 @Sayegh7 @RomanKornev @0xflotus @jamesmosier @carloschneider @tbodt @Jackymancs4 @Ephemera

**Comment by buunguyen** [comment]
@thewarpaint @Akryum @hisabimbola @kevinconaway @bigredwill @tvytlx @chrisbrownie @piamancini @ergenekonyigit @dimorinny @gluons @broven @fieteboerner @itiut @amio @josephfrazier @hknochi @leocaseiro @ruanyl @meip @Justineo @Mottie @MonwF @norio-nomura @mijoharas @voithos @athaeryn @eush77 @enyo @bayandin @leereilly @tatsuyaoiw @jerizm @alexbeletsky @letunglam @sidke @Luegg @isbadawi @vakata @Spittie @k2nr @behnam @DrewML @jsutlovic

**Comment by crashbell** [comment]
Just learned about this. Took me an hour haha.

That's tough, I can't imagine how could you go through this in those days. I understand that you put your heart into this project, that's hard to keep calm in that situation.

Hope you feel better now. Take a break, I will fully support your decision no matter what is it. I believe that we will have a way out to resolve the license issue completely.

Just something cheerful I want to share here:
That was like 5 years ago when my first MR was merged, and now I just figured out that GitLab CEO gave me thanks. I missed including this into my resume :)
![image](https://user-images.githubusercontent.com/810139/98166418-f29dbf80-1f19-11eb-9159-64eb123fb3c5.png)

Thanks @buunguyen for giving me a chance to involve in Octotree.
Please feel free to ping me if you need some help.

**Comment by stevennoto** [comment]
Hi, and thanks for starting a thread for contributors to discuss this. I saw the other thread but I didn't want to engage there.

First off, I wanted to take the chance to thank you for creating and maintaining Octotree. I use it every day and it makes code review so much better. I recommend it to everyone I work with, and clearly the 300k users on the Chrome store also like it due to its 5-star rating. So thank you for making GitHub better by your work!

Regarding this situation, it's unfortunate that it has become a flame war, and that so many people who don't even have a stake in the project have posted such extreme things. If you need a break, go for it: family and job come first. After a break, I hope you can return to your hobby project refreshed.

If it helps, I'd be happy to waive any claim I have for my contributions. And like crashbell said, I will support your decisions on the software. Keep us posted. Thanks!

**Comment by widyakumara** [comment]
First of all, thank you for creating Octotree.

As for my contribution, it's way too miniscule to be a burden.
I'm happy to waive any claim for it.

**Comment by jerizm** [comment]
I'm happy to waive any claim for my contributions as well.

**Comment by mijoharas** [comment]
same, I don't even remember making a contribution to octotree, I hereby waive any claim to it. Hope you don't let this get you down.

**Comment by letunglam** [comment]
@buunguyen
I'm sorry you had to go through that. That thread was really toxic and the whole thing was blown way out of proportion.

Octotree is one of the tools I can't live without and it has saved me so much time over the last 6 years. I'm glad I was able to help in the early days. Thank you for creating and continue building Octotree till now. You clearly have put tremendous effort into the project. As @stevennoto said, take care of yourself and come back recharged.

**Comment by buunguyen** [comment]
Hi all, thank you for the kind words. I really appreciate that.

Our team discussed and we think the best thing we could do for Octotree users is we could focus on building Octotree without getting distracted by things like this again. As stated before, the Octotree team wrote the vast majority of the open-source code, built from scratch the closed-source software (which is ~3 times bigger than the open-source version) and took great care to only reuse certain things we owned or already rewrote. Despite all this, unless it's absolutely clear we have complete ownership over the open-source code, some people might still question us in the future.

Per the git-blame stats referenced in my last comment, the open-source repo currently has 90 LOCs from 14 different contributors who aren't team members or haven't waived their copyright. These contributors are: @ricosmall, @jdreesen, @stevennoto, @samvel1024, @Sayegh7, @Ephemera, @kevinconaway, @Brightcells, @itiut, @DrewML, @voithos, @Sayegh7, @fieteboerner, @tvytlx. I'd like to ask these contributors to assign the ownership of their contributions to me by responding to this thread or email me at bn@octotree.io. If anyone not willing to do that, we will respect their decision and remove their code from this repo. In addition, even though there has been very little outside contribution in the past few years (and exactly 2 very minor commits this year), we will ask future contributors to either sign an CLA or submit a bug report instead. These actions should put this matter to rest and our team can go back to building Octotree.

Finally, I'd like to take this chance to thank everyone for supporting this project during the last 6 years. I especially want to thank former and current team members for dedicating a lot of their free time working with me on Octotree and making it useful for so many people. It's been a lovely journey and I can't thank you all enough.

**Comment by Ephemera** [comment]
I enjoyed contributing to the octotree, although it's a long time ago.
I'm happy to waive any claim for my contributions.

**Comment by kevinconaway** [comment]
Waived.  Good luck 🚀

**Comment by tvytlx** [comment]
Waived. Thank you for giving me the chance to participate.

Buu Nguyen <notifications@github.com> 于2020年11月20日周五 上午2:45写道：

**Comment by voithos** [comment]
I'm happy to waive as well. :+1:

**Comment by DrewML** [comment]
Waived as well. Thanks for the hard work on this project @buunguyen!

**Comment by fieteboerner** [comment]
I also waive any claim of my contributions.

**Comment by behnam** [comment]
I don't remember what my contribution was. But, anyway, waiving any claims, as well.

**Comment by stevennoto** [comment]
I also waive my ownership of my contributions to Octotree.

**Comment by buunguyen** [comment]
Thank you for waiving the copyright here and via email. 5 people haven't responded, so I [removed their code](https://github.com/ovity/octotree/commit/425325df0be5adf01fedbd7701864b823fdde6ca) from this repo. These are very straightforward 1 or few-line bug fixes and a change to `.gitignore`. We fixed these ourselves in the closed-source version (which, BTW, is __not__ a fork of this repo and does _not_ share commit history). This matter can now be closed. 

Thanks again for your contribution and support.
