### ISSUE TITLE
Option to use GitHub's new dark mode for the "main" view

### ISSUE THREAD

**Issue by macintacos** [ovity/octotree#1048]
### Description

Right now we're 95% of the way there because there's an option to only theme the sidebar. However when I turn on GitHub's new dark mode and turn on the theme for only the sidebar, the unfortunate side effect is that the tab bar for files is themed as if it's in light mode instead of dark mode:

![image](https://user-images.githubusercontent.com/8128941/101554908-89302700-3985-11eb-903e-1adfda41f22a.png)

My guess is that this would be best solved by adding a theme option for GitHub's built-in dark theme, and just theme the tab bar appropriately if it's chosen.

**Comment by kidonng** [comment]
> we're 95% of the way

I don't think so. Octotree uses some of GitHub's style and now some of them are also messed up:

![image](https://user-images.githubusercontent.com/44045911/101634544-d4b90280-3a63-11eb-8e99-a01f7811a8a8.png)

**Comment by endyquang** [comment]
Thanks for reporting. We already fixed in 6.2, should be available in stores soon
