### ISSUE TITLE
Duplicated "View full' buttons looking at a PR

### ISSUE THREAD

**Issue by c17r** [ovity/octotree#1049]
### Description

It starts off showing the expected one button per file. It seems that when it hits into a file that has multiple comments that you end up with an additional `View full` button per comment plus the default one for the file i.e. a file with 3 comments has 4 `View full` buttons. Also seems to cause that number to stick for all files going forward even if the file doesn't have any inline comments. Each `View full` button is clickable and does the exact thing: opens the file in a modal with the context being the top of the file. I thought that _maybe_ it would open the file in a modal scrolled to that particular comment but, nope, all the same.

### Environment (if bug)

* Octotree version: 6.2.2
* Browser & version: Chrome 87.0.4280.88
* OS & version: Win 10 Pro 1909
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/148640/102539572-db570380-407b-11eb-92fc-60dd82cd9cc8.png)

* Console error log below this line
No errors

**Comment by endyquang** [comment]
Thanks for reporting. This issue should be fixed and released now.
There should be only 1 `view full` button for each file. Please check if it still get duplicated @c17r

**Comment by c17r** [comment]
Seems to be good, thank you!
