### ISSUE TITLE
GHES search box uses black text in dark themes (unreadable)

### ISSUE THREAD

**Issue by mengesb** [ovity/octotree#1050]
### Description
On GHES, the search box is unreadable in dark themes because the text is black. When highlighting the text is white and backgrounded by the themes color, so is visible then. On github.com, the text is white and readable, highlighting works the same.

### Environment (if bug)

* Octotree version: 6.2.2
* Browser & version: Brave Version 1.18.70 (Chromium: 87.0.4280.101) and Chrome 87.0.4280.88
* OS & version: MacOS 10.15.7 (19H114)
* Screenshot, if any (drag an image here)

GHES:
<img width="617" alt="Screen Shot 2020-12-17 at 13 59 12" src="https://user-images.githubusercontent.com/1378071/102549992-ec027c00-4071-11eb-806a-f7a51d442284.png">

github.com:
<img width="617" alt="Screen Shot 2020-12-17 at 14 15 36" src="https://user-images.githubusercontent.com/1378071/102550257-616e4c80-4072-11eb-9516-c3f4eda32b48.png">

* Console error log below this line
Brave emits no console errors, however Chrome does on github.com

[github.com-1608242688634.log](https://github.com/ovity/octotree/files/5712425/github.com-1608242688634.log)

There's an element difference between GHES and github.com for the search box

GHES:
```
<input type="text" class="form-control input-sm header-search-input jump-to-field js-jump-to-field js-site-search-focus js-site-search-field js-navigation-enable jump-to-field-active jump-to-dropdown-visible" data-hotkey="s,/" name="q" value="" placeholder="Search or jump to…" data-unscoped-placeholder="Search or jump to…" data-scoped-placeholder="Search or jump to…" autocapitalize="off" aria-autocomplete="list" aria-controls="jump-to-results" aria-label="Search or jump to…" data-jump-to-suggestions-path="/_graphql/GetSuggestedNavigationDestinations" spellcheck="false" autocomplete="off" aria-activedescendant="jump-to-suggestion-search-scoped">
```

github.com:
```
<input type="text" class="form-control input-sm header-search-input jump-to-field js-jump-to-field js-site-search-focus js-site-search-field is-clearable" data-hotkey="s,/" name="q" value="" placeholder="Search or jump to…" data-unscoped-placeholder="Search or jump to…" data-scoped-placeholder="Search or jump to…" autocapitalize="off" aria-autocomplete="list" aria-controls="jump-to-results" aria-label="Search or jump to…" data-jump-to-suggestions-path="/_graphql/GetSuggestedNavigationDestinations" spellcheck="false" autocomplete="off">
```

Unsure if that's related at all or not.

**Comment by buunguyen** [comment]
Hi, thanks for reporting. What theme you're using? Does this happen with the "GitHub (default)" theme? Would also help tremendously if you can inspect the element with Chrome Dev Tool and trace what piece of CSS setting that black-ish color to the text. Thanks.

**Comment by mengesb** [comment]
> What theme you're using?
Theme: Solarized Dark

**Theme: Solarized Dark**
On Chrome, GHES, when typing text in the box, it remains black, when I click out, it turns white
On Chrome, github.com, when typing text in the box, it is white, when I click out, it remains white

**Theme: Github (default)**
On Chrome, GHES, when typing text in the box, it is black and the bg color of the box is white, when I click out, it turns white and the bg color of the box turns black
On Chrome, github.com, when typing text in the box, it is black and the bg color of the box is white, when I click out, it turns white and the bg color of the box turns black

So the default theme seems to be behaving correctly with colors and text.

> Would also help tremendously if you can inspect the element with Chrome Dev Tool and trace what piece of CSS setting that black-ish color to the text. Thanks.

Could you give some instructions or link to me a help guide to give you exactly what you want?

**Comment by buunguyen** [comment]
Thanks for the information. It's helpful to know the default style works.

> Could you give some instructions or link to me a help guide to give you exactly what you want?

Please see the red rectangle in the screenshot. You can use Chrome inspector, click on the search box when it has text, then look at the Styles tab, specifically look for the place that sets the text color to that unexpected black/blue-ish color.

<img width="1600" alt="screen" src="https://user-images.githubusercontent.com/406631/102558711-e9f4e900-4082-11eb-8bbc-c9db20db7c4c.png">

**Comment by mengesb** [comment]
text is black; still selected in search box:
<img width="1920" alt="Screen Shot 2020-12-17 at 16 25 16" src="https://user-images.githubusercontent.com/1378071/102559412-a3a08980-4084-11eb-9b09-a0d7fc36c3f4.png">

text is white, clicked out of search box with text:
<img width="1920" alt="Screen Shot 2020-12-17 at 16 25 27" src="https://user-images.githubusercontent.com/1378071/102559441-b87d1d00-4084-11eb-908b-3c1fc20d0c97.png">

**Comment by mengesb** [comment]
It looks like it's adding and deleting it sometimes in those segments.

**Comment by mengesb** [comment]
When I first load with no search text, I get:
<img width="884" alt="Screen Shot 2020-12-17 at 16 34 16" src="https://user-images.githubusercontent.com/1378071/102559933-e1ea7880-4085-11eb-949b-fd8ccb17b809.png">


Here's the text, but I had to note the strikethrough text (since copy/paste doesn't obey that)
```
injected stylesheet
html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) .Header .header-search-wrapper, html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) .Header .header-search-wrapper input, html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) .file-header {
    background: rgb(32, 32, 32) !important;
}
injected stylesheet
html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) .form-control, html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) .form-select {
    color: rgb(198, 198, 198);
    background-color: rgb(24, 24, 24); <=== strikethrough
    box-shadow: none;
    border-color: rgb(52, 52, 52);
}
injected stylesheet
html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) input, html.octotree-ghe[data-octotree-theme]:not([data-octotree-theme="sidebar"]) textarea {
    color: rgb(198, 198, 198); <=== strikethrough
}
```

Then I click into the search:
<img width="884" alt="Screen Shot 2020-12-17 at 16 33 26" src="https://user-images.githubusercontent.com/1378071/102559999-08a8af00-4086-11eb-8ea5-168609f1dc96.png">

Can't copy text because it changes the focus and the text changes

**Comment by buunguyen** [comment]
Thanks for this. In the last picture, something overrides the "color" of .form-select, causing the strikethrough. If you scroll down that list, do you see anything having "color" _not_ strikethrough?

**Comment by mengesb** [comment]
In `.jump-to-field-active{}` there was a color set there. When I unchecked it, and tested I saw the colors behave normally. Came from header-search.scss:109 ; only shows when selected in that search box

**Comment by buunguyen** [comment]
Thank you, this is very useful. Would you mind test a hot fix build before we release it to the store? If you don't mind, please send an email to support@octotree.io, we'll send you the build to test. Much appreciated.

**Comment by mengesb** [comment]
The version reports as 6.2.1, however yes it does work as expected in GHES. The text is legible when focused and not focused in the search box

**Comment by buunguyen** [comment]
Great! Thanks for confirming that the fix works. We've just released to the stores, should be available soon.

**Comment by mengesb** [comment]
I uninstalled, and re-installed. verified that everything is in good working order. Thanks for the fantastic turn-around.
