### ISSUE TITLE
How do I open tabs

### ISSUE THREAD

**Issue by randy-johnson** [ovity/octotree#1051]
I just installed Octotree today. The chrome version.  I cannot seem to figure out how to get tabs working.  I see 1 tab being created if I am browsing the repo and clicking files in the sidebar, but it never opens up more than 1 tab.  What am I missing?

Thanks.

**Comment by buunguyen** [comment]
You can double-clicking a file on the sidebar to open new tab.

**Comment by randy-johnson** [comment]
Right, when I double click files in the left sidebar, a tab gets opened, but only 1 tab at a time ever shows.  It just overwrites the tab already open.

![image](https://user-images.githubusercontent.com/161461/102816560-3b131e80-439c-11eb-9e19-9ca3fde73503.png)

**Comment by Sayvai** [comment]
I find that if you open a tab, and want that to persist (eg, after reload), or not overwritten by a newly opened file, then like in VS Code, you'll notice the tab title text appears in **italics** style when you first open the tab, and so just double-click on the opened tab, and you'll notice the tab title text is no longer styled in italics, hence the tab will persist on reload, nor will the tab be overwritten by newly opened files. 

See GIF demonstration below.

![Octotree_Feature_Tabs](https://user-images.githubusercontent.com/7581546/102858770-b7e8db80-4422-11eb-8f69-413d730e8a8e.gif)

**Comment by randy-johnson** [comment]
@Sayvai ,  thank you.  That indeed allows the tab to persist.
