### ISSUE TITLE
Is there a way to keep it on the screen without it getting in the way?

### ISSUE THREAD

**Issue by davidcsi** [ovity/octotree#1052]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

Suggestion:

- When one clicks on the little arrow to show the tree, it shows up over the actual page, hiding anything behind it. It'd be perfect if one could configure it so that it always shows up in github and embeds itself on the screen, like octotree does.
Attaching a screenshot.
![Screenshot 2021-01-08 at 20 29 31](https://user-images.githubusercontent.com/902640/104061405-6d23dd80-51f0-11eb-8120-e9a4d329fbd4.png)

**Comment by buunguyen** [comment]
What gets in the way, the sidebar or the tab? It gets in the way how? And what is the proposal/suggestion?

**Comment by davidcsi** [comment]
The tree shows up over the actual github page. Is there any way to embed it in the page like octotree does?

**Comment by buunguyen** [comment]
>  like octotree does.

This repo is the Octotree repo. And Octotree doesn't hide contents when you pin it. 

I think you probably comment on the wrong software?

**Comment by davidcsi** [comment]
oh damn.. sorry!
I've been using octetree for a long time, but the price being asked for it is way too much for personal use. 
I'm sorry I posted on the wrong place!
David
