### ISSUE TITLE
Detail view in GitHub Advisory Database broken with pinned sidebar

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1056]
### Description
For example on this page https://github.com/advisories/GHSA-h7f9-cvh5-qw7f the detail header is shift to the left when the sidebar is pinned: 
![grafik](https://user-images.githubusercontent.com/424602/109368697-3ede8800-789a-11eb-8395-219fdf5ae97a.png)

While this is how it should look:
![grafik](https://user-images.githubusercontent.com/424602/109368746-6c2b3600-789a-11eb-9750-3d69b44b90dd.png)

**Proposal:** disable Octotree on these pages

### Environment (if bug)

* Octotree version: v6.2.6
* Browser & version: Firefox 86.0 (64-Bit)
* OS & version: Windows 10 Pro 20H2

**Comment by danhgit** [comment]
Thanks for reporting. Octotree probably shouldn't show up in this page. We'll fix it.

**Comment by jdreesen** [comment]
Fixed in `v6.3.1`, thx :)
