### ISSUE TITLE
GHE 3.0 sidebar tree view text is unreadable (black) in dark themes 

### ISSUE THREAD

**Issue by federkasten** [ovity/octotree#1057]
### Description

In GHE 3.0, which was released last week, the text in the sidebar tree view is black and unreadable in the dark theme. The text on github.com is displayed correctly.

### Environment (if bug)

* Octotree version: 6.3.1
* Browser & version: Firefox 86.0
* OS & version: Arch Linux

![Screenshot_2021-03-02_takashi_testing](https://user-images.githubusercontent.com/644325/109601623-8e56d980-7b62-11eb-846b-f196af572349.png)

**Comment by danhgit** [comment]
Hi @federkasten. Thanks for reporting the issue. We don't have GHE 3.0 to test, so please help check the followings:

* Do you have the same problem with other Octotree themes? (I suppose GHE 3.0 doesn't support native GH dark theme.)
* Open dev console, reload the page, find the line "GitHub Enterprise version" that Octotree prints out. What does it print?
* Please inspect any file node in the Octotree sidebar and open the "Styles" tab in the browser dev tools. Take screenshot of all the styles being applied to that element and send us.

Maybe better if you can send the info to support@octotree.io to avoid sharing more info about your GHE deployment here.

**Comment by federkasten** [comment]
Thanks @danhgit .

> Do you have the same problem with other Octotree themes?

I noticed the activity page and pull request page header are displaying strangely in the dark themes. I will send screenshots and style info to the email address later.

>  (I suppose GHE 3.0 doesn't support native GH dark theme.)

Yes. GHE 3.0 does not provide GH native dark theme.

> Open dev console, reload the page, find the line "GitHub Enterprise version" that Octotree prints out. What does it print?

No messages of Octotree were printed out to the dev console. Can you tell me how to do this in more detail?

> Please inspect any file node in the Octotree sidebar and open the "Styles" tab in the browser dev tools. Take screenshot of all the styles being applied to that element and send us.

OK. I will send the info via email later.

**Comment by danhgit** [comment]
> No messages of Octotree were printed out to the dev console. Can you tell me how to do this in more detail?

Octotree looks into the DOM to know the version of GHE in order to do some conditional logic to ensure backward compability. If it can find the version, it will print out. Looks like they change the DOM structure in GHE 3, thus no version info is printed. 

Can you help inspect the DOM or view page source to see how to get the version of GHE? If you could capture the screenshot of the DOM structure or in the page source leading to the version, so that we could build a jQuery selector that reads the version, it would help tremendously.

> OK. I will send the info via email later.

Thank you.

**Comment by federkasten** [comment]
Okay. I will also send the DOM screenshot of the version of GHE . Thanks.

**Comment by danhgit** [comment]
I've just released v7 that includes this fix. Please let me know if there's still problem. Thanks for helping me troubleshoot the issue!
