### ISSUE TITLE
[Feature Request] Expand All Folders On File Tree View On PR / Commit Pages

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1058]
### Description (Feature Request)
Would it be possible to modify the existing `Collapse tree` icon button to toggle between collapsing **and expanding all** the relevant folders within the PR and Commit pages (PR and non-PR)?

Also, as a bonus, we could maybe consider extending the feature request to apply to all other GitHub page areas, whereby all folders and files load on the extension. But there may be a performance cost impact by enabling such a feature on such a view where all folders / files are loaded onto the sidebar.

See GIF below demonstrating current `Collapse tree` facility, which correctly collapses all folders, but without a facility to expand all folders.

![Octotree_Collapse-All-But-No-Exapnd-All](https://user-images.githubusercontent.com/7581546/110455375-45ea6f00-80c0-11eb-98e9-b8581f76cdae.gif)

### System Information

* Octotree version: `6.3.0`
* Browser & version: `Chrome 89.0.4389.82`
* OS & version: `OSX Catalina 10.15.7 (19H524)`

**Comment by danhgit** [comment]
v7 supports this. Should be available in the stores shortly. Thanks for the suggestion!
