### ISSUE TITLE
Octotree login is down for Pro version

### ISSUE THREAD

**Issue by rzaharenkov** [ovity/octotree#1059]
### Description

I was looking to report that through the website but it seems that website is using the same DB which is down. So I don't see any other way to reach out rather than open the issue here.

### Environment (if bug)

* Octotree version: 6.3.0
* Browser & version: Chrome 89.0.4389.82
* OS & version: MacOS 11.2.3

**Comment by danhgit** [comment]
Hi, thanks for reporting. We're looking into this ASAP.

**Comment by jdreesen** [comment]
For me it works again.

**Comment by danhgit** [comment]
I pushed the fix. Thanks for confirming it works, @jdreesen. Should work for everyone else too. Gonna close this issue.

**Comment by jdreesen** [comment]
Thx for the very quick fix!
