### ISSUE TITLE
Does not switch to dark theme

### ISSUE THREAD

**Issue by fport** [ovity/octotree#1061]
### Description
- As you know now, it has introduced a feature that can synchronize with our system and automatically switch between day and night themes.  
![Screenshot from 2021-03-19 16-16-38](https://user-images.githubusercontent.com/56169582/111787364-e6fed400-88cf-11eb-9522-adc9fc38fe20.png)
- When you choose your theme mode as **sync with system** [GitHub Appearance](https://github.com/settings/appearance) **Octotree** doesn`t change to dark mode if you are a dark mode user.
![Screenshot from 2021-03-19 16-17-11](https://user-images.githubusercontent.com/56169582/111787573-27f6e880-88d0-11eb-9d1e-4ad972983490.png)

### Environment (if bug)
Octotree version: 6.3.1
Browser & version: Google Chrome
OS & version: Arch Linux

**Comment by Sayvai** [comment]
I am not a contributor to Octotree, but the option labelled `Sync with system` in the first screenshot you posted is a GitHub setting, and is independent of the Octotree Chrome extension as such.

If you wanted Octotree to sync with the GitHub-applied theme settings, then have you not tried to configure this from within Octotree's own theme settings, by selecting the Octotree theme configuration labelled `GitHub (default)`? 

See screenshot below.

![Screenshot 2021-03-23 at 10 23 21](https://user-images.githubusercontent.com/7581546/112132212-41df4680-8bc2-11eb-8b3a-cbfab5b71ebd.png)

**Comment by danhgit** [comment]
This was included with the update I've just published. Should be available shortly. Thanks for reporting!
