### ISSUE TITLE
[Bug]: File Changes Diff Labels Not Legible On GitHub (default) Theme

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1070]
### Description
It appears that the diff labels exposed on the file tree file changes within PRs are not legible. The text pretty much blends with the background colour. So I can barely make out the number of files / lines changed as per file.
 
![Screenshot 2021-03-30 at 09 54 13](https://user-images.githubusercontent.com/7581546/112963563-68136200-913f-11eb-9b24-aa04de036064.png)

### Environment

* Pro User: `Yes`
* Octotree version: `7.0.0`
* Browser & version: `Chrome 89.0.4389.90`
* OS & version: `Mac OSX 10.15.7`
* Console error log: `N/A`

**Comment by danhgit** [comment]
GitHub just retired some old selectors. I've fixed and published. Should be available soon.

**Comment by danhgit** [comment]
Great to hear, thanks for the confirmation!
