### ISSUE TITLE
Octotree doesn't work if the URL ends in a trailing slash

### ISSUE THREAD

**Issue by nikoladev** [ovity/octotree#1071]
### Description
Octotree doesn't load if the URL ends in a trailing slash:

- Works 🤙
  - https://github.com/pnpm/pnpm
- Fails ❌
  - https://github.com/pnpm/pnpm/

I've tested on both Firefox and Safari.

I don't know exactly when this started, but I've noticed it happening recently.

### Environment (if bug)

* Octotree version: 7.0.1
* Browser & version: Safari 14.0.3
* Browser & version: Firefox 87.0
* OS & version: macOS 10.15.7
* Screenshots:

![image](https://user-images.githubusercontent.com/15011519/113840970-8b6a8c80-9791-11eb-9ca7-d31e5556362a.png)

![image](https://user-images.githubusercontent.com/15011519/113840910-7b52ad00-9791-11eb-9aac-ebd8b81b5c79.png)

**Comment by danhgit** [comment]
We released a fix in 7.0.2. Should be available shortly. Thanks for reporting `@nikoladev!`

**Comment by jdreesen** [comment]
For me, it's working again, thx :)

**Comment by danhgit** [comment]
Thanks for confirming @jdreesen!

**Comment by nikoladev** [comment]
I can also confirm that 7.0.2 fixes it in both Safari and Firefox.

Thanks!
