### ISSUE TITLE
Unusably slow on large PRs

### ISSUE THREAD

**Issue by markhowardform3** [ovity/octotree#1072]
### Description

Octotree is unusable slow when dealing with very large PRs, often causing the browser to timeout. I generally have to disable the extension to be able to review such PRs. 

This is particularly the case when PRs contain large numbers of generated or synchronised files, for example with go modules, it is common to include all dependency sources under a `/vendor` directory (unless an organisation has a separate proxy to host these permenantely).

An example of an open source PR that is unusable with octotree is: https://github.com/goharbor/harbor-cluster-operator/pull/51

It would be great if octotree could give up after a few seconds, or possibly have an option to ignore paths entirely in PRs (

### Environment (if bug)

* Octotree version: v7.0.2
* Browser & version: Chrome - latest
* OS & version: Ubuntu 20.04.2
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
Thanks for reporting. This was fixed in 7.0.3. Large PRs should load okay now.

**Comment by markhowardform3** [comment]
Amazing. That's a huge improvement. Thanks.
