### ISSUE TITLE
Octotree tree on draft pull requests. 

### ISSUE THREAD

**Issue by llrs** [ovity/octotree#1073]
Many thanks for providing this tool, it makes easier to navigate and see the structure of a repo without opening new tabs.

### Description

I am working on a [draft PR](https://github.com/ropensci/rtweet/pull/572). When I am on it I cannot use the navigation menu as it appears a message: 
"This branch was either deleted or you don't have access to it. Please go to Settings to login with GitHub OAuth or input a GitHub access token.". 

I am logged in and I have admin rights to that repository as part of a team of an organization (The organization didn't approved octotree to access private repositories). I am using the free tier.  

### Environment (if bug)

* Octotree version: 7.0.2
* Browser & version: Firefox
* OS & version: Ubuntu 20.04
* Screenshot:

![Screenshot from 2021-04-30 00-49-16](https://user-images.githubusercontent.com/6818218/116627712-f1d86a00-a94d-11eb-93a4-e2195b0184b8.png)

* Console error log below this line

**Comment by danhgit** [comment]
Thanks for reporting. This was fixed in version 7.0.3. Please try again.

**Comment by llrs** [comment]
Many thanks for the quick fix!
