### ISSUE TITLE
[Bug]Check Icon about selected theme  is not in the correct position

### ISSUE THREAD

**Issue by underwindfall** [ovity/octotree#1074]
### Description
when I display the color theme by sidebar of browser, the icon of ✔️  is not in the corrrection position.

### Environment (if bug)

* Octotree version: 7.0.2
* Browser & version: Chrome 90.0.4430.85
* OS & version: Mac BigSur 11.2.3
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/14819756/117208667-af070e00-adf5-11eb-8f85-a49602440206.png)

**Comment by danhgit** [comment]
Gonna close as we only support GitHub's built-in themes now.
