### ISSUE TITLE
Firefox: panel blocks whole screen

### ISSUE THREAD

**Issue by lulalala** [ovity/octotree#1076]
### Description

On Firefox, when mouse is hovered over the Octotree button, it would expand to the whole screen, and user is unable to exit from Octotree.

I've only enabled Octofree extension and nothing else.

I've also tried this on Chrome, and on Chrome it displays correctly.

### Environment (if bug)

* Octotree version: 7.0.2
* Browser & version: Firefox 87.0
* OS & version: Mac OS X 10.15.7
* Screenshot ![CapturFiles_13](https://user-images.githubusercontent.com/366910/118232575-599cc200-b4c3-11eb-86ce-8528b1bae4ca.png)
* Console error log below this line: none

**Comment by danhgit** [comment]
Hi, can you re-install Octotree to see if this problem persists?

**Comment by danhgit** [comment]
I'm closing this now as I'm quite sure re-installing will fix the issue. Thanks for reporting.

**Comment by danhgit** [comment]
Sorry, you might also have to delete the "octotree.sidebar_width" local storage entry. Just go to a repo in github, open the Firefox dev tool, look for local storage and delete that entry. I think it might have the wrong value.

**Comment by lulalala** [comment]
@danhgit thanks. Yes my `octotree.sidebar_width` is 2032 somehow. After deleting it things works as expected.
