### ISSUE TITLE
Octotree login and website are down

### ISSUE THREAD

**Issue by ITProKyle** [ovity/octotree#1085]
### Description

The octotree chrome extension was logged out, disabling all pro features. Upon trying to login again, the `octotree.io` website was unreachable.

Namecheap is redirecting the request but connection is being refused.

```
HTTP/1.1 302 Found
Server: nginx
Date: Wed, 09 Jun 2021 19:51:08 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 46
Connection: keep-alive
Location: https://www.octotree.io
X-Served-By: Namecheap URL Forward

curl: (7) Failed to connect to www.octotree.io port 443: Connection refused
```

It looks like this is the second time this has happened in a fairly short period of time (#1059). Would it be possible for the extension to have less of a reliance on connecting back to the `octotree.io` service as to not break the workflow of those that rely on this tool when occasional downtime occurs?

**Comment by ITProKyle** [comment]
The service looks to be back online. The website is accessible and I am able to login.

However, there is still the the issue of making the extension (or backend service) more resilient to prevent these outages.

**Comment by danhgit** [comment]
Hi, thanks for reporting. My apologies for the problem. We'll investigate how to improve the availability of the backend.

**Comment by danhgit** [comment]
We've been running Octotree on better hardware. Hope this won't be an issue anymore. If it is, we'll make further improvement.
