### ISSUE TITLE
Jump to file diff does not work when clicking the title in PR views

### ISSUE THREAD

**Issue by tomohiro310** [ovity/octotree#1086]
### Description
When clicking the file name of a file in the sidebar of PR views, nothing happens.
This happens in every PR.

For example,
- Broken Link from Octotree
   - `https://<domain>/<owner>/<repo>/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8`
- Working Link from GitHubEnterprize
   - `https://<domain>/<owner>/<repo>/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5`

I thinks this issue is related to https://github.com/ovity/octotree/issues/1015

### Environment (if bug)
- Github: GitHub Enterprise Server 3.0.5
- Octotree version: 7.0.4
- Browser & version: Chrome Canary 91.0.4472.101
- OS & version: Windows 10 Pro 19041.685

**Comment by danhgit** [comment]
Hi, can you try these steps

Navigate to a repository in your GHE
Open the Octotree settings
Find the "GHE" textbox and enter the version of your GHE
Click "Apply Settings"
Reload the page

**Comment by tomohiro310** [comment]
Thank you for your reply.

![Screenshot from 2021-06-10 20-40-31](https://user-images.githubusercontent.com/27690577/121519032-28fd6900-ca2c-11eb-940d-ce8bc77b55d8.png)
I tried these steps, but there is no change.

The incorrect link from octotree is shorter than the correct link from GitHubEnterPrize.

**Comment by danhgit** [comment]
Hi, it looks like GHE 3.0.x changes the URL format. Can you contact me at support@octotree.io so that I can send you a build where you can test before I release it to the store? Thanks you.

**Comment by tomohiro310** [comment]
After I have updated Octotree version to 7.0.5, these wrong link problems have been resolved!
Thank you for quick handling.
