### ISSUE TITLE
file navigator is not working in pull request

### ISSUE THREAD

**Issue by frogsm** [ovity/octotree#1087]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

At some point, the file navigation function will not work in pull requests.
I'm sorry that I can't attach a screenshot because of the security of the code.
This happens at Github Enterprise.

### Environment (if bug)

* Octotree version: v7.0.5
* Browser & version: chrome 91.0.4472.106(stable) (x86_64)
* OS & version: Mac OS Bigsur 11.3
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
Hi, can you try these steps

Navigate to a repository in your GHE
Open the Octotree settings
Find the "GHE" textbox and enter the version of your GHE
Click "Apply Settings"
Reload the page

If it still doesn't work, please send me an email at support@octotree.io with more info: GHE version, the format of the URL in Octotree sidebar vs the actual URL.

**Comment by frogsm** [comment]
Wow, thank you so much. It's working very well.
