### ISSUE TITLE
[feature request] In PR review, the file tree should highlight the files that are currently visible in the viewport

### ISSUE THREAD

**Issue by lolmaus** [ovity/octotree#1088]
It would make navigating the PR diff *much* easier!

It could look like this:

![image](https://user-images.githubusercontent.com/200884/122765675-6d4cfc80-d2a9-11eb-83c6-b6203ac91845.png)

**Comment by danhgit** [comment]
We added this in v7.0.6. Please give it a try and let us know if it works as expected. Thanks for the suggestion!

**Comment by lolmaus** [comment]
This is awesome! Thank you so much for implementing it!

Some considerations:

1. On the dark theme at least, the highlight is bare visible. At daytime I have some glare on the screen and I have to really strain my eyes to see the highlight.

    I used a userCSS to make it brighter, though I had to come up with a ridiculous selector to overcome the Octotree's own selector specificity.

2. More than one file may be visible on the screen at once. It would be nice if all (partially) visible files were highlighted in the tree.

**Comment by danhgit** [comment]
Hi, I'm gonna close this issue now. For dark theme, now that we fully support GitHub's dark themes (including the new high contrast and color-blind themes), I hope this is no longer an issue for you. Thanks.
