### ISSUE TITLE
Branch tree and name not updating unless I refresh

### ISSUE THREAD

**Issue by Quentin1010** [ovity/octotree#1090]
### Description
When I switch branch in Github UI, I can see a small spinner showing in Octotree, but then the tree doesn't update itself until I refresh the whole web page.

### Environment (if bug)

* Octotree version: 7.0.6 (free account)
* Browser & version: Chrome 91.0.4472.114
* OS & version: macoS Big Sur 11.3.1

![image](https://user-images.githubusercontent.com/24384117/126542788-2593eb0a-c111-4cb3-b58e-6834fcb9c435.png)

**Comment by jsec** [comment]
Also having the same issue.

Environment: 
Ocototree version: 7.0.6 (Pro)
Browser: Chrome 90.0.4430.212 
OS: Windows 10

**Comment by danhgit** [comment]
Hi, this should have been fixed in the last released. If not, please let me know to re-open. Thanks.
