### ISSUE TITLE
Repository tree is not shown for Pull Requests due to error

### ISSUE THREAD

**Issue by ava1ar** [ovity/octotree#1091]
### Description
I am using Octotree with GitHub Enterprise and recently start getting issue with displaying the repository tree fro pull requests: instead of a tree, I am seeing following error message: "can't access property "digest", crypto.subtle is undefined"

### Environment (if bug)

* Octotree version: 7.0.7
* Browser & version: Firefox Developer 91.0b7
* OS & version: Windows 10 (build 1909)
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
Hi, I believed I have responded via email and resolved this for you, but if I'm mistaken, please follow these steps:

* Open Octotree settings
* Scroll to the bottom
* Enter the version of your GHE in the "GHE version" textbox
* Save and reload
