### ISSUE TITLE
Feature Request: Support Cascadia Code

### ISSUE THREAD

**Issue by BasixKOR** [ovity/octotree#1092]
Cascadia Code is integrated into many products such as VS Code, Windows Terminal. It would be nice to use it on GitHub as well, although I'm unsure if they already switched the default to Cascadia Code.

**Comment by danhgit** [comment]
Thanks, Cascadia Code looks great. Will add it in the next release.

**Comment by danhgit** [comment]
Cascadia Code has been supported since 7.2.
