### ISSUE TITLE
Painfully slow browsing experience on very large repos

### ISSUE THREAD

**Issue by lolmaus** [ovity/octotree#1093]
### Description

When viewing very large repos, Octotree makes the browser tab freeze for many seconds.

Example: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yadda

The short term solution could be adding a repo ignore list to Octotree settings, so that I can disable Octotree for https://github.com/DefinitelyTyped/DefinitelyTyped . The tree in such repos is unusable anyway.

### Environment (if bug)

* Octotree version: v7.0.7
* Browser & version: Vivaldi 4.1.2369.21 (based on Chrome 92.0.4515.159)
* OS & version: Windows 64-bit Pro 10.0.19043 Build 19043
* PC: Ryzen 2700X, 64 GiB RAM, Intel Optane 900P SSD

**Comment by danhgit** [comment]
There have been many perf improvements over the past year and at this point, we think it works quite well even for very large repos like this. I'm closing this ticket now, but if anyone still experiences poor experience, please let us know.
