### ISSUE TITLE
Text with GitHub dark modes is illegible dark colors

### ISSUE THREAD

**Issue by jayqi** [ovity/octotree#1094]
### Description
Starting today, text in the Octotree sidebar appears in dark blue in all of GitHub's dark modes, which makes them hard to read. The settings page also has text appearing in dark gray which is similarly illegible. 

### Environment (if bug)

* Octotree version: v7.1.0
* Browser & version:  Google Chrome 93.0.4577.82
* OS & version: macOS 10.15.7
* Screenshot, if any (drag an image here)

<img width="768" alt="Screen Shot 2021-10-01 at 3 19 32 PM" src="https://user-images.githubusercontent.com/2721979/135675891-c51a833d-f8c0-445c-b77a-2f00b822f62c.png">

<img width="768" alt="Screen Shot 2021-10-01 at 3 27 31 PM" src="https://user-images.githubusercontent.com/2721979/135676076-83bdc5b5-3124-482e-b479-eb3b0f6b3bce.png">

* Console error log below this line

**Comment by mengesb** [comment]
Seems the "themes" are gone ... I have the same dark blue on black text; but I'm guessing you're using the vscode icons so at least those can be seen, using github icons makes it too tark to read anything

**Comment by danhgit** [comment]
Hi, GitHub made a change that broke our color. We've already submitted v7.1.1 that fixes this. Should be available soon. Thanks for reporting!

**Comment by wenfangdu** [comment]
Until the official fix, you can use [this theme](https://github.com/wenfangdu/github-brighter-text):

![image](https://user-images.githubusercontent.com/28700378/135706431-0b5baeec-b1a2-4b22-b51b-e754c10e1519.png)

**Comment by moeen-mahmud** [comment]
I've removed Octotree and add it again, but it still doesn't work.

![octotree](https://user-images.githubusercontent.com/61315959/135718698-e559cba6-04b6-4805-88aa-0f3de7b2fa2c.png)

**Comment by jerryc127** [comment]
> I've removed Octotree and add it again, but it still doesn't work.
> 
> ![octotree](https://user-images.githubusercontent.com/61315959/135718698-e559cba6-04b6-4805-88aa-0f3de7b2fa2c.png)

![image](https://user-images.githubusercontent.com/16351105/135726704-835d570d-c6d6-4dc1-ab78-3671dbbb2de7.png)

same as you

**Comment by danhgit** [comment]
Hi, currently v7.1.1 with the fix is already available on Firefox. For other stores, we already published to all of them yesterday, but it has to go through the moderation process. This could take several days. I'll keep you posted. Thank you.

**Comment by moeen-mahmud** [comment]
> Hi, currently v7.1.1 with the fix is already available on Firefox. For other stores, we already published to all of them yesterday, but it has to go through the moderation process. This could take several days. I'll keep you posted. Thank you.

Thanks for the response! 
Hopefully, we will get the update soon. 😇

**Comment by qoobes** [comment]
That's amazing, I've just started running into the issue, and it seems it's already fixed. Good job on the fast responses!

**Comment by tolumide-ng** [comment]
Hopefully, this comes soon for chrome users also. Thank you for the fast response 👍🏽

**Comment by micalevisk** [comment]
I'm using v7.1.1 in Firefox. Is the following expected?

![image](https://user-images.githubusercontent.com/13461315/135758044-d8f33370-e778-42db-ac7a-6a63a243349f.png)

**Comment by danhgit** [comment]
It's not expected. GitHub seems to be working hard on the theme and UI refactoring stuff.

We've just submitted 7.1.2 that fixes the issue @micalevisk reported and some more. It's already available on Firefox (gotta love the people at Mozilla). Other stores will typically takes more time. Please be patient.

There could be issues we missed or more changes from GitHub in the next few days. Please help report any you see and we'll try our best to address them quickly. Thanks everyone!

**Comment by danhgit** [comment]
The update is already available on Chrome and Safari. Please give it a try.

**Comment by tolumide-ng** [comment]
@danhgit it works perfectly on Brave browser now, thank you!!!

**Comment by jayqi** [comment]
v7.1.2 works great on Chrome. The issue is resolved for me and I'm happy to consider it closed, though I don't know if you want to still keep it open to track things for other browsers.

**Comment by danhgit** [comment]
Thanks for confirming @tolumide-ng and @jayqi! I'll leave it here a bit longer in case GitHub hasn't finished their refactoring and there are new issues.

**Comment by danhgit** [comment]
@jinyongp thanks. We're aware of the issue. Working on a fix, will release with support for the new GitHub color-blind theme.

**Comment by danhgit** [comment]
@jinyongp I've just released 7.2 to the stores. Should be available soon. Thank you!

**Comment by bimp** [comment]
getting this issue with 7.2.0 in both Chrome and Edge today? ideas?

**Comment by danhgit** [comment]
@bimp can you share screenshot, OS and which GitHub dark theme you use?

Thanks.

**Comment by bimp** [comment]
@danhgit I'm seeing it with ANY dark theme:
![image](https://user-images.githubusercontent.com/580277/140240241-41bc0562-645c-40b8-994f-73bb11fe9e55.png)

I'm on Windows 10 Version 21H1 (OS Build 19043.1288)
I'm also using it on GitHub Enterprise 2.22.17
![image](https://user-images.githubusercontent.com/580277/140240538-95c3ddaf-c7c3-4e68-baf9-d9fd9e587829.png)

**Comment by danhgit** [comment]
Is this Octotree dark theme or GitHub dark theme?

**Comment by bimp** [comment]
> Is this Octotree dark theme or GitHub dark theme?

Both. Any kind of dark theme has the issue. Im having to resort to Github default with the light theme in order to see text in sidebar

**Comment by danhgit** [comment]
This is GitHub Enterprise, right? If so, please contact us at support@octotree.io so that we can get more info. This issue is for GitHub dark theme on github.com.

**Comment by bimp** [comment]
> This is GitHub Enterprise, right? If so, please contact us at [support@octotree.io](mailto:support@octotree.io) so that we can get more info. This issue is for GitHub dark theme on github.com.

@danhgit I sent an email couple of days so please let me know if you need additional info. thanks
