### ISSUE TITLE
Sidebar hard to use / read with GitHub Dark mode

### ISSUE THREAD

**Issue by ApexModder** [ovity/octotree#1095]
### Description
Using GitHub's built in Dark Theme the side bar is hard to read.
Can enable this theme using `Settings > Appearence`  and enabling any of the Dark themes.
Light themes are much easier to use & read, but those are hard on the eye at times.

### Environment
* Octotree version: 7.1.0
* Browser & version: Mozilla FireFox 92.0.1 (64-bit)
* OS & version: Windows 10 (21H1 19043.1237)

![Error Preview](https://user-images.githubusercontent.com/29412632/135693736-d667b219-3c22-45e7-a961-2ba85c8f935c.png)

**Comment by ApexModder** [comment]
Right after posting this issue, I noticed there was another issue about this that I didnt spot before #1094

**Comment by danhgit** [comment]
Hi, thanks for reporting. I'm gonna close this so that everyone can track https://github.com/ovity/octotree/issues/1094
