### ISSUE TITLE
Themes are gone

### ISSUE THREAD

**Issue by rozag** [ovity/octotree#1096]
### Description
Themes button is not here anymore and I have to use a theme provided by Github instead of my favorite Octotree's one.

### Environment (if bug)

* Octotree version: 7.1.2
* Browser & version: Firefox 92.0.1
* OS & version: macOS 11.6
* Screenshot, if any (drag an image here)
<img width="1920" alt="Screenshot 2021-10-04 at 13 43 41" src="https://user-images.githubusercontent.com/4456745/135838532-fac65b64-6b56-494e-9d1d-52ddd17bb981.png">

**Comment by macintacos** [comment]
Was just about to report this, my colors are also all out of whack now (it seems to revert to some default theme instead of the one you previously had selected).

**Comment by bmoyer240** [comment]
![image](https://user-images.githubusercontent.com/6550299/135874958-1d756240-b17a-42fa-86c6-d7b480ac6f2b.png)
![image](https://user-images.githubusercontent.com/6550299/135875086-dec538f9-ca18-4729-bafd-bbca1c665664.png)

**Comment by macintacos** [comment]
Ah looks like this is #1094.

**Comment by danhgit** [comment]
@macintacos yes, the theme issue can be tracked in the other ticket.

@rozag we stopped support Octotree dark themes since 7.1 to focus on supporting the new GitHub's dark themes. Please see the release note below (it's also in the app, if you click the yellow banner in the Octotree sidebar). As mentioned in the that note, you can use [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark) to enable custom themes. Sorry about the inconvenience. 

> In the latest version of GitHub, its DOM has changed so much and breaks all Octotree's dark themes. In the past, we supported dark themes because GitHub didn't. However, GitHub now supports [various dark themes](https://github.com/settings/appearance). Ensuring that Octotree works well with these built-in themes is already hard, maintaining our own themes, amidst frequent GitHub DOM changes and lots of CSS selector conflicts, has become increasingly infeasible and resulted in highly brittle code, with lots of <i>!important</i> declarations and other ugly hacks.
>
> After failed attempts to fix the broken themes and through much consideration, we've decided to drop the support for Octotree's dark themes (except in old versions of GitHub Enterprise that use old DOM and styles). We'll focus energy on making sure Octotree works well with GitHub's built-in themes. Those who miss old dark themes can use [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark), which supports Octotree and has a broad selection of themes.
>
> We apologize for the inconveniences and hope to receive your continued support.

**Comment by rozag** [comment]
Oh well, that's sad, but I feel your pain, thanks for the quick response.
