### ISSUE TITLE
FAQs / Troubleshooting

### ISSUE THREAD

**Issue by danhgit** [ovity/octotree#1097]
# Please refer to the user guide below

**User guide**: https://www.octotree.io/features

---

# The following contents are DEPRECATED

### Dark theme no longer works
In the past, we supported dark themes because GitHub didn't. It [does now](https://github.com/settings/appearance) and keeps adding more themes and introducing changes. Supporting GitHub themes while maintaining our own themes, amidst frequent GitHub DOM changes and enhancements, has become increasingly challenging and resulted in highly brittle code (lots of `!important` declarations and other ugly hacks). As of v7.1, we decided to drop support for Octotree's dark themes so that we can focus on making sure Octotree works well with GitHub's built-in themes. Those who miss old Octotree dark themes can use [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark), which supports Octotree and has a broad selection of themes.

### "The branch was deleted or access is denied"
Please ensure that you already authenticated with GitHub (i.e. "Login with GitHub" in Octotree)  or supplied a personal access token. Check out [this guide](https://www.octotree.io/features#authentication).

If you did that and the issue persists, the repository probably belongs to an organization that Octotree doesn't have access to. Go to [this page](https://github.com/settings/connections/applications/746ccaaa555c27cb1f7a) to grant permission.

### Octotree sidebar doesn't stay in the pinned position
Try these steps:
* Uninstall all versions of Octotree, including local version if any, from your browser
* [Download](https://www.octotree.io/download) and install it again

### Not able to access Pro features

If you're a Pro user and can't access Pro features, perform these steps:
* If you had linked GitHub with Octotree, go to Octotree's settings screen and unlink GitHub
* Logout of Octotree
* Login with your __Octotree email and password__ (not via GitHub OAuth)
* Go to settings screen to link with GitHub if needed

If still not work, try re-installing Octotree and try again.

### Migrate GitHub connection from one Octotree account to another Octotree account

* Go to [www.octotree.io](http://www.octotree.io/)
* Login with the Octotree account you have GitHub connected to
* Go to the Account page (click the link in the top right corner of the page)
* Disconnect GitHub from the account
* Logout and login with the other account (the one you want to link with GitHub)
* Go to the Account page
* Connect to GitHub

## Safari

If you receive this error: 
<img src="https://user-images.githubusercontent.com/38257704/147523256-8ea91e62-bb76-464a-86b2-e23622c0f989.png" width="500">

Run this command in the terminal ([why](https://github.com/ovity/octotree/issues/1110))

```bash
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Safari.app
```

### Cannot navigate files in pull requests or styles are broken
Perform these steps:
* Navigate to a repository in your GHE
* Open the Octotree settings
* Find the "GHE" textbox and enter the version of your GHE
* Click "Apply Settings"
* Reload the page

**Note:** If it still doesn't work, try using "3.0" in the "GHE" textbox.

## Others
* [Plan comparison](https://www.octotree.io/pricing)
* [Complete user guide](https://www.octotree.io/features)
* For feature requests & bugs, [create ticket](https://github.com/ovity/octotree/issues/new) or 
* For payment & billing, email us support@octotree.io from your Octotree's email.

**Comment by MarianoRui** [comment]
Marca error

**Comment by 40w7or** [comment]
Farhat_a22

**Comment by 40w7or** [comment]
Hack

**Comment by danhgit** [comment]
Use this instead: https://www.octotree.io/features#troubleshooting
