### ISSUE TITLE
Octotree icon is much bigger than other macOS apps

### ISSUE THREAD

**Issue by sargunv** [ovity/octotree#1099]
### Description

This is a fairly minor issue, but I noticed the icon for Octotree on macOS doesn't quite match the system standards, it's much bigger than all the other apps, which all have a consistent size/shape (except Magnet). See screenshot:

<img width="1512" alt="Screen Shot 2021-10-29 at 17 35 53" src="https://user-images.githubusercontent.com/1320357/139513995-1b440861-e478-4f97-b4c1-be0a4ebfbaf3.png">

### Environment (if bug)

* Octotree version: 7.1.2 (52)
* Browser & version: N/A
* OS & version: macOS 12.0 Monterey

**Comment by sargunv** [comment]
And here's a screenshot on the dock:
<img width="1512" alt="Screen Shot 2021-10-29 at 19 02 51" src="https://user-images.githubusercontent.com/1320357/139516645-96861c30-b44f-4e73-ad46-323a50cbf515.png">

**Comment by danhgit** [comment]
Good catch. We just published an update that fixes this.

**Comment by danhgit** [comment]
It might take a few days to be available though. Thanks for reporting!

**Comment by sargunv** [comment]
thanks!
