### ISSUE TITLE
Files sorting order not matching GitHub

### ISSUE THREAD

**Issue by m-radzikowski** [ovity/octotree#1105]
### Description

If repo has two directories, `lorem` and `lorem-ipsum`:

- GitHub shows longer first
- Octotree shows shorter first

Shorter first makes more sense, however it differs from GitHub. It's especially annoying in Pull Requests (in pro version), where you select first file from the top in Octotree and it scrolls down to the middle of the PR since GitHub has different sorting.

### Environment (if bug)

* Octotree version: 7.2.5

### Related

#582, #899

**Comment by danhgit** [comment]
Fixed in 7.3, Octotree now matches GitHub sort order exactly. Thanks for reporting.
