### ISSUE TITLE
Where are release notes published?

### ISSUE THREAD

**Issue by jayqi** [ovity/octotree#1106]
Sometimes I see the banner notification in the sidebar notifying a new release, but I'm in the middle of something and click away before checking it out, and then I lose that banner. 

I haven't been able to find a link to release notes in the sidebar, this repo, or https://www.octotree.io/. It would be great if release notes were prominently linked and easily findable in any or all of those places.

**Comment by amerixan** [comment]
If you download the latest tag (might be any tag), there is a `HISTORY.md` file in the archive that is essentially a change log.  It's strange to me that is not included in the root of the main branch of the repository by default.

@jayqi I agree that it would be very nice to have a `CHANGELOG.md` at the very least so people know where to look for the most recent changes.

**Comment by danhgit** [comment]
@jayqi thanks for the suggestion. We thought the little popup was convenient for people to discover the changes but what you described makes sense. I've just put the recent changes on [our website](https://www.octotree.io/changes). Will update and link to this moving forward.

@amerixan we don't maintain the code in this repo. It's mentioned in the README. I've just moved the notice up in the README to make it clearer. Thanks.
