### ISSUE TITLE
View Full button missing

### ISSUE THREAD

**Issue by brian-captain-crosby** [ovity/octotree#1109]
### Description

The `View Full` button is no longer there when viewing PR files. It used just left of the Viewed checkbox.

I tried in incognito mode with other extensions disabled but it still didn't work.

### Environment (if bug)

* Octotree version: v7.2.5
* Browser & version: Chrome Version 96.0.4664.110 
* OS & version: macOS Catalina version 10.15.7
* Screenshot, if any (drag an image here)

expected:
![image](https://user-images.githubusercontent.com/11326835/147039343-961ec827-741c-4d09-99dd-4e79cd8fb185.png)

actual:

![image](https://user-images.githubusercontent.com/11326835/147039378-beb3c9ed-f84e-4c90-9606-54304771262f.png)

* Console error log below this line
  - Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
  - DevTools failed to load source map: Could not load content for chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
  - POST https://collector.githubapp.com/github/collect net::ERR_CONNECTION_REFUSED analytics-client.js:47

**Comment by danhgit** [comment]
It was reported before: https://github.com/ovity/octotree/issues/1104. Basically GitHub added this functionality and also broke ours, so we removed it.

That said, the GitHub's button is easy to miss. In addition, after using it in the past few weeks, I think I'd prefer the Octotree's view-full popup better :). I'll fix the issue and add back the button.

**Comment by danhgit** [comment]
Please look out for v7.3 which contains the fix. Thanks.
