### ISSUE TITLE
The operation couldn’t be completed. (SFErrorDomain error 1.)

### ISSUE THREAD

**Issue by Adrift001** [ovity/octotree#1110]
### Description
when I click `Quit and Open Safari Extensions Preferences...`, A prompt box pops up.
### Environment (if bug)

* Octotree version: 7.3.0
* Browser & version: Safari
* OS & version: macOS 12.1 (21C52)
* Screenshot, if any (drag an image here)
<img width="503" alt="image" src="https://user-images.githubusercontent.com/8119320/147519122-74260de4-46ce-4314-bdb1-043493b991bc.png">
* Console error log below this line
I don't know how to get logs

**Comment by danhgit** [comment]
Did you install Octotree from the [App Store](https://apps.apple.com/us/app/octotree/id1457450145?mt=12)?

**Comment by Adrift001** [comment]
yes

**Comment by Adrift001** [comment]
I deleted it and reinstalled it. This still happens

**Comment by Adrift001** [comment]
https://github.com/refined-github/refined-github/issues/4353
It helped me solve the problem.
I run `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Safari.app`, then safari Prompt for new extensions available. then It's ok.

**Comment by danhgit** [comment]
Thank you! I'll update the Troubleshooting Guide with this.

**Comment by PC-Chiu** [comment]
@Adrift001 🐮
