### ISSUE TITLE
Multiple tabs during PR codereview

### ISSUE THREAD

**Issue by fischman-bcny** [ovity/octotree#1113]
Using Octotree in Chrome with a Pro subscription, I was hoping to be able to open the files involved in a PR in multiple tabs as is possible while browsing a repository. Is this somehow possible already today? 
Double-clicking in a PR's sidebar's file tree behaves as if I've single-clicked, scrolling the "Files changed" view to the file in question, but I'm hoping it's possible to open each file in a separate tab to review the entire file at a time.

* Octotree version: 7.3.0
* Browser & version: Chrome 97.0.4692.99
* OS & version: macOS 12.1

**Comment by danhgit** [comment]
Sorry to take long, this is now supported in 7.10.0 (should be available shortly in the stores). Just hover a file, click the "open external" icon <img width="27" alt="image" src="https://github.com/ovity/octotree/assets/38257704/024c24f6-c7ec-4d8c-b1d7-7eadb5f847db"> to open it in a new tab.
