### ISSUE TITLE
[Safari] number pills get duplicated at the bottom of a repo

### ISSUE THREAD

**Issue by kevcube** [ovity/octotree#1116]
### Description
in safari, if you navigate to a repo page, click any file, then go back, all number pills are duplicated at the bottom of the page beneath the readme.

### Environment (if bug)

* Octotree version: safari latest
* Browser & version: safari latest
* OS & version: Mac m1 latest
* Screenshot, if any (drag an image here)
* Console error log below this line

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/716806/155228696-1a7c540d-9bd5-49fd-bb97-2f7dce992a8f.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/716806/155228771-ac2d7c0a-9dff-4f85-9a0b-4371571f0a90.png">

**Comment by jdreesen** [comment]
I noticed this, too.

Environment:
- Octotree version: v7.4.0
- Browser & version: 97.0.1 (64-Bit)
- OS & version: Windows 10 Pro 21H2

**Comment by danhgit** [comment]
We fixed this in 7.4.3. Thanks for reporting @jdreesen @kevcube

**Comment by kevcube** [comment]
@danhgit I'm still seeing this in Safari

**Comment by jdreesen** [comment]
@danhgit Me too. 

Current Environment is:
- Octotree version: v7.4.3
- Browser & version: Firefox 98.0.2 (64-Bit)
- OS & version: Ubuntu 20.04.4 LTS
