### ISSUE TITLE
Octotree does not refresh PR file tree after clicking on the `reload` button

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1122]
### Description
When I'm on a PR page and the author pushes new changes, GitHub displays a `Reload` button at the top which refreshes the view. But it seems that Octotree doesn't refresh when I click it. 

I just had the case where the PR author deleted some files, but Octotree still showed them until I hit F5.

### Environment (if bug)

* Octotree version: v7.4.0
* Browser & version: 98.0 (64-Bit)
* OS & version: Ubuntu 20.04.4 LTS

**Comment by danhgit** [comment]
Seems duplicated with https://github.com/ovity/octotree/issues/1136. I'm closing it, but please let me know if it's a actually different bug.

**Comment by jdreesen** [comment]
No, I think it's the same. Apparently I opened an issue twice :see_no_evil:

**Comment by danhgit** [comment]
Thanks for confirming.
