### ISSUE TITLE
Cannot launch octotree on chrome

### ISSUE THREAD

**Issue by hejiaji** [ovity/octotree#1132]
### Description
Cannot launch octotree on chrome, clicking the extension icon renders nothing

### Environment (if bug)
* Octotree version: 7.5.1
* Browser & version: Chrome 102.0.5005.61
* OS & version: macOS Monterey 12.3.1 
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/19968961/173801806-844cea89-b784-49ef-b56b-a0a74b0386be.png)

* Console error log below this line
Nothing in the console

**Comment by danhgit** [comment]
Sorry for the delayed response. If you go to the root of a repository or a pull request review page, would Octotree show up? Because depending on the display mode, Octotree might hide itself in Issue page.

**Comment by danhgit** [comment]
If that doesn't help, please re-install Octotree and try again. Thanks.

**Comment by danhgit** [comment]
Gonna close it. If the above instructions don't help, please let me know.
