### ISSUE TITLE
Prevent scroll from bubbling up to GitHub page.

### ISSUE THREAD

**Issue by HarshKapadia2** [ovity/octotree#1135]
### Description

When Octotree has a scroll in a repository:
- Once the top/bottom of the list is reached in Octotree after scrolling, the parent (GitHub page) starts scrolling and the current position in the open file is lost (as it scrolls), which is frustrating.
   - The scroll/wheel event should be stopped from bubbling to the GitHub page.
- It would be nice to have a (thin) scrollbar.
   - If the scrolling of the GitHub page is intentional, then at least adding a scrollbar would be nice so that the user knows that they have reached the beginning/end of the list.

### Current Behaviour

https://user-images.githubusercontent.com/50140864/178098092-38d29905-9378-4a89-b595-8ed23eb2d8a8.mp4

#### Environment

> This is the environment used in the above video.

* Octotree version: v7.5.3 (Logged in free user)
* Browser & version: Microsoft Edge v103.0.1264.44 (Official build) (64-bit)
* OS & version: Windows 11 Home Single Language 21H2 build 22000.778

**Comment by danhgit** [comment]
We fixed in 7.6. Please look out for that version.
