### ISSUE TITLE
Octotree does not update its files when clicking on the `Refresh` button in a PR

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1136]
### Description
When someone pushes changes to a PR, GitHub displays a ![grafik](https://user-images.githubusercontent.com/424602/179535608-5d539eae-b979-4294-8d78-67a2806e5caa.png) button in the changes view. When clicking on it, the view updated. If the changes include new files, I'd expect them to appear in Octotree, but they don't!

### Environment (if bug)

* Octotree version: v7.5.3
* Browser & version: Firefox 102.0 (64-Bit)
* OS & version: Ubuntu 20.04.4 LTS

![grafik](https://user-images.githubusercontent.com/424602/179536089-4fb38055-1a20-4e33-bd3b-3f98c7f913c4.png)

**Comment by danhgit** [comment]
We fixed in 7.6. Please look out for that version.

**Comment by danhgit** [comment]
@jdreesen was this fixed for you?

**Comment by jdreesen** [comment]
I wasn't able to verify it completely, but it seems to work, thx!
