### ISSUE TITLE
OctoTree no longer working for me

### ISSUE THREAD

**Issue by nevack** [ovity/octotree#1141]
### Description

<table>
<tr>
	<td><img width="325" alt="image" src="https://user-images.githubusercontent.com/8330119/194910360-70bbcd23-7c3e-4f1d-a684-c8be9c266605.png"></td>
	<td><img width="324" alt="image" src="https://user-images.githubusercontent.com/8330119/194910215-f2509589-dc68-44de-9440-c552aa46df99.png"></td>
</table>

### Environment (if bug)

* Octotree version: 7.6.1
* Browser & version: Google Chrome 106.0.5249.103
* OS & version: macOS Ventura 13.0 (22A5365d)
* Console error log below this line
```
POST https://collector.github.com/github/collect net::ERR_CONNECTION_REFUSED
send @ analytics-client.js:47
sendPageView @ analytics-client.js:28
n @ hydro-analytics.ts:63
(anonymous) @ hydro-analytics-pageview.ts:25
await in (anonymous) (async)
21693 @ hydro-analytics-pageview.ts:26
c @ bootstrap:19
b @ behaviors-ddd03c44fdaa.js:132
(anonymous) @ behaviors-ddd03c44fdaa.js:132
c.O @ chunk loaded:23
(anonymous) @ behaviors-ddd03c44fdaa.js:132
b @ jsonp chunk loading:71
(anonymous) @ behaviors-ddd03c44fdaa.js:1
```

**Comment by danhgit** [comment]
Hi, I can't reproduce this. Does the error still persist? If it does, can you send a complete log (the one attached here doesn't look like it comes from Octotree)? Thanks.

**Comment by nevack** [comment]
> Does the error still persist?

Yes, it does.

> Can you send a complete log?

Of course, but what log do you expect?
Are there some diagnostics captured by extension itself?
Because the only error I can see in tab console is already attached.

**Comment by danhgit** [comment]
Sorry about that 😢... Can you try uninstall Octotree and try again? If that doesn't work, please email support@octotree.io so I could ask for more information to troubleshoot the issue.

**Comment by nevack** [comment]
> Sorry about that cry... Can you try uninstall Octotree and try again? If that doesn't work, please email [support@octotree.io](mailto:support@octotree.io) so I could ask for more information to troubleshoot the issue.

Full reboot of my machine has helped, weird.

Thank you anyway, feeling really stupid now for not trying this first :/
