### ISSUE TITLE
Disable OctoTree on `apps` pages

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1144]
### Description
The URL path prefix "/apps" is used for GitHub apps.

### Problem

Those pages have no repo and OctoTree doesn't work.

### Screenshots

![image](https://user-images.githubusercontent.com/424602/199931718-e4017c25-e85d-446a-90a6-763083830489.png)

### Environment (if bug)

* Octotree version: v7.7.0
* Browser & version: Firefox 106.0.2 (64-Bit)
* OS & version: Ubuntu 20.04.5 LTS

**Comment by danhgit** [comment]
Fixed in 7.8
