### ISSUE TITLE
The operation couldn't be completed. (SFErrorDomain error 1.)

### ISSUE THREAD

**Issue by Charliego93** [ovity/octotree#1145]
### Description
When I click the `Quit and Open Safari Extensions Preferences...` button, it says `The operation couldn't be completed.
(SFErrorDomain error 1.)`

Try scenarios:
1. Uninstall and reinstall
2. run `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Safari.app` and `reboot` 
#1110

But it didn't work, it's still in an unusable state

### Environment (if bug)

* Octotree version: `Version 7.7.0 (83)`
* Browser & version: `Safari 13.1.3 (15609.4.1)`
* OS & version: `10.15.7 (19H15)`
* Screenshot, if any (drag an image here)
<img width="532" alt="image" src="https://user-images.githubusercontent.com/26761592/203744616-6182af3a-8206-49f7-9019-ae09916faea2.png">
* Console error log below this line

**Comment by Charliego93** [comment]
After I upgrade Safari to `15.6.1 (15613.3.9.1.16, 15613)`, it works fine, please ignore this issue.

**Comment by PC-Chiu** [comment]
Same error on Safari 15.6.1, What's to be done?

Octotree version: Version 7.7.0 (83)
Browser & version: Safari 15.6.1 (15613.3.9.1.16, 15613)
OS & version: 10.15.7 (19H2026)
Screenshot:
<img width="532" alt="截屏2023-02-03 下午5 33 19" src="https://user-images.githubusercontent.com/8520547/216565671-99bee052-6c78-40d2-b89b-49bdb2688b14.png">

**Comment by danhgit** [comment]
Hi @PC-Chiu, please look at https://github.com/ovity/octotree/issues/1097, there's instruction to solve this particular issue.

**Comment by PC-Chiu** [comment]
@danhgit Thank you! The solution is right, Octotree work fine after run the command.
