### ISSUE TITLE
Not getting my pro features

### ISSUE THREAD

**Issue by grimurjonsson** [ovity/octotree#1147]
### Description
Im having some problems with my Pro account.
* I cant double click files for tabs
* The font doesnt update when I change it
* The "trial" text is there.

I assume that this is because the plugin doesnt recognize me as Pro.

My octotree/github setup is 
* i have a github account, with a repo that requires SSO. I've created a token and authorized that token with the SSO. This seems to work, as the extensions basic features work.
* my octotree email is NOT my main email on github, altho i've set it up as an alternative email.

What I've done to try to make it work.
* I've unlinked the github account from my octotree account, logged out and in again and reconnected the extension in the browser.
* I've tried both 0auth and github login in the extension

I'm sure im just missing something obvious.

### Environment (if bug)

* Octotree version: 7.7.0
* Browser & version: Chrome - Version 108.0.5359.96 (Official Build) (64-bit)
* OS & version: win 11
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
Hi @grimurjonsson. Please try the instructions [in this guide](https://github.com/ovity/octotree/issues/1097) to update the GitHub connection. The 2 relevant sections are: "Not able to access Pro features" and "Migrate GitHub connection from one Octotree account to another Octotree account". 

If performing those steps doesn't fix the issue, please email to support@octotree.io with the following information:
* Your Octotree pro email address
* The GitHub username you link with Octotree (in case it's not grimurjonsson)

**Comment by danhgit** [comment]
Hi, I hope the issue has been resolved. If not, please reach out to support@octotree.io with the requested information. I'm closing this issue now. Thank you.
