### ISSUE TITLE
Feature request: search files with regex

### ISSUE THREAD

**Issue by gforien** [ovity/octotree#1148]
### Description
Searching file names with a regular expression would be a great feature !

Ex:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/7701186/210917401-acb38394-25a2-45bf-968d-3e62da056ea4.png">

Thank you for your time 🙏

**Comment by danhgit** [comment]
Thanks for the suggestion. We'll look into this.

**Comment by danhgit** [comment]
This is supported in 7.10.0 (available to stores soon).
