### ISSUE TITLE
Bug: `view PRs` not loading PRs

### ISSUE THREAD

**Issue by gforien** [ovity/octotree#1149]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue:
- in octotree, click on `View pull requests`
- *expected*: list of PRs
- *happened*: infinite scrolling
<img width="434" alt="image" src="https://user-images.githubusercontent.com/7701186/210918935-f4275172-c5ce-4cf3-bb16-1391ae65f20c.png">

Request is made to `api.github.com` but this is GHES with a custom domain name eg `github.mycompany.com/api`
<img width="778" alt="image" src="https://user-images.githubusercontent.com/7701186/210919203-5aeeb731-0416-4df0-a76e-930147dcd2c7.png">

### Environment (if bug)

* Octotree version: 7.7.1
* Browser & version: Chrome 108.0.5359.124 (official build) (arm64)
* OS & version: MacOS 12.4
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
@gforien can you try version 7.8 and see if it fixes the problem? If not, I would appreciate if you reach out via support@octotree.io so that we could gather some more information about your GHE deployment.
