### ISSUE TITLE
OctoTree doesn't work at all

### ISSUE THREAD

**Issue by Speiger** [ovity/octotree#1151]
### Description
Installed OctoTree on Opera using operas addon installer (reinstalled today just to double check)
And it doesn't show up.
I gave permission to access githubs site.

### Environment (if bug)

* Octotree version: 7.5.3
* Browser & version: Opera Version 95.0.4635.46
* OS & version: Windows 10 almost up to date
* Screenshot, Can't really screenshot a missing octotree
* Console error log below this line
No error log when filtering for octo or tree

**Comment by danhgit** [comment]
Hi @Speiger, is this GitHub Enterprise or just github.com? If GHE, please email us at support@octotree.io so that we can request more information about your Enterprise deployment to help our troubleshooting.

**Comment by Speiger** [comment]
@danhgit just github.com
I managed to fix it by installing the Chromium version instead of the Opera version.

So the opera version seems to be bugged out. 

The Opera Version is: Version 7.5.3
While the Chromium version is: 7.8.1

**Comment by danhgit** [comment]
Thanks for the update @Speiger. The new version is already available in Opera, so if you want to use it, it should work.
