### ISSUE TITLE
Feature request: green checkmarks on folders in PR mode

### ISSUE THREAD

**Issue by lali1-betsson** [ovity/octotree#1152]
If all the files in a folder is marked as viewed, (thus the green checkmark shows up before those filenames on the octotree), the parent folder of those files should be marked by a green checkmark, too.
This would save a lot of time, when reviewing large PRs.
In current version I have to go through the whole folder structure and manually open/close them a lot to be able to check the review status of bigger chunks of code files, what is quite a tedious task.

Since the green checkmark feature is already implemented on the individual files, I assume this would be fairly simple to implement, and would bring a significant value in usability.

(I've used "Better Pull Requests for Github", what have this very useful feature, but it seems to be discontinued.)

**Comment by danhgit** [comment]
Good idea... We'll think about this. Should be simple change, but need to think about the UI because currently no space for the check in folder. Suggestion is welcome.

**Comment by danhgit** [comment]
Implemented in v7.9. Thanks for the suggestion!
