### ISSUE TITLE
[Bug] File tree overlapping with GitHub FeaturePreview 'Global navigation update' side bar

### ISSUE THREAD

**Issue by ApexModder** [ovity/octotree#1154]
### Description
Having the GitHub FeaturePreview `Global navigation update` enabled allows opening a sidebar menu when clicking the GitHub logo (top left).

When this side bar is open, the Octotree side bar overlaps GitHubs side bar.

### Environment (if bug)

- **Octotree version**: _v7.8.3_
- **Browser & version**: _Firefox 111.0.1 (64 bit)_
- **OS & version**: _Windows 11 (22H2 Build 22621.1555)_

![preview-of-bug](https://i.imgur.com/MTDg23B.gif)

**Comment by danhgit** [comment]
Thanks for reporting this @ApexModder. How about we adjust to put Octotree sidebar behind the GitHub panel, would that work? If you have another preference, please let us know.

**Comment by ApexModder** [comment]
Oh uhh, I was thinking maybe the GitHub panel could open up to the right of the Octotree panel,
but that could take up a lot of horizontal screen space now that I think of it.

Overlaying GitHub's ontop of Octotree's would be fine I guess, rather than what it is now, Octotree on top of GitHub's, it's only a temp panel after all.
[I actually didn't know this panel existed in the feature preview until I shrunk down Octrotree's panel.]

**Comment by danhgit** [comment]
@ApexModder please check out version 7.9 for the fix. Thank you.
