### ISSUE TITLE
[CHORE] Document Required GitHub Personal Access Token Scopes

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1158]
### Description
When creating a new GitHub Personal Access Token, I struggled to know and figure out what the bare minimum personal access token scopes I needed to set read-only permissions to.

I believe the Octotree [Guide](https://www.octotree.io/features#authentication) page should 👉  **list the scopes that is required to be to set to read-only** 👈 , before generating a unique token, to then re-use within the Settings panel of the Octotree browser extension to successfully access GitHub repository contents.

This would resolve the problem for myself (and others) in generating tokens without the correct scope settings, and having to go-back-and-forth between GitHub token generation until the **correct** token is generated and working with Octotree browser extension.

Also, the scope should cover both GitHub Personal Access Token types:
- Fine-grained tokens (beta)
- Tokens (classic)

![GitHub Personal Access Tokens page, highlighting the two GitHub Personal Access Token types](https://github.com/ovity/octotree/assets/7581546/144b7a56-8586-4968-bee4-04c129ec5284)

> **Note** I managed to successfully generate a new GitHub personal access token using the **Fine-grained tokens (beta)** type on first try, luckily selecting the right scope options this time, which doesn't include the option to never expire for security reasons. <br/><br/>And so given that, I know I will have to repeat the token generation process again in future, and hope to remember the correct scopes to set on first attempt again, unless it is documented, which would make it efficient easier for me for next time 😅

### Environment

* Octotree version: `7.9.2`
* Browser & version: `Chrome` `114.0.5735.133`
* OS & version: `Mac OS Ventura 13.4 (22F66)`
* Console error log below this line: `N/A`
* Paid subscriber: `Yes`

**Comment by danhgit** [comment]
@Sayvai thanks for your idea and sorry for taking long to respond. I've updated the [guide](https://www.octotree.io/features) with more information about creating tokens. If you have any suggestion to improve the guide, please let me know.

**Comment by Sayvai** [comment]
Thanks @danhgit 🙌 

For the benefit of others who may come across this issue page, then i copy and paste the current instructions excerpt from the [guide](https://www.octotree.io/features#authentication) at the time of this comment as an additional reference, should those instructions ever be moved: 👇

> 2. Manually input GitHub Personal Access Token
> You can create either a fine-grained token or classic token (see more below), then paste it into the token textbox in the extension's Settings screen. If you login via GitHub OAuth and also provide personal access token, the latter is used. If you have [multiple GitHub accounts](https://www.octotree.io/features#multi-github-accounts) with access to different private repositories, Octotree supports multiple GitHub accounts. [Learn more about Personal Access Tokens](https://help.github.com/articles/creating-an-access-token-for-command-line-use).
>
>       a. Fine-grained Tokens
>
>       Click [here](https://github.com/settings/personal-access-tokens/new) to generate a fine-grained token
Enter token name, expiration and add these permissions:
All repositories OR choose specific repositories
Repository Permissions > Contents: read-only
Repository Permissions > Metadata: read-only
Repository Permissions > Pull Requests: read-only
Note: to access organization repositories, the organization admin must enable access via tokens. See [this guide](https://github.com/organizations/kmslabs/settings/personal-access-tokens-onboarding).
>
>       b. Classic Tokens
>
>       Click [here](https://github.com/settings/tokens/new) to generate a classic token
Enter expiration and pick 1 of these permissions:
repo: if you want Octotree to work for private repositories
public_repo: if you want Octotree to work for public repositories
