### ISSUE TITLE
Cancel subscription 

### ISSUE THREAD

**Issue by uditabose** [ovity/octotree#1160]
### Description
Cancel subscription for udita.bose@mongodb.com

### Environment (if bug)

* Octotree version:
* Browser & version: 
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
I've just cancelled your subscription.

**Comment by donluf** [comment]
Sorry I had too much trust in myself and couldn't at all figure out what to do I thought it was translation (sorry girls and guys I don't hope I have taken a spot, where others would have been) I tryed to help but got in to something I didn't understood anything of sorry and have a good day
