### ISSUE TITLE
Repository header pushed too far to the right when the sidebar is pinned

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1162]
### Description
It happens again (see #1026 and #1150).

https://github.com/ovity/octotree/assets/424602/9892eec4-de80-4d68-80e3-7cbedf4d5963

### Environment

* Octotree version: 7.9.3
* Browser & version: 115.0.2 (64-Bit)
* OS & version: Windows 10 Pro 22H2

**Comment by danhgit** [comment]
Thanks for reporting, @jdreesen. We've fixed it in 7.9.4. Should be available in the stores soon.

**Comment by jdreesen** [comment]
Thx for the fix. Sadly, it's not yet available for Firefox.

**Comment by danhgit** [comment]
Sorry, the release is getting a review hold up at Mozilla.

**Comment by jdreesen** [comment]
It works again, thx!
