### ISSUE TITLE
I see two file trees. one of github and one of octotree

### ISSUE THREAD

**Issue by UriZafrir** [ovity/octotree#1163]
I think you can close this because I found there is a button on the left to "files" that allows to close it. Didn't find anything on this topic though.

### Description
newbie question (didn't find any issues on this):

when using octotree I see two file trees. one of github and one of octotree.
how can i resolve this and see only the octotree one?

![image](https://github.com/ovity/octotree/assets/35652384/4148144c-61d9-49f9-9100-f10e099461ec)

### Environment (if bug)

* Octotree version: v7.9.4
* Browser & version: brave 1.57.62
* OS & version: Mac M1 13.4.1
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by danhgit** [comment]
Hi, if you clicked the icon before the "Files" label, it will hide the GitHub tree and won't show again.
<img width="66" alt="image" src="https://github.com/ovity/octotree/assets/38257704/e5cbacf4-1c92-44fd-a456-35cee7164f6c">
