### ISSUE TITLE
[Bug] File tree displaying as "deleted branch" or "no access" when branch is not deleted and has access

### ISSUE THREAD

**Issue by ApexModder** [ovity/octotree#1164]
### Description
When navigating to any branch other than the default branch, octotree reports that the branch is either deleted or i do not have access to the given branch. This is an error as i am clearly seeing the branch on github itself.

This also occasionly happens upon first load to the default branch, but reloading the webpage fixes here, reloading does not fix on other branches.

### Environment (if bug)

* Octotree version: 7.9.5
* Browser & version: FireFox 118.0.1 (64 bit)
* OS & version: Windows 11 (22H2 - build 22621.2361)

<details>

<summary>screenshots</summary>

### Octotree repoting as deleted/no access, but able to view the branch just fine on github
![image](https://github.com/ovity/octotree/assets/29412632/d0b4f0b2-437d-4297-9749-0787093bd60d)

</details>

**Comment by danhgit** [comment]
This is weird. Have you seen this happen with multiple repos or only a particular repository?

**Comment by ApexModder** [comment]
Ive had this happen to quite a few repos, not tied to any one particular user/org.

**Comment by prplecake** [comment]
I'm seeing this a lot, too. Across multiple repos and orgs. Octotree has access to all orgs.

**Comment by danhgit** [comment]
Can you remove and re-grant access of the orgs to Octotree again: [org access page](https://github.com/settings/connections/applications/746ccaaa555c27cb1f7a).
 
Also if any of the repos having problem are public, would appreciate if you could send the links to me so I could reproduce. FWIW, I tried https://github.com/Jozufozu/Flywheel that @ApexModder reported, but it displayed normally for me. 

<img width="531" alt="image" src="https://github.com/ovity/octotree/assets/38257704/5b46faa3-df60-4c4b-b3e8-f13ee853d29b">

Any help to reproduce is appreciated!

**Comment by danhgit** [comment]
@ApexModder @prplecake we've changed the approach to branch selection in 7.11.0. Can you check if this issue is fixed.

**Comment by ApexModder** [comment]
![firefox_OpTerMsM2g](https://github.com/ovity/octotree/assets/29412632/291cd0b8-bb6a-4e3b-8ecb-540a6cfed74a)

as you can see the error is still present on v7.11.0, but its more manageable as rather than branches always reporting as no access, if you simply refresh the page, the file tree will then load fine.

upon initially loading a repo, the file tree loads fine
switch to any branch, file tree fails to load
refresh the webpage, file tree will then load fine for that branch

_the above gif, also showcases that the error happens not only on other peoples repos but also my own repos, which i have full access to._

**Comment by prplecake** [comment]
Can confirm the new behavior reported by @ApexModder.

**Comment by danhgit** [comment]
Thank you @ApexModder for the super helpful video and @prplecake for your confirmation. We've fixed it in 7.11.1, please update and try again. Appreciate your patience.
