### ISSUE TITLE
File explore panel is overlapping content in View full mode

### ISSUE THREAD

**Issue by neo-cheung** [ovity/octotree#1165]
### Description

In PR code "View full" function, the side panel is overlapping the content 

### Environment (if bug)

* Octotree version: 7.10.0
* Browser & version: Brave Version 1.60.114 Chromium: 119.0.6045.124 （Official Build） （arm64） 
* OS & version: Mac 14.1.1
* Screenshot, if any (drag an image here)
expected behavior (non View full mode)
![20231114-173907](https://github.com/ovity/octotree/assets/28858412/2a3fa9f6-3dd8-4f02-9709-1c78d4384afd)
View full current behavior
![20231114-174020](https://github.com/ovity/octotree/assets/28858412/e6b05f5d-5ffd-4b0d-9a1d-f198cc8eb04f)

**Comment by danhgit** [comment]
Thanks for reporting. We'll look into this.

**Comment by danhgit** [comment]
@neo-cheung we fixed this in 7.11.0, can you try again?

**Comment by neo-cheung** [comment]
> @neo-cheung we fixed this in 7.11.0, can you try again?

Confirmed, the problem has been resolved
