### ISSUE TITLE
Compatibility issues with v7.11.0 and Edge browser

### ISSUE THREAD

**Issue by LaoYang1994** [ovity/octotree#1167]
### Description
It seems that v7.11.0 (the latest version in the Edge App Store) experiences some lag when used in Microsoft Edge, but v7.11.1 does not have this issue.

### Environment
Ubuntu18.04

* Octotree version: v7.11.0
* Browser & version: Edge Version 120.0.2210.91 (Official build) (64-bit)
* OS & version: Ubuntu18.04

**Comment by danhgit** [comment]
Thanks for reporting, @LaoYang1994. We've submitted v7.11.1 to Edge. It should be available in a few days, please check to see if the issue persists.

**Comment by LaoYang1994** [comment]
@danhgit The latest version (v7.11.2) no longer has this issue. Thank you!
