### ISSUE TITLE
View full not working first time. Only after refresh

### ISSUE THREAD

**Issue by alan994** [ovity/octotree#1172]
### Description
When I open a code review tab on some PR I'm missing `View full` action on the right side of each file. 

<img width="1327" alt="image" src="https://github.com/ovity/octotree/assets/8849512/99993fea-336b-48d4-9acb-75dcac82db4f">

**After refresh it's working ok**

<img width="1337" alt="image" src="https://github.com/ovity/octotree/assets/8849512/d00786c5-d024-4f4f-a492-b8783404fe57">

### Environment (if bug)

* Octotree version: 7.11.2
* Browser & version: Arc 1.34.0
* OS & version: Mac OS 14.2.1
* Screenshot, if any (drag an image here): Added above
* Console error log below this line: None

**Comment by danhgit** [comment]
Fixed in 7.11.3. Please look out that version, should be available in a few days. Thanks for reporting!

**Comment by danhgit** [comment]
Closed as fixed.
