### ISSUE TITLE
Octotree looks broken

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#1173]
### Description
GitHub has apparently made a bigger change. Octotree looks broken since a few minutes :(

### Environment (if bug)

* Octotree version: 7.11.3
* Browser & version: Firefox 123.0.1 (64-Bit)
* OS & version: Ubuntu 20.04.6 LTS

![grafik](https://github.com/ovity/octotree/assets/424602/cf9d87ce-37e4-4382-aeca-60336f2e4bd8)

![grafik](https://github.com/ovity/octotree/assets/424602/4a15a04c-611b-4878-ae1e-24d8cdfbc364)

**Comment by Stelzi79** [comment]
Yes, indeed there happened an update a few minutes/hour ago which basically made Octotree in GitHub dark mode very hard to read.

**Comment by danhgit** [comment]
Thank you for reporting! We've released a fix in 7.12.0 moments ago. It should be available shortly across the stores. Please report back if there's still any problem.

**Comment by jdreesen** [comment]
I already got it. It looks fine again. Thx for the **very** quick fix! :heart:

**Comment by Stelzi79** [comment]
Yes it works now and is readable.

**Comment by Sayvai** [comment]
@danhgit - Thanks for the `7.12.0` which now fixes the tree view dark mode styles 🙂 

However, I noticed the `pull requests list` and `branches list` views styles are also broken, where it seems like the overlay backgrounds are transparent, revealing the content underneath, rendering the overlay content inaccessible / not readable.

See attached image below:

### Pull Requests list

![Octotree - Pull Requests List styles broken](https://github.com/ovity/octotree/assets/7581546/72cd59e6-4fd9-42fe-a0bd-2caa2b5f9838)

### Branches list
![Octotree - styles broken on branches list view](https://github.com/ovity/octotree/assets/7581546/f418d733-5c6a-48b1-af9c-30c8a4de4812)


Can this also be fixed too when you get the chance? 🙏

**Comment by mark2685** [comment]
> @danhgit - Thanks for the `7.12.0` which now fixes the tree view dark mode styles 🙂
> 
> However, I noticed the `pull requests list` and `branches list` views styles are also broken, where it seems like the overlay backgrounds are transparent, revealing the content underneath, rendering the overlay content inaccessible / not readable.
> 
> See attached image below:
> 
> ### Pull Requests list
> ![Octotree - Pull Requests List styles broken](https://private-user-images.githubusercontent.com/7581546/314224299-72cd59e6-4fd9-42fe-a0bd-2caa2b5f9838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTQ4MDUsIm5iZiI6MTcxMDg5NDUwNSwicGF0aCI6Ii83NTgxNTQ2LzMxNDIyNDI5OS03MmNkNTllNi00ZmQ5LTQyZmUtYTBiZC0yY2FhMmI1Zjk4MzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDAyODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgwY2Q5YmRkYTc3ZTM4NjM2NjM0YjQ0ZTNkNmZhYmRkMDUyZDFjMGIwMjM3ZmM3MTM1ZTlhZmE5ZjA5MTM2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y63SGjS5wr1JexF3N2eo7A40HFKKPFBGppmcY_kYuFA)
> 
> ### Branches list
> ![Octotree - styles broken on branches list view](https://private-user-images.githubusercontent.com/7581546/314224328-f418d733-5c6a-48b1-af9c-30c8a4de4812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTQ4MDUsIm5iZiI6MTcxMDg5NDUwNSwicGF0aCI6Ii83NTgxNTQ2LzMxNDIyNDMyOC1mNDE4ZDczMy01YzZhLTQ4YjEtYWY5Yy0zMGM4YTRkZTQ4MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDAyODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjlmMmRmNmJmOGVkM2Q1MjY2NzVhYWZhODQ1YWYzODc5N2MyOGQ2OTVkYWYzZTVlNzFiNWExN2E3MmM4M2EwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FxIe-1sDM8-T995EnutD5lNgtZTcg54D8ED4RWzuJHg)
> 
> Can this also be fixed too when you get the chance? 🙏

Just updated to `7.12.0` and it all still looks pretty broken across tree views, pull request lists, and branch lists.

**Comment by danhgit** [comment]
@Sayvai @mark2685 can you share the OS & browser you use? Or, maybe GitHub is rolling out the changes in batches to different users and that explains we see different things, in which case, we hope the dust will settle soon so we could code a more permanent fix.

**Comment by mark2685** [comment]
@danhgit - Sure!
MacOS: Sonoma 14.4
Google Chrome: Version 123.0.6312.59

![CleanShot 2024-03-20 at 11 25 38](https://github.com/ovity/octotree/assets/280870/348f9566-248d-4497-a66f-c1f308d3e024)

**Comment by jdreesen** [comment]
It's also broken for me. See versions in start post.

**Comment by Sayvai** [comment]
> @Sayvai @mark2685 can you share the OS & browser you use? Or, maybe GitHub is rolling out the changes in batches to different users and that explains we see different things, in which case, we hope the dust will settle soon so we could code a more permanent fix.

Hi @danhgit - sorry for the delay! Been super busy with work.

So the PRs and Branches list views style bug is still currently happening in following Chrome and MacOS versions on the two separate MacOS machines, while I have the Octotree Chrome extension version at `7.12.0` installed:

- Chrome `122.0.6281.129` - MacOS `Sonoma 14.3.1`
- Chrome `123.0.6312.59` - MacOS `Sonoma 14.4`

**Comment by danhgit** [comment]
Thanks all for providing details and screenshots. We figured out the problems and fixed all that were reported. Please look out for v7.12.1 for the fixes and report back if there's still any issue.

**Comment by Sayvai** [comment]
> Thanks all for providing details and screenshots. We figured out the problems and fixed (i.e. Pull Requests and Branches list) all that were reported. Please look out for v7.12.1 for the fixes and report back if there's still any issue.

Hi @danhgit - I've updated the Chrome extension to `7.12.1`, and I can confirm that this fixes the latest styling issues.

Many thanks for releasing all fixes at breakneck-speed! 🙌 🚀

**Comment by danhgit** [comment]
Really glad to hear, @Sayvai! Thanks everyone again for the timely reporting of this issue and providing details to help us resolve it.
