### ISSUE TITLE
Support for replace the tree view to the right side

### ISSUE THREAD

**Issue by totht91** [ovity/octotree#344]

**Comment by buunguyen** [comment]
What does this mean?

**Comment by totht91** [comment]
Something like this: 
![right octotree](https://cloud.githubusercontent.com/assets/8333960/20169900/47a92044-a72a-11e6-90e2-89f95cb93e7a.png)

**Comment by buunguyen** [comment]
This, together with some advanced features, is implemented in Octotree Pro. Please consider paying for the subscription to access this feature and support the contributors. Learn more on our website: https://www.octotree.io/
