### ISSUE TITLE
Access Token - Multiple Github Accounts with Private Repositories

### ISSUE THREAD

**Issue by dominiquecharlebois** [ovity/octotree#347]
### Description
Disclaimer: I don't know if this is a bug or a fault on github or the extension.
 
Problem: I have two github accounts. Both accounts have private repos and both accounts need access token for the extension to work properly. 

<img width="232" alt="Problem" src="https://cloud.githubusercontent.com/assets/19155476/20366435/f69aac1a-abff-11e6-8653-94aca8ae9ef5.png">

What I expect: For it to remember my access tokens for each account and not for the last access token used. 

<img width="232" alt="Expectation" src="https://cloud.githubusercontent.com/assets/19155476/20366458/1243440e-ac00-11e6-95f2-276848f1a543.png">

### Environment (if bug)

* Octotree version: Latest Chrome Extension Version
* Browser & version: Latest Chrome Version
* OS & version: MacBookPro 13inch Retina - 2015
* Screenshot, if any (drag an image here)

**Comment by ahonymous** [comment]
+1

**Comment by nicolasmiari-unext** [comment]
+1

**Comment by tokiwinter** [comment]
👍

**Comment by timofonic** [comment]
@buunguyen Any news about this?

**Comment by zanedev** [comment]
would be cool..

**Comment by Elaniobro** [comment]
To add to the scope, I would also expect this to work with private `authtoken` and public repos.

**Comment by LowryTang** [comment]
+1 
I have accounts on github and github enterprise. I like to have this feature so that it can works on both github

**Comment by cloud-hpcnt** [comment]
+1 for this

I also have accounts on GitHub & GitHub Enterprise.
It would be great if I can register my access key per access domain:
- `https://github.com` =>  `access-token-1`
- `https://my-github-enterprise-domain.com` => `access-token-2`

**Comment by cloud-hpcnt** [comment]
@buunguyen Thanks!

**Comment by buunguyen** [comment]
Support for multiple GitHub accounts is implemented in Octotree Pro, which comes with other advanced features. Please consider purchasing the subscription of Octotree Pro if you need any of these features. See more here: https://www.octotree.io/
