### ISSUE TITLE
Searching option

### ISSUE THREAD

**Issue by desislavsd** [ovity/octotree#410]
Your extension is great! Life is much more easier and github is better!

I would love to see one more feature though. Can you add search field in the sidebar's header so that the file tree may be filtered  for quicker finding of files.  

Thanks in advance!

**Comment by maliming** [comment]
@desislavsd Look at this, buddy #414

**Comment by desislavsd** [comment]
@maliming Looks great! Hope it will be merged!

**Comment by buunguyen** [comment]
File search, together with some advanced features, is implemented in Octotree Pro. Please consider paying for the subscription to access this feature and support the contributors. Learn more on our website: https://www.octotree.io/

**Comment by jayarjo** [comment]
@buunguyen Any other way to pay for it? Paypal at least maybe?

**Comment by buunguyen** [comment]
@jayarjo sorry, credit card only for now.

**Comment by jayarjo** [comment]
You potentially miss many clients. Consider adding Stripe for example, it is easy to embed.

**Comment by buunguyen** [comment]
We're using Stripe. It doesn't support Paypal.
