### ISSUE TITLE
Inquiry: Why custom keyboard shortcut assignment was removed

### ISSUE THREAD

**Issue by AESM** [ovity/octotree#427]
### Description

In the past, I could go to _chrome://extensions/ > Keyboard shortcuts_ & define my own custom keyboard shortcut.  Octotree no longer appears on that list.  Was there a reason for this change?

### Environment

* Octotree version: 2.2.0
* Browser & version: Google Chrome 60.0.3112.90 & Google Chrome Canary 62.0.3185.0
* OS & version: macOS Sierra 10.12.6

**Comment by buunguyen** [comment]
Interesting, I didn't even know that exist! If there was code for it, it wasn't there knowingly :) and can't think of any change that could possibly cause this change in behavior. Maybe Chrome itself changes. Anyway, if anyone knows how to allow customizing Octotree via that page shortcut, I'd love your insight or a PR.

**Comment by Mottie** [comment]
It sounds like the `manifest.json` was changed. Add a [`commands` option](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands) to include keyboard shortcuts.

**Comment by buunguyen** [comment]
Sorry, it's been a while. Question: what do you use this shortcut for? Why not use the shortcut in the Octotree settings view?

**Comment by AESM** [comment]
@buunguyen - The current Octotree settings work, which is why I never pushed hard for the change.  But my answer would be keeping & providing consistency to the user.

First, the method I mentioned above used to work & there was no default shortcut.  Both of these changed at some point, which meant users that created their own shortcut had to learn a new command at the very least.

Second, the _chrome://extensions/shortcuts_ page exists to manage extension shortcuts.  Default commands provided by developers appear here & users can use this UI to change them or assign one (sometimes more) if none exists.  It's inconvenient (if not inconsistent) for most of the extension primary action commands to be in one location, but not all.

Again, not the end of the world, but that was my logic.  Hope that makes sense.
: )

**Comment by buunguyen** [comment]
Thanks. You meant you were able to use chrome://extensions/shortcuts to configure the toggle behavior of Octotree sidebar? That is quite interesting because we never wrote code to handle that command :). I suppose Chrome works in an interesting way that we don't understand yet.
