### ISSUE TITLE
Hope to add local cache & user other's repository list.

### ISSUE THREAD

**Issue by wilon** [ovity/octotree#442]
### Add local cache

In my country, Visiting github is slow. Hope to add cache which repository I visited. Base on the commit api to control update cache. Such as https://api.github.com/repos/buunguyen/octotree/commits.

### Add user other's repository list on the tree top

Then it can quick jump to other repo.

-----
Thanks.

**Comment by buunguyen** [comment]
This took us a long time to build. Cache is available with pro subscription since v4.0.
