### ISSUE TITLE
Support for brave extension

### ISSUE THREAD

**Issue by altosaar** [ovity/octotree#456]
Any plans to support brave?

https://github.com/brave/browser-laptop

**Comment by buunguyen** [comment]
Looks like Brave hasn't fully implemented support for web extensions yet: https://github.com/brave/browser-laptop/issues/253. When it has, should be easy to create a build for it.

**Comment by kaltepeter** [comment]
It appears brave/browser-laptop#253 may be integrated at this point. Any chance of integrating with brave?

**Comment by grantwinney** [comment]
I use Brave and the extension seems to be working perfectly fine. This issue might be resolved... or I might be misunderstanding the original problem. 🤔

**Comment by buunguyen** [comment]
Thanks for the note @grantwinney. As this issue is old, gonna close now. If people have specific problem with Brave, please open new issue. Thanks.
