### ISSUE TITLE
[Proposal] Gitea support

### ISSUE THREAD

**Issue by lunny** [ovity/octotree#467]
Gitea is an light weight self-host git service. See https://github.com/go-gitea/gitea. Since Gitea has similar API with github, add support for gitea is easier. Currently, gitea's route is `/api/v1` but not `/api/v3`.

**Comment by lunny** [comment]
And the test site is https://try.gitea.io

**Comment by buunguyen** [comment]
It's not hard to support a product. What's I haven't figured out how to deal with is maintaining the code as these products keep changing their layouts or DOM. The lesson from supporting GitHub and BitBucket in the past is there weren't enough interest in the community to maintain the support while I couldn't afford the time to continuously improve Octotree and make sure it works with all different products. Unless the situation changes, it's unlikely Gitea will be supported.

**Comment by laoshaw** [comment]
is it possible to write a basic workflow or a few steps so other people can contribute relatively easily to support things like gitea(e.g. steps to add support for other repo sites such as gitea)? I'm interested to get gitea support added as well. Thanks.

**Comment by zuosc** [comment]
It is a pity!
