### ISSUE TITLE
Support "expand all" for the file tree

### ISSUE THREAD

**Issue by lev112** [ovity/octotree#470]
would be nice to have an option to expand all of the directories in the tree view.
maybe limit the number of files

it is very convenient when reading a PR that doesn't contain a lot of files.

**Comment by buunguyen** [comment]
Maybe requesting jstree itself? https://github.com/vakata/jstree

**Comment by keimlink** [comment]
jstree has an [`open_all()`](https://github.com/vakata/jstree/blob/master/src/jstree.js#L2814) function. Is this the right way to go?

**Comment by iwllyu** [comment]
would love an expand all function

**Comment by michalpaukert** [comment]
Why is this issue closed?

**Comment by stevennoto** [comment]
Hi @buunguyen, I use this extension all the time, and in the spirit of [Hacktoberfest](https://hacktoberfest.digitalocean.com), I was thinking of taking on this issue (add a way to expand whole tree if not lazily loaded, including in PR view). I use Octotree to help navigate PR's all the time and this would be super useful for me!

Before I do though, I wanted to ask if you were interested in help here, and if so, if you had preferences for how to implement it. For example, adding "expand all"/"collapse all" buttons, icons, hotkeys, etc.

Let me know what you think, and thanks again for this amazing Chrome extension!

**Comment by buunguyen** [comment]
@stevennoto I've just added the Help Wanted label to those I'd like to be fixed/supported in Octotree. Feel free to work on any of them. Let me know if you have any question. Thanks again for the help.

**Comment by emetcalfputnam** [comment]
This would be an extremely useful feature, is it possible to please re-open?

**Comment by stevennoto** [comment]
@emetcalfputnam I was going to look at this one, after I tackle some smaller fixes and get familiar with more of the code. I also think it would be super useful for certain types of PR's. :)

**Comment by dsbonev** [comment]
Reopen this issue, it is not fixed. Furthermore, let's expand the whole tree by default on PR pages just like the `github_pr_tree` project does it.

### Octotree PR tree
![image](https://user-images.githubusercontent.com/1313633/47270866-a376d300-d57a-11e8-9c62-a84ec4731c5e.png)

### Github PR tree (https://github.com/berzniz/github_pr_tree)
![image](https://user-images.githubusercontent.com/1313633/47270886-e042ca00-d57a-11e8-9163-8209d4d26a85.png)

**Comment by buunguyen** [comment]
Expand all files by default maybe a good first step. Not sure how it plays out for large PRs though. So an option or trigger button would appear like the best thing. If trigger button, the UI must be clean and uncluttered. Option might be easier, although I'm not sure what is better, depending on the design of the trigger button.

> Reopen this issue, it is not fixed.

On the internet, it's hard to get the tone of the people behind the keyboard. So please try to comment in a way that can't be possibly misconstrued as being aggressive or dictating. It would be a shame if a good idea or suggestion is buried, ignored or even blocked because it is buried under a tone-deaf comment that isn't appreciated by the maintainers.

**Comment by pmalekn** [comment]
👍 for this feature. My suggestion would be (amongst listed in here) to add an option to:

```
Expand all in:
* [ ] PRs
* [ ] project views
* [ ] others
* [ ] ...
```

so that user can choose when to expand the tree. And possibly add a hotkey combination (the same way as for showing the dock) to expand or collapse the tree.

**Comment by buunguyen** [comment]
Since the last few releases, PRs have been expanded by default, without the need to add stuff to the UI. I suppose this issue can be closed.
