### ISSUE TITLE
Slow navigation

### ISSUE THREAD

**Issue by shrpne** [ovity/octotree#489]
With octotree enabled navigating between pages takes much more time. I'm not sure what's the reason for this. 
If this is because of pjax, maybe pjax can be disabled?
If this is because of downloading repo's files tree, maybe downloading can be detached to a separated worker? So navigating speed will not be affected.

Also would be nice if octotree will turn off when sidebar is collapsed, so there will be no unnecessary loading.

### Environment
* Octotree: 2.4.3
* Browser: Firefox 58.0.1
* OS: macOS 10.13.2

**Comment by buunguyen** [comment]
Caching will help. Track in this issue: https://github.com/ovity/octotree/issues/442.
