### ISSUE TITLE
Add support for download entire directory

### ISSUE THREAD

**Issue by vsxen** [ovity/octotree#498]
this repo may be helpful (https://github.com/MinhasKamal/DownGit).
Thanks for your work .

**Comment by ifyour** [comment]
Well, Will this feature be considered? @buunguyen

**Comment by buunguyen** [comment]
AFAIK, automatically download is no longer possible. Also, it feels like it's a bit different from Octotree's primary goal of making code browsing & reviewing on GH easier. This feels like it should be a separate extension.
