### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by HenkeDaniil** [ovity/octotree#503]
Please add dark mode!

**Comment by ttuygun** [comment]
Seen without dark mode using Dark Reader extension like this.
<img width="1625" alt="screen shot 2018-09-23 at 00 42 40" src="https://user-images.githubusercontent.com/10091984/45921982-aa51ed80-bec9-11e8-8032-ec551556aea7.png">

**Comment by rxliuli** [comment]
Yes, I used the plugin [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh). I would very much like to add dark mode, although I can customize the style via the [stylus](https://add0n.com/stylus.html) plugin, but I still want to set the dark mode directly.

**Comment by charygao** [comment]
Please add dark mode with optional in settings page。thank you all！

**Comment by rxliuli** [comment]
> Please add dark mode with optional in settings page。thank you all！or i will do it by my self samplely😂
> ![default](https://user-images.githubusercontent.com/6499936/48334759-b15dd680-e696-11e8-871e-f1e05693af0d.png)

I also use the navigation that implements black, using [Stylish](http://userstyles.org/styles/37035), wu'be my feelings are not bad. -(๑☆‿ ☆#)ᕗ

![image](https://user-images.githubusercontent.com/24560368/49331479-894bfe00-f5d8-11e8-9bf2-92f0f6eed3d8.png)

**Comment by ewgenius** [comment]
I'm not sure about support for some external dark themes (because they might be different), but I think it would be nice to have option for GitHub dark header, as far as it is official and default.

I have some WIP changes, I can create a PR for that:

![kapture 2019-01-11 at 0 51 10](https://user-images.githubusercontent.com/827338/50999468-4405df00-153b-11e9-967b-6365d1395223.gif)

**Comment by buunguyen** [comment]
Please consider [Octotree Pro](https://www.octotree.io/) if you want built-in dark mode support. Octotree Pro requires a paid subscription and comes with premium features for advanced users. This would help me maintain and improve Octotree.

**Comment by rxliuli** [comment]
. . . So you use the dark mode as a charging function? ? ? This simple feature doesn't even require more than 20 lines of css. . .

**Comment by buunguyen** [comment]
You think! But yes, dark mode and some other features are only available in Octotree Pro.

**Comment by buunguyen** [comment]
And the teasers for those who are interested...

<img width="1601" alt="1" src="https://user-images.githubusercontent.com/406631/55044200-9d3bc580-4ff6-11e9-82fb-fbcffa1107ed.png">
<img width="1562" alt="2" src="https://user-images.githubusercontent.com/406631/55044201-9d3bc580-4ff6-11e9-9fc1-3231aeba6c60.png">

**Comment by ForsakenHarmony** [comment]
How is dark mode "niche/non-core", more people would choose it, it's core and not niche at all

**Comment by buunguyen** [comment]
Well, this ticket has been open for more than a year and nobody steps up to provide a complete implementation. Besides, there are over 250k people using Octotree for many years without the feature and everyone loves it. Seems like a good justification to me.
