### ISSUE TITLE
Octotree branch doesn't match the branch of selected file

### ISSUE THREAD

**Issue by august-xu** [ovity/octotree#511]
### Description
when i choose a commit ,the files list also are master file list;but when i choose one tag,the file list are the tag`s file list; is there a possibility showing the file list of a commit

### Environment (if bug)
* Octotree version:
2.4.6
* Browser & version:
chrome 65.0.3325.181
* OS & version:
win7 64x
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/6892564/39244078-27ea9f5e-48c2-11e8-833a-d316e1f8ad25.png)

**Comment by buunguyen** [comment]
Dup https://github.com/ovity/octotree/issues/473
