### ISSUE TITLE
safari install fails from error	Sandbox: fseventsd(64) System Policy: deny(1) file-read-metadata /private/var/folders/...

### ISSUE THREAD

**Issue by bedge** [ovity/octotree#513]
### Description

Following OSX install instructions, using safari extension builder to install.

* Octotree version: b4b43e9 Buu Nguyen - (HEAD -> master, origin/master, origin/HEAD) Update PULL_REQUEST_TEMPLATE.md (2 days ago)

* Browser & version: Safari 11.1
* OS & version: 10.13.4 (17E202)

OSX console shows:

error	10:21:37.867575 -0700	kernel	Sandbox: fseventsd(64) System Policy: deny(1) file-read-metadata /private/var/folders/_c/g97yt22n4fv2dnqzs3g7dq0r0001ys/0/SafariFamily/Safari/Extensions/octotree-2.safariextension/jstree.css

Error is repeated for all files.

console errors:

![screen shot 2018-04-30 at 10 26 07 am](https://user-images.githubusercontent.com/499317/39440833-098e7218-4c61-11e8-9178-64d9bf228863.png)

extension builder config after loading extension:

![screen shot 2018-04-30 at 10 26 34 am](https://user-images.githubusercontent.com/499317/39440839-0dfd77cc-4c61-11e8-8193-377953c25106.png)

![screen shot 2018-04-30 at 10 26 48 am](https://user-images.githubusercontent.com/499317/39440842-14ac4468-4c61-11e8-9c06-fea517f75b7a.png)

**Comment by buunguyen** [comment]
I'm tracking Safari in here https://github.com/ovity/octotree/issues/539
