### ISSUE TITLE
Folder icons are not showing properly

### ISSUE THREAD

**Issue by anidotnet** [ovity/octotree#515]
### Description
The folder icons are not showing properly in chrome.

### Environment (if bug)

* Octotree version: 2.4.6
* Browser & version: Google Chrome Version 66.0.3359.170 (Official Build) (64-bit)
* OS & version: Ubuntu 18.04 LTS 64-bit
* Screenshot

![image](https://user-images.githubusercontent.com/696662/39956413-9ffcfeae-55fd-11e8-98d5-d47361ac9039.png)

**Comment by buunguyen** [comment]
I just tried on Chrome 67 on Ubuntu, seems to work fine. Does this still happen?

**Comment by anidotnet** [comment]
Yes it still does

![image](https://user-images.githubusercontent.com/696662/43476447-3dfd6178-9516-11e8-948d-a0d97dd5ec74.png)

Current chrome version - Version 68.0.3440.75 (Official Build) (64-bit)
OS - Ubuntu 18.04.1 LTS

**Comment by anidotnet** [comment]
I seems to be resolved with Ubuntu 18.10 with chrome 70.0.3538.77

**Comment by buunguyen** [comment]
Great, thanks for reporting back!
