### ISSUE TITLE
Cannot retrieve contributors in firefox

### ISSUE THREAD

**Issue by izhengfan** [ovity/octotree#516]
### Description

Visiting any files from octotree causes `Cannot retrieve contributors at this time`.  Refreshing the webpage can fix it. Visiting files directly from Github webpages works fine.

### Environment (if bug)

* Octotree version: 2.4.6
* Browser & version: Firefox 60.0 (64 bit)
* OS & version: Ubuntu 16.04.4
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/8697363/40106871-7b7d282c-5929-11e8-954c-7b7a46030502.png)

**Comment by mahngiel** [comment]
Happens on mac 10.13.6, FF 61.0.2 (x64), OctoTree 2.4.6

**Comment by mdonoughe** [comment]
I'm not seeing this on Windows 10 Firefox 63 OctoTree 2.5.0.

**Comment by izhengfan** [comment]
Yes, this problem seems fixed now. On FireFox 63.0, Ubuntu 16.04.

**Comment by buunguyen** [comment]
Thanks for reporting back.
