### ISSUE TITLE
Extension style not being loaded on Safari

### ISSUE THREAD

**Issue by Rodrigora** [ovity/octotree#517]
### Description
Just installed the extension and it's not working on Safari. Seems that the CSS wasn't loaded.

### Environment (if bug)

* Octotree version: master
* Browser & version:  Safari 11.1
* OS & version: macOS High Sierra 10.13.4
* Screenshot:

<img width="773" alt="screen shot 2018-05-22 at 16 04 44" src="https://user-images.githubusercontent.com/36473613/40371136-c1296aa2-5dd9-11e8-9c21-56d1eaeff4fe.png">

**Comment by pjay** [comment]
Same issue here. If you run `gulp styles` before `gulp safari`, the CSS will be correctly built and included in the extension. Maybe a dependency issue in the gulpfile? As I'm not fluent with those techs, I'll let someone else fix this.

**Comment by buunguyen** [comment]
Tracking Safari support in here https://github.com/ovity/octotree/issues/539
