### ISSUE TITLE
Bug in network graphs

### ISSUE THREAD

**Issue by piranna** [ovity/octotree#520]
### Description
On a project network graphs, having octotree open, the tooltips and clikcs when putting the mouse on top of a commit are displaced, and you need to put the mouse several centimeters to the left so they get shown and clickable.

### Environment (if bug)

* Octotree version: Chrome extension
* Browser & version: Chromium Versión 66.0.3359.181 (Build oficial) Built on Ubuntu , running on Ubuntu 18.04 (64 bits)
* OS & version: Ubuntu 18.04
* Screenshot, if any (drag an image here)
![captura de pantalla -2018-06-19 10-45-45](https://user-images.githubusercontent.com/532414/41586814-f4bb4374-73ad-11e8-9f40-bf4d717b145b.png)

**Comment by buunguyen** [comment]
Dup https://github.com/ovity/octotree/issues/443
