### ISSUE TITLE
Display repo and file size

### ISSUE THREAD

**Issue by chad-it** [ovity/octotree#521]
hope can display repo size, size of each file

**Comment by buunguyen** [comment]
This extension https://github.com/harshjv/github-repo-size supports this quite effectively. I'm leaning on not re-inventing the wheel in this case.

**Comment by nmaxcom** [comment]
@buunguyen sure, it works well in the navigation container. But is there a way to show the file size in octotree? That's where it'd be useful if you are using octotree to navigate your way around a repo.
