### ISSUE TITLE
Safari no longer supports unsfae extensions in mac os mojave public beta

### ISSUE THREAD

**Issue by star114** [ovity/octotree#523]
### Description
showed the message box with unsupported safari extension and disabled.

### Environment (if bug)

* Octotree version: newest version in dist directory (dist/safari.safariextz)
* Browser & version: Safari 12.0
* OS & version: Mac os Majave Public Beta 1
* Screenshot, if any (drag an image here)
![image 2018-07-02 at 10 57 11 am](https://user-images.githubusercontent.com/5426221/42141827-ba699016-7de6-11e8-831b-895bc89bfccb.png)

**Comment by osteele** [comment]
More information here: [Apple Developer Documentation > Safari Extensions JS](https://developer.apple.com/documentation/safariextensions): “ Legacy Safari Extensions distributed outside of the Safari Extensions Gallery are not supported in Safari 12. Legacy Safari Extensions distributed in the Safari Extension Gallery are deprecated, and Safari 12 is the last release to support them. New submissions to the Safari Extensions Gallery will be accepted until the end of 2018.”

Possible workarounds / courses of action:
* George Garside has documented how to [manually install Safari extension in Safari 12](https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/). Maybe the README should be updated with these instructions, or a link to them, by the time Mojave is released?
* Submitting Octotree to the Safari Extensions Gallery will make it available for installation from the Gallery, until macOS 10.15 (presumably beta summer of 2019, release early fall 2019). Submitting Octotree to the Gallery requires a (paid) developer account.
* The only long-term (post-Mojave) solution that doesn't require a manual workaround is to include Octotree as a [Safari App Extension](https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension) extension within a macOS application.

**Comment by osteele** [comment]
The instructions from [Bypass ‘Safari no longer supports the unsafe extension’ in macOS Mojave](https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/), that I cited in the previous comment, didn't work verbatim for me. (Renaming `safari.safariextz` to `safari.zip` and double-clicking on it just makes another file `safari.zip.cpgz`. Running `unzip dist/safari.safariextz` or `unzip dict/safari.zip` prints an error "End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive…".)

Here's the modification that worked instead:

```bash
$ npm install -g gulp
$ gulp build
```

Then follow the instructions in [Bypass ‘Safari no longer supports the unsafe extension’ in macOS Mojave](https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/), starting at "Add safariextension to Extension Builder", to install and run `tmp/safari/octotree.safariextension`.

**Comment by buunguyen** [comment]
@osteele would you mind proposing the changes needed in README.md to help other folks?

**Comment by star114** [comment]
@osteele I already added safari extension to Extension Builder and run explicitly whenever I quit the safari. It is very inconvenience that I should run "explicitly".

Do you know how to skip this "run" the extension builder? I mean, can I run and enable this safari extension from extension builder automatically?

**Comment by osteele** [comment]
@star114 I'm not aware of a workaround for repeating the installation each time you start Safari. When I described the developer installation procedure in my previous comment, I hadn't yet quit and restarted Safari, and therefore wasn't aware how inconvenient it is.

@buunguyen I can update the README. Since the instructions are complicated and since the workaround doesn't turn out to be very practical (see @star114's comment above—you need to repeat the procedure each time you launch Safari), I'm not sure copying the instructions out into the README is worthwhile. Maybe instead the README should just say that the extension can't easily be installed in macOS 10.14 (Mojave) / Safari 12.0, and link to this issue for more detail?

**Comment by star114** [comment]
@osteele I agree with you. it is not a true solution. it's just a workaround with little inconvenience.

@buunguyen do you have any plans to enroll safari extensions gallery of apple app store?

**Comment by buunguyen** [comment]
@star114 sorry, no plan. Last time I checked, it was a painful process and requires paid membership. Not sure if anything's changed since then but certainly not a fan of that process.

**Comment by buunguyen** [comment]
Closed for newer thread https://github.com/ovity/octotree/issues/539

**Comment by buunguyen** [comment]
Please see announcement of official Safari release: https://github.com/ovity/octotree/issues/539#issuecomment-476486281
