### ISSUE TITLE
Unable to save access token for enterprise Github account (Opera)

### ISSUE THREAD

**Issue by cfenwick74** [ovity/octotree#524]
### Description
Installed octotree on Opera. Created a personal access token for my enterprise github account. When I tried to save it, I got an error saying that the personal access token was invalid. This happened in Chrome as well when I tried it there. This happened on both Windows 7 and Windows 10

### Environment
* Octotree version: 2.4.4
* Browser & version:
Opera 53.0.2907.99
Chrome 67.0.3396.99
* OS & version:
Windows 7 Enterprise - Version 6.1 (Build 7601: Service Pack 1) (Opera)
Windows 10 Pro - Version 1709 (Build 16299.461) (Opera and Chrome)

### Additional info
I was able to successfully save a personal access token in an earlier version of Chrome on my Windows 7 machine. (not sure what version of Chrome I was running at the time, though, sorry)

### Screenshot
![invalid personal access token](https://user-images.githubusercontent.com/8890796/42392845-4040ed0e-8122-11e8-87bc-b66caae1b187.png)

**Comment by buunguyen** [comment]
Can you open Chrome dev tool, local storage and check if octotree.access_token has the right value? Also check if you don't have extra spaces around the string.

**Comment by cfenwick74** [comment]
My apologies. It does work in Chrome. I'm unable to save it in Opera though.

**Comment by buunguyen** [comment]
Can you check octotree.access_token in local storage to see what value it has?
