### ISSUE TITLE
Browsing old commits

### ISSUE THREAD

**Issue by mustafaozhan** [ovity/octotree#525]
Hello,

First of all I am really thankful for this project I am able to easily navigate the repos nowadays. But there is one thing which I realized, Octotree is not able to navigate some commits for a project.
For example;

Let's say I have a repo name is **A** and there is 3 commit inside **initial commit** , **commit1** and **commit2**. so when I navigate **github/username/A** everything works like a charm it shows the lastest updated project files which is **commit2**.

 But the case is when I want to browse the specific commit time of a project. Let's say I want to browse the project when **initial commit** was made, at this time our url is **github.com/username/A/tree/uniqueIDforInitialCommit** but Octotree is always navigate me the lastest commit files  **github/username/A** which is **commit2** instead of **github.com/username/A/tree/uniqueIDforInitialCommit** which is **initial commit** .

I hope you will solve it as soon as possible. It would be much more useful for big projects to brows different period of projects.

Regards,

Mustafa Ozhan

**Comment by HuEric** [comment]
I also have this situation, visiting an old commit and octotree showing **master** branch, so selecting from the tree jump me back to master version of the file.

**Comment by buunguyen** [comment]
Dup https://github.com/ovity/octotree/issues/473
