### ISSUE TITLE
It crashed when I want to delete a project

### ISSUE THREAD

**Issue by FindHao** [ovity/octotree#528]
### Description

When I want to delete a project, the web page crashed.  Disable the octotree, work well.

### Environment (if bug)

* Octotree version: 2.4.6
* Browser & version: 68
* OS & version: Debian 9 X64

**Comment by FindHao** [comment]
Actually it crashed in every project page on the last version. Now I install the latest version and it seems be fixed. Thanks for your work.

**Comment by buunguyen** [comment]
Thanks for updating. Glad that's no longer an issue.
