### ISSUE TITLE
Crash on Chrome when popping up

### ISSUE THREAD

**Issue by xyprince** [ovity/octotree#531]
### Description
Crash on Chrome 68.0.3440.106 Chinese version but English works fine

### Environment

* Octotree version:2.4.6
* Browser & version:Chrome 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
* OS & version:Win10 home 1803
* Screenshot
![gif2](https://user-images.githubusercontent.com/7668939/44296940-d8587680-a2fa-11e8-8e64-4a54f710a17d.gif)

**Comment by Molunerfinn** [comment]
+1

**Comment by luxueyan** [comment]
me too

**Comment by xyprince** [comment]
Working properly in the latest Chinese version of Chrome (69.0.3497.92)。
Is there anyone else still having problems?

**Comment by buunguyen** [comment]
If there's still a problem please submit a new ticket with error log in the dev console. Thanks.
