### ISSUE TITLE
Firefox setup doesn't allow to configure GHE domain

### ISSUE THREAD

**Issue by MichalMichalak** [ovity/octotree#535]
### Description
In Chrome, when click setup, I can configure custom domain name for GHE instance. In Firefox this field doesn't exist. How do I configure it in Firefox?

### Environment (if bug)

* Octotree version: 2.4.6
* Browser & version: Firefox 61.0.2 (64-bit)
* OS & version: Mac OS High Sierra
* Screenshot, if any (drag an image here)

**Comment by Ephemera** [comment]
It's supported chrome and safari only.
https://github.com/buunguyen/octotree/blob/master/README.md#enterprise-urls

**Comment by MichalMichalak** [comment]
Thank you, I understand. Do you have any plans for FF?

PS. Chrome and Opera, yes? Docs say Opera, not Safari.

**Comment by buunguyen** [comment]
I'm not 100% sure but I think it might be possible with Firefox Quantum. Currently the firefox version of Octotree puts the permission statically in the manifest. But it might be possible to request permission for enterprise URLs dynamically like Chrome. Will need to tweak the build and/or deal with the chrome specific API (hopefully just a simple conversion from "chrome" to "browser", but I never tried). Would be great if someone can jump on this task.

**Comment by buunguyen** [comment]
Closing, track this issue here: https://github.com/ovity/octotree/issues/275
