### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by yin-shu** [ovity/octotree#538]
### Description
最近一直都提示这个连接错误，所有的项目都是
Cannot connect to website. If your network connection to this website is fine, maybe there is an outage of the API. Please try again later.

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/29432662/45683329-d5f57080-bb75-11e8-9cd9-8bd67bd20643.png)

**Comment by buunguyen** [comment]
Does this still occur? Can you open the Chrome dev console and see if there's any error log?

**Comment by yin-shu** [comment]
@buunguyen 
![image](https://user-images.githubusercontent.com/29432662/47058028-d37a4b00-d1f5-11e8-98b2-e523764b2666.png)
没有什么报错信息

**Comment by mustaqimM** [comment]
@buunguyen I get the same error with `umatix` enabled but the logger doesn't show anything other than `collector.githubapp.com` that is blocked

**Comment by hli2020** [comment]
> @buunguyen I get the same error with `umatix` enabled but the logger doesn't show anything other than `collector.githubapp.com` that is blocked

Do you resolve it? I've suffered this for a few days already.

**Comment by NARUTOne** [comment]
![image](https://user-images.githubusercontent.com/18441915/56791987-19663a80-683b-11e9-8a49-1fa08535d894.png)
![image](https://user-images.githubusercontent.com/18441915/56792023-2c790a80-683b-11e9-9b0c-b72cf1021583.png)

**Comment by gaoweichun** [comment]
I get the same error with Octotree

**Comment by romeoblog** [comment]
I get the same error on chrome.

**Comment by romeoblog** [comment]
It's normal now.

**Comment by ManiuLtd** [comment]
I get the same error on chrome.

**Comment by xihazhiwang** [comment]
I get the same error on chrome

**Comment by AziCat** [comment]
I have the same error on chorme 79.0.3945.88 x64

**Comment by lamster2018** [comment]
I get the same error on chrome 
版本 80.0.3987.122（正式版本） （64 位）

**Comment by lamster2018** [comment]
I get the same error on chrome 
版本 80.0.3987.122（正式版本） （64 位）

**Comment by jiabinbin** [comment]
I get the same error on chrome
80.0.3987.132 (正式版本) （64 位）T.T

**Comment by VVVVictorJ** [comment]
I met the same problem，but I found it's about the url reset. 
![image](https://user-images.githubusercontent.com/38826071/76386253-fc791e00-639e-11ea-9e98-8625e566c2d5.png)
Then I just think a second.  I changed my host file a few days ago because dns redirection caused by GFW. So I return back the original setting. I commented the line which pointed by the arrow. Then the plugin works.
![image](https://user-images.githubusercontent.com/38826071/76386640-ecae0980-639f-11ea-96d8-f3ebe05f6099.png)

**Comment by VVVVictorJ** [comment]
@buunguyen 
I find it isn't work ,too. I replaced the ip address and fixed it.
![image](https://user-images.githubusercontent.com/38826071/76393811-479b2d00-63af-11ea-96e0-bbe7f9b846bb.png)

**Comment by xiaobu1994** [comment]
I have the same error on chorme 80.0.3987.132

![image](https://user-images.githubusercontent.com/44577736/76827700-6b9cb980-685a-11ea-9312-3a3801e8e75d.png)

**Comment by 15050050972** [comment]
I meet the same error, I'm in china.
So I try to start a vpn, then refresh the page, then the octotree works fine...

**Comment by xiaobu1994** [comment]
> I meet the same error, I'm in china.
> So I try to start a vpn, then refresh the page, then the octotree works fine...

me too

**Comment by DoTime** [comment]
me too
how slove this problem?

**Comment by hi-mamba** [comment]
chrome f12 看下哪些域名被墙了，代理下就OK了

**Comment by ayarei** [comment]
I must turn off the proxy to use the octotree, it's really weird.

**Comment by RookieJay** [comment]
我这里的原因是hosts里面设置了api.github.com的代理 屏蔽掉就可以了
![image](https://user-images.githubusercontent.com/28537741/96953822-a5d2e580-1524-11eb-9157-961c6b2d69bc.png)
