### ISSUE TITLE
Support for Edge

### ISSUE THREAD

**Issue by hez2010** [ovity/octotree#541]
### Description
Could you add support for Microsoft Edge? Thanks!

### Environment (if bug)

* Octotree version: -
* Browser & version: Edge 42.17134.1.0
* OS & version: Windows 10 pro x64 17134.185
* Screenshot, if any (drag an image here) -
* Console error log below this line -

**Comment by buunguyen** [comment]
Duplicate https://github.com/ovity/octotree/issues/480

**Comment by buunguyen** [comment]
Edge version: https://microsoftedge.microsoft.com/addons/detail/octotree/joagmknfcgpikbadjkaikmnhpjadihjg?hl=en-US
