### ISSUE TITLE
Improvements in context of PR

### ISSUE THREAD

**Issue by basejumpa** [ovity/octotree#542]
### Description
Below the repository's name there is the branch of the context shown. That's fine on code pages.

But being in context of a pull-request (PR), octotree in version 2.4.9 shows the base branch of the PR. That does not fit to the diffs shown.

Within a PR you deal with deltas between two or more commits. 

* [ ] Feature Request-1: Feature Request: In PR context, octotree shall not display base branch but the two references of the diff in the PR. So two branches or a short commit hash.
* [ ] Feature Request-2: Octotree shall regard the commit which is selected on the PR's "Files changed" page.

### Environment (if bug)

* Octotree version: 2.4.9
* Browser & version: Chrome, Version 69.0.3497.100 (Official Build) (64-bit)
* OS & version: Windows 10
* Screenshot, if any (drag an image here)

![image](https://user-images.githubusercontent.com/8762228/46011507-5829eb80-c0c6-11e8-8227-ec7837215108.png)

![image](https://user-images.githubusercontent.com/8762228/46011512-5fe99000-c0c6-11e8-86c3-c47fb12f45c7.png)

* Console error log below this line:
-none-

**Comment by stevennoto** [comment]
Hey @basejumpa, I know this is an older issue, but for Hacktoberfest I took a look and think I have fixed the branch display. See linked PR with screenshot.

I addressed your first feature request, to show both the head and base branches. I'm not sure about the second one, to somehow show reflect which files or commits are filtered in the PR view. In these cases, Octotree still shows the full PR file tree, so I think it's appropriate for it to keep showing just the base and head branches.
