### ISSUE TITLE
Feature request: Enhance options where to show

### ISSUE THREAD

**Issue by basejumpa** [ovity/octotree#543]
Feature request: Enhance options where to show.

My usecase is to show it in the context of pull-requests only. So suggest to replace the option "Snow in non-code pages" by a field of on/off options:

```
Show in:
* ( ) Code
* ( ) Code/Commits
* ( ) Pull request
```

**Comment by danhnguyen30041975** [comment]
IMO, below options make sense

```
Show in:
* [ ] Code
* [ ] Pull Request
* [ ] Commit
* [ ] Other pages
```

Note: `[ ]` is checkbox

**Comment by buunguyen** [comment]
Change to `Show sidebar in:`

Should select all options by defaults. Also move this section to after Shortkey.

**Comment by buunguyen** [comment]
This is in 3.0.10.
