### ISSUE TITLE
Octotree's side panel shifts GitHub's header's content

### ISSUE THREAD

**Issue by flawyte** [ovity/octotree#546]
### Description

The title says it all. Here's a screenshot to help you see the problem :
![Screenshot showing header's content being shifted](https://snag.gy/O68nEB.jpg)

You can see that the header's content gets shifted to the right when the Octotree panel is open (when it's closed too, but less).

Though I don't know if it's really a bug or if it's intentional, because I used the DevTools to see what's going on and it happens because padding gets added to the header's content. But why is that?

### Environment (if bug)

* Octotree version: 2.4.9
* Browser & version: Google Chrome 69.0.3497.100
* OS & version: Windows 10

**Comment by buunguyen** [comment]
Is this OSX? What's the total width of your browser window?

**Comment by flawyte** [comment]
It's Windows 10 and my screen/browser width is 1920.

**Comment by flawyte** [comment]
I can submit a PR if you want, if you just tell me how it should actually behave or if this part is to be removed completely.

**Comment by buunguyen** [comment]
This part can't be removed. It might not work for all cases in all browsers but removing it will definitely change the behavior on Chrome. The idea is it should push only the head when the tree is collapsed (so that the logo doesn't overlap the Octotree toggle button), but push everything when the tree expands.

**Comment by flawyte** [comment]
Okay I see. But it should only happen if needed (on small screens), right? Because if you have a "big" (classic) screen resolution such as 1920*1080, there's enough room for the sidebar to expand without overlapping the header or page's content, and thus Octotree doesn't need to push anything.

So maybe the best way is :
- First, determine if there's room for Octotree's toggle button without it overlapping GitHub's logo
- If not, shift header's content
- Else, do nothing

And the same would have to be done with the page's content when the sidebar is open.

What do you think?

**Comment by buunguyen** [comment]
Yes, it shouldn't push header or content if the button/tree doesn't overlap.
