### ISSUE TITLE
Can I add night mode?

### ISSUE THREAD

**Issue by rxliuli** [ovity/octotree#551]
My Chrome browser uses global night mode, so the color of the plugin is a bit less harmonious. Can I add an option to switch to night mode?

> Attached: Below is the github webpage

![Snipaste_2018-10-14_21-38-23.png](https://i.loli.net/2018/10/14/5bc346e855440.png)

**Comment by buunguyen** [comment]
Dup https://github.com/ovity/octotree/issues/503.

What do you mean your chrome uses "global night mode"? Is that an extension?
