### ISSUE TITLE
Feature request: octotree should respect url of a PR page

### ISSUE THREAD

**Issue by lev112** [ovity/octotree#553]
### Description
when viewing a PR, the url might have many formats:
1. single commit:
https://github.com/ovity/octotree/pull/xxx/commits/hash
this will show that changes in a single commit
1. 2 commits
https://github.com/ovity/octotree/pull/xxx/files/hash1..hash2
this will show all the changes between 2 commits
1. url parameters
https://github.com/ovity/octotree/pull/xxx/files?utf8=%E2%9C%93&diff=unified&w=1
this can be set by using the following control:
![image](https://user-images.githubusercontent.com/4376907/47202022-12e79980-d3a6-11e8-95c8-3c66fef20793.png)

I have 2 feature request (might make sense to split into to issues, but they seem related)
1. when pressing a link on the file tree, it should preserve the current url  
(the existing behavior is just to reload the page and losing the data in the url)
1. when viewing a subset of commits, the file tree should show only the files that changed in those commits  
(the existing behavior is to show all changed files)

**Comment by AmazingJaze** [comment]
Seconded. Being able to use octotree for subsets of commits is the dream.

**Comment by m-radzikowski** [comment]
Yes, losing the selected commits filter when clicking on the file in octotree to jump to it in PR is really annoying.

**Comment by danhgit** [comment]
I've just published v7 that only shows files that are changed in a commits. Also fixed the filter issue. It should be available in the stores shortly. Thanks for reporting!
