### ISSUE TITLE
Bug report for BitBucket

### ISSUE THREAD

**Issue by aaabramov** [ovity/octotree#554]
### Description

Today, I realized that octotree on BitBucket disappeared, and I thought that https://github.com/ovity/octotree/issues/514 was implemented (joke).
But actually, there is a defect in octotree which prevents left-panel to be rendered.

### Environment (if bug)

* Octotree version:
`2.5.0`
* Browser & version:
```

Google Chrome | 69.0.3497.100 (Official Build) (64-bit)
-- | --
Revision | 8920e690dd011895672947112477d10d5c8afb09-refs/branch-heads/3497@{#948}
OS | Mac OS X
JavaScript | V8 6.9.427.23
Flash | 31.0.0.122 /Users/_________/Library/Application Support/Google/Chrome/PepperFlash/31.0.0.122/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
```
* OS & version:
![image](https://user-images.githubusercontent.com/11317222/47222263-ef7d1880-d3be-11e8-851d-e18149aaa32e.png)
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/11317222/47222052-885f6400-d3be-11e8-9590-97bc0fb3171a.png)

![image](https://user-images.githubusercontent.com/11317222/47222042-7f6e9280-d3be-11e8-8252-3a7a2b11c46f.png)

* Console error log below this line
The following errors are printed to console:
![image](https://user-images.githubusercontent.com/11317222/47222111-a200ab80-d3be-11e8-886a-bb6fd4884c24.png)

**Comment by buunguyen** [comment]
Thanks for reporting the issue.

Bitbucket support was removed from 2.5. I'm not exactly sure why the errors show up, maybe there's a caching problem. Can you try uninstall & reinstall Octotree?

**Comment by aaabramov** [comment]
@buunguyen after reinstalling Octotree, no issues were found.
Bitbucket is free of error logs & strange clicks.

Since I have this opportunity, thank you for your work!

**Comment by buunguyen** [comment]
@aaabramov thanks for reporting back. And glad the tool is useful for you!
