### ISSUE TITLE
Pull request creation failed. Validation failed: A pull request already exists for tajawal:HUB-1222.

### ISSUE THREAD

**Issue by zeeshanbashir** [ovity/octotree#557]
### Description
I am trying to create a pull request and I am getting this in response.
`Pull request creation failed. Validation failed: A pull request already exists for tajawal:HUB-1222.` but if you look at the PR's you won't find any PR. 
### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
And you're sure this is caused by Octotree?

**Comment by like-github1** [comment]
You've already created a pull request from the same branch Name. Try creating a new branch with diffrent name  at the same commit (git checkout -b new-branch) and creating the pull request from there
