### ISSUE TITLE
Octotree is adding padding-left to the GitHub Header

### ISSUE THREAD

**Issue by lalitmee** [ovity/octotree#560]
### Description
When **Octotree** is enabled, some `padding-left` is added to the **GitHub** header. Here is the [screenshot](https://imgur.com/a/5PcgYZ2) of the view.

### Environment (if bug)

* Octotree version: **2.5.0**
* Browser & version: **Google Chrome => Version 70.0.3538.67 (Official Build) (64-bit)**
* OS & version: **Lubuntu 18.04**
* Screenshot, if any (drag an image here) 
![2018-10-24-174747_1920x1054_scrot](https://user-images.githubusercontent.com/10762218/47429984-a0b3f200-d7b5-11e8-8af3-8006bb6406e7.png)

* Console error log below this line
**None**

**Comment by jdreesen** [comment]
Same for me.

### Environment

* Octotree version: 2.5.0
* Browser & version: Firefox 62.0.3
* OS & version: Ubuntu 16.04 as well as Windows 10

**Comment by saildata** [comment]
Using the [github-wide](https://github.com/mdo/github-wide/blob/master/github-wide.css) userstyle seems to fix it.

Without github-wide:
![octotree_without_githubwide](https://user-images.githubusercontent.com/11636184/50378030-433df500-05ee-11e9-9039-a5e5b2cda171.png)

With github-wide:
![octotree_with_githubwide](https://user-images.githubusercontent.com/11636184/50378032-4a650300-05ee-11e9-8aa9-cc86f4c8a091.png)

**Comment by buunguyen** [comment]
Does this still happen with v3.x?
