### ISSUE TITLE
Clears saved issue drafts on reload

### ISSUE THREAD

**Issue by prydonius** [ovity/octotree#561]
Thanks a lot for building Octotree, it's an incredibly useful tool!!

### Description

Steps to repro:
1. Start creating a new issue
2. Add a label to the issue
3. Click on a link to something else (e.g. the label)
4. Click back in the browser to return back to the issue
5. See the previous draft appear but then disappear while Octotree loads

![octotree-issue-text-clear-bug](https://user-images.githubusercontent.com/1544861/47487512-db17a080-d842-11e8-8ba8-a8fbdcd8ebc9.gif)

### Environment (if bug)

* Octotree version: 2.5.0
* Browser & version: Version 69.0.3497.100 (Official Build) (64-bit)
* OS & version: macOS 10.13.3 (17D102)

**Comment by danhgit** [comment]
We fixed this in 7.5.0
