### ISSUE TITLE
Gitlab not work

### ISSUE THREAD

**Issue by exotfboy** [ovity/octotree#566]
I know octotree support gitlab online and gitlab enterprise, however it can not load the data after I set the gitlab enterprise url, and it seems that octotree use api v3 to fetch data from gitlab while the v2 is not supported.

* Octotree version: 2.5.1 
* Browser & version: Chrome  70.0.3538.77
* OS & version: Win 10
* Screenshot, if any (drag an image here) 

![image](https://user-images.githubusercontent.com/16457917/47892365-36c0da00-de92-11e8-9e04-1155a8c8a2a2.png)

* Console error log below this line

{"error":"API V3 is no longer supported. Use API V4 instead."}

* Gitlab-ce version: GitLab Community Edition 11.2.3

**Comment by buunguyen** [comment]
Sorry, gitlab was no longer supported for a while.

**Comment by exotfboy** [comment]
Is there any special reason for stopping support for gitlab?

**Comment by kirill-konshin** [comment]
Is there any chance to get the support back? Do you need help with something in particular?

**Comment by cehoffman** [comment]
Given there is now a paid :face_with_open_mouth_vomiting: version, it seems all reasons for not GitLab support have vanished.

I poke fun, but this is a reason I would pay for the _pro_ version.

**Comment by kirill-konshin** [comment]
@buunguyen Actually, I'd pay for GitLab if it would be there.

Additionally, GitLab devs landed a tree feature for pull requests.

**Comment by albacoretuna** [comment]
This is a new extension specifically for Gitlab if you came here by searching: 
https://github.com/tavyandy97/span-tree
