### ISSUE TITLE
Can't see the background html

### ISSUE THREAD

**Issue by jnxyatmjx** [ovity/octotree#572]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

I use Octotree version is 2.5.1 in Chrome 70.0.3538.102 64bit  on Windows 10.
It only display the octotree tree but can't display the original github html page. why?

**Comment by jnxyatmjx** [comment]
![image](https://user-images.githubusercontent.com/9018335/48528442-02094580-e8ca-11e8-8125-c3a3f9ae9d86.png)
It looks like this page.

**Comment by buunguyen** [comment]
Please open local storage and update this key `octotree.sidebar_width` to 300.
