### ISSUE TITLE
Horizontal scrollbar on commit split page

### ISSUE THREAD

**Issue by djy0** [ovity/octotree#576]
### Description
Open this page `https://github.com/facebook/react/commit/5bce0ef10ab28c87e57dd96dbe1d8470f8d68569?diff=split` and open octotree sidebar, you can see a horizontal scrollbar appear at the bottom

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: chrome 70
* OS & version: windows 10
* Screenshot, if any (drag an image here)

* Console error log below this line

**Comment by buunguyen** [comment]
I believe this was fixed. Please open a new issue if it still exists in the latest version.
