### ISSUE TITLE
Click file automatically add some prefix

### ISSUE THREAD

**Issue by daoluan** [ovity/octotree#579]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.
![image](https://user-images.githubusercontent.com/2241128/48893727-fe526180-ee7b-11e8-923f-56fe6f9fb2a5.png)

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: newest
* OS & version: macos
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/2241128/48893776-12965e80-ee7c-11e8-8df2-635fe763acbe.png)

* Console error log below this line

**Comment by buunguyen** [comment]
Which browser and step to reproduce?

**Comment by daoluan** [comment]
chrome anytime

**Comment by Kerita** [comment]
The same

**Comment by Kerita** [comment]
Caused by another chrome extension
 [BitApp Wallet](https://chrome.google.com/webstore/detail/bitapp-wallet/fihkakfobkmkjojpchpfgcmhfjnmnfpi)

**Comment by buunguyen** [comment]
Thanks for updating, @Kerita.
