### ISSUE TITLE
About file name sorting

### ISSUE THREAD

**Issue by Lipang** [ovity/octotree#582]
### Description
I found that this extension does not correctly sort files with names as numbers, just like in images.
- ![image](https://user-images.githubusercontent.com/33782391/49268718-0faef580-f49c-11e8-9a6d-b5f205579244.png)

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: Chrome
* OS & version: Windows10

**Comment by James-Quigley** [comment]
`src/adapters/github.js` line 301.

Should just be able to change it to:
```
// Sort by path, needs to be alphabetical order (so parent folders come before children)
// Note: this is still part of the above transform to mimic the behavior of get tree
tree.sort((a, b) => a.path.localeCompare(b.path, window.navigator.userLanguage || window.navigator.language, {
    numeric: true
}));
```

**Comment by ngocpt1906** [comment]
Let me look at this issue, thanks for reporting!

**Comment by danhnguyen30041975** [comment]
@ngocpt1906 Since there is no progress from you, I closed your PR it

**Comment by endyquang** [comment]
In my experience i've never see a good ux that treat the file's name as number.
This is not an issue but just the desired behavior for sorting file.

**Comment by buunguyen** [comment]
@endyquang 	what is the sorting behavior in GitHub itself? As long as Octotree matches it, then it's fine.

**Comment by James-Quigley** [comment]
Can confirm it matches GitHub:
![image](https://user-images.githubusercontent.com/12548978/62062185-843a5f80-b1f6-11e9-864b-dc1bb957d855.png)

**Comment by buunguyen** [comment]
Great, thanks @James-Quigley! Closing this issue now.
