### ISSUE TITLE
Buggy/agitated transition

### ISSUE THREAD

**Issue by nmaxcom** [ovity/octotree#584]
"Trembling" effect when widening the sidebar

* Octotree version: **2.5.1**
* Browser & version: **Google Chrome | 70.0.3538.110 (Official Build) (64-bit)**
* OS & version: **macOS Sierra (10.12.6)**
* Video:

https://youtu.be/50Xc947vURw

**Comment by buunguyen** [comment]
That looks super annoying. What is the screen resolution?

**Comment by nmaxcom** [comment]
It's a 15.4" at 2880 x 1800

**Comment by buunguyen** [comment]
Does this still happen with v3.0?

**Comment by nmaxcom** [comment]
Yes, but I just realized it's my fault.

I made a personal CSS file for GitHub (wider and easier to read among other changes) that is loaded with the Stylus chrome extension. I got too used to it that I'd forgotten.

But when turned off it works as expected.

**Comment by buunguyen** [comment]
Got it, thanks for the update. Glad you resolved the problem.
