### ISSUE TITLE
Footer covers last item

### ISSUE THREAD

**Issue by benwaffle** [ovity/octotree#594]
### Description
Missing `dev.go`:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1713819/50616118-28546600-0eb5-11e9-9451-4be2c7f17f3c.png">

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: Firefox 64.0
* OS & version: macOS 10.14.2

**Comment by buunguyen** [comment]
Fixed in v3, will release soon.
