### ISSUE TITLE
Switch to lazy loading when "Load entire tree at once" is required.

### ISSUE THREAD

**Issue by samvel1024** [ovity/octotree#595]
Sometimes when I browse a huge repo, the tree is not rendered and a message asks to enable "Load entire tree at once". ([example](https://github.com/Stichting-MINIX-Research-Foundation/minix)) However when I enable it I get an annoying lag when I browse small repositories since the implementation of the lazy strategy is fetching each directory separately. 

My suggestion is to dynamically switch the strategy from eager to lazy when the user tries to browse a huge repository, because having "Load entire tree at once" enabled all the time slows down the user a little bit. I would be happy to help in the realisation of this feature.

Thanks for the great utility

**Comment by buunguyen** [comment]
Sounds reasonable. Maybe handle that error, then automatically lazy for that repo only. Can you send a PR?

**Comment by buunguyen** [comment]
Closed as it was merged.
