### ISSUE TITLE
Execution of tests / Chrome headless doesn't work

### ISSUE THREAD

**Issue by theHolgi** [ovity/octotree#604]
### Description
I'm trying to reproduce the tests, and am unable to get it to work.
- With Chrome, tests succeed until the 3rd one ("should toggle upon button click") with display (reason: right=12px instead of 5px)
- Headless Chrome (test/factory.js: options.addArguments(['--headless']) fails already the very 1st test; plugin is completely inactive
- With Firefox, the plugin is not installable (no rule for firefox.xpi), and firefox.zip can only be installed with tweaking selenium (see [here](https://stackoverflow.com/questions/44969025/unable-to-install-webextension-with-selenium))
- Firefox tests fail the 1st test (sidebar 233 pixel wide instead 232)
- At least, Firefox headless _works_ in general

Remark: Headless operation is imperative for automated test execution, therefore my focus on it.
**Q**: What is your test environment?

### Environment (if bug)

* Octotree version: commit 9259377f (2018-12-01)
Node.js 10.14.1
* Browser & version:
Chromium 71.0.3578.80
ChromeDriver 2.42.591071 as installed by npm dependencies
Firefox 64.0
geckodriver 0.23.0
* OS & version:
Ubuntu 16.04
* Screenshot, if any (drag an image here)
* Console error log below this line
See separate comments

**Comment by theHolgi** [comment]
2) Setup with chrome-headless:
<pre>
....
[11:49:48] Starting 'test'...


(node:17691) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
  chrome
    init
      1) should create toggle button and sidebar
    main
      tree
      opts
        values
          token
          hotkey
          remember
          non-code

  firefox
    init
    main
      tree
      opts
        values
          token
          hotkey
          remember
          non-code


  0 passing (11s)
  1 failing

  1) chrome init should create toggle button and sidebar:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".octotree_toggle"}
  (Session info: headless chrome=71.0.3578.80)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.4.0-139-generic x86_64)
      at new bot.Error (/home/lamm/devel/njs/octotree/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
...
</pre>
screenshot take from the testcase (po.driver.takeScreenshot()) shows no octotree triangle:
![out](https://user-images.githubusercontent.com/13648152/51175952-f8955d00-18bb-11e9-93ff-1156c543d038.png)

**Comment by theHolgi** [comment]
Pity me. Chrome headless just [doesn't support extensions](https://bugs.chromium.org/p/chromium/issues/detail?id=706008).
Can you still answer the general question: What is your test environment and what are your experiences with firefox?

**Comment by dinkelaker** [comment]
@steffen from GH wants to have a lock at this issue.

**Comment by buunguyen** [comment]
Sorry, but I no longer maintain the tests. Gonna delete it.
