### ISSUE TITLE
Can't open a tree with name having more than 14 chars

### ISSUE THREAD

**Issue by liyuankui** [ovity/octotree#609]
### Description

Can't use for this public repo on this branch
https://github.com/spring-cloud/spring-cloud-netflix/tree/gh-2479-zuul-hystrix-timeout

### Environment (if bug)

* Octotree version: latest
* Browser & version: Chrome latest
* OS & version: MacOS
* Screenshot, if any (drag an image here)
* Console error log below this line

404 `https://api.github.com/repos/spring-cloud/spring-cloud-netflix/git/trees/gh-2479-zuul-h%E2%80%A6?recursive=1&_=1548032193725`

**Comment by RomanKornev** [comment]
Fixed in #603

**Comment by buunguyen** [comment]
Just released in 2.5.2
