### ISSUE TITLE
[Question] Security Concern over Access Token authorization for private repos

### ISSUE THREAD

**Issue by adamchenwei** [ovity/octotree#610]
### Description
Octotree ask for Github ` Full control of private repositories` authority for access token on private repos.

Is it grant access to read the private repos code completely or just status related data?

Feel free to answer in SO if wished.
Ref: https://stackoverflow.com/questions/54294049/github-full-control-of-private-repositories-authority-for-access-token-grant

**Comment by buunguyen** [comment]
Whatever permission needed to access GitHub API. Not sure if GitHub permissions are fine-grained enough, but feel free to play around to limit the granted scope.
