### ISSUE TITLE
Side bar background color doesn't change for GitHub Enterprise

### ISSUE THREAD

**Issue by chvarunkumar1994** [ovity/octotree#612]
### Description
When the background color of the page is updated, sidebar's background color is updated accordingly in the GitHub version but not in the GitHub Enterprise version. 

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: Google Chrome & Version 71.0.3578.98 (Official Build) (32-bit)
* OS & version: Windows 10
* Screenshot

![thatdoesntworkwhitebg](https://user-images.githubusercontent.com/7436391/51632701-9240b800-1f15-11e9-8965-50a1f81d43a3.png)
* Console error log -
Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".
jstree.js:6 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.

**Comment by buunguyen** [comment]
Please consider paying for Octotree Pro to have built-in dark mode support and GitHub Enterprise: https://www.octotree.io/
