### ISSUE TITLE
It keeps saying a certain repository is private, while the repository is actually public

### ISSUE THREAD

**Issue by ferrybig** [ovity/octotree#615]
### Description

**Steps to reproduce:**

1. Go to https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Expected:** 

It shows all the files in that repository

**Actual:**

It says the repository is private

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
* OS & version: Ubuntu 18.04.1 LTS
* Additional information: I'm using a 4k screen, with scaling at 100% and the zoom on its default settings
* Console error log below this line

        GET https://api.github.com/repos/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/git/trees/eeeeeeeeeeeeee%E2%80%A6?recursive=1&_=1548497474269 404 (Not Found)

This is not an duplicate of the 4 issues linked by github, as the example repositories in those issues all work at the moment

**Comment by ferrybig** [comment]
The extension seems to mis-interpreting the master branch of the repo.

It thinks the master branch is `eeeeeeeeeeeeee…`, while the actual master branch is `eeeeeeeeeeeeeeeeeeeeeeee`

And then interprets the 404 error it receives as that the repository is private

**Comment by jdreesen** [comment]
May this have been fixed by https://github.com/ovity/octotree/pull/603 recently?
I don't think the fix has been released yet, though.

**Comment by ryaninvents** [comment]
I'm seeing similar behavior when there is a slash character (`/`) in the branch name, such as `fix/should-not-crash`

**Comment by buunguyen** [comment]
Just released in 2.5.2
