### ISSUE TITLE
Safari does not execute the plugin script because of Content Security Policy

### ISSUE THREAD

**Issue by kradalby** [ovity/octotree#638]
### Description
Application does not render the github repo tree in the correct way. Left side stays blank and tree ends up below the github footer.

Error rendered in console:
`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

#### Reproduce
1. Build for Safari
2. Load through the Safari Developer menu
3. Go to a github repo

### Environment (if bug)

* Octotree version: 2.5.5 (2.5.4 and master)
* Browser & version: Safari 12.0.3
* OS & version: macOS 10.14.3
* Screenshot, if any (drag an image here)
![View](https://screenshots.kradalby.no/20190318111848.png)
![Error](https://screenshots.kradalby.no/20190318111758.png)
* Console error log below this line
`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

**Comment by buunguyen** [comment]
https://github.com/ovity/octotree/issues/539#issuecomment-476486281
