### ISSUE TITLE
can you add it to suport gitlab or other site like github

### ISSUE THREAD

**Issue by zhang512322977** [ovity/octotree#640]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by albacoretuna** [comment]
This is a new extension specifically for Gitlab if you came here by searching: 
https://github.com/tavyandy97/span-tree
