### ISSUE TITLE
download specific file with oneclick

### ISSUE THREAD

**Issue by YvonneD** [ovity/octotree#641]
Hi, I am using the extension for a long time and love it. I used to download single file with the download button at the right side of each file from my mind. But I found the download button all gone nowadays. If click the icon front, the code will open with another tab. But I really love the way download to computer directly like before. 
Is that the correct display?
![image](https://user-images.githubusercontent.com/14529637/55026018-7a021d80-4fd8-11e9-8d34-bf1a3985b265.png)
Anyone know how to add the download button? 
Thank you

**Comment by buunguyen** [comment]
Yeah, this annoys me too. But there was a browser change that disallowed direct download like that. I'm not aware of any new workaround at the moment though.

**Comment by YvonneD** [comment]
> Yeah, this annoys me too. But there was a browser change that disallowed direct download like that. I'm not aware of any new workaround at the moment though.

Got it.I didn't realise there is a browser change back days.  Hopefully have other way to make convience.
btw if the "download btn" can link to google drive or dropbox something like that so that should be a dowload to computer selection?

**Comment by uilnauyis** [comment]
@buunguyen Thanks for creating this cool project~! 

I did a quick google search and saw this StackOverflow thread: https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo. In the top accepted answer, there are two cool projects that enabling users downloading files or folder of a URL. Would you consider implementing the downloading functionalities in some ways similar?

**Comment by buunguyen** [comment]
AFAIK, this is still not technically possible with Chrome. Gonna close it. If it's possible in the future, we'll revisit this.
