### ISSUE TITLE
Disable drawer open on hover

### ISSUE THREAD

**Issue by SpencerPark** [ovity/octotree#648]
This is more of a feature request but really is a request for reverting a "feature". 

octotree just updated on me to v3.0.0 and the new sidebar (which I keep closed unless looking for files) has the new functionality of opening on mouseover and it is getting a little frustrating. Could the hover functionality be under a flag instead? I would only like the drawer to open when I click on the button.

Otherwise the drawer keeps opening when I just want to move my mouse out of the way, or in another case where my second monitor is to the left and my mouse crosses over the boundary to get there, again the drawer opens when I wouldn't like it to.

Thanks for all your work on octotree, it makes github much more enjoyable :)

**Comment by Dekken** [comment]
Really not liking the new update either - this is one reason

**Comment by buunguyen** [comment]
Providing an option to click to open makes sense. We'll work on that.

**Comment by buunguyen** [comment]
@Dekken 

> Really not liking the new update either - this is one reason

What are the other reasons?

**Comment by hsluoyz** [comment]
The sidebar keeps opening by itself all the time when I looked at a GitHub repo. I still prefer the original button. Is there any way to go back? Thanks.

**Comment by nphi** [comment]
I have created a PR for switching between hover and click behaviour. I hope it would be merged ASAP

**Comment by laudavid** [comment]
I do not like the feture too, please fix it as soon as possible .

**Comment by nphi** [comment]
@hsluoyz  I guessed you're in the pinned mode by using hotkeys. Could you check if the pin icon is on?
![Screen Shot 2019-04-14 at 3 32 28 PM](https://user-images.githubusercontent.com/8633840/56090294-b2f02c80-5eca-11e9-810b-2c97a2faf509.png)

**Comment by Dekken** [comment]
> @Dekken
> 
> > Really not liking the new update either - this is one reason
> 
> What are the other reasons?

It has disabled use of user styles (stylus/stylish)

**Comment by tamer1an** [comment]
@Dekken  but they are monetizing black theme now  :finnadie:

@buunguyen  Is it makes sense to do enterprise access also not free? I use this extension for a 5 year as long as it exists. 

As i understand this will not offence GPL licence if I fork this and release a version that allows darkmode and enterprise for free :godmode:? if some one already does this please give a link to the fork.

also, new sidebar hover over is  annoying ⚡️, u cannot prevent it to stay hidden, if u pin it and use hotkey it will turn on hover listener again

**Comment by hanzheteng** [comment]
Totally agree. I always keep it hidden unless I click the button. With this new version update, it often appears by mistake when my cursor moves to the left side, which is really annoying.

**Comment by buunguyen** [comment]
Folks, please don't complain about why we need to charge for Octotree Pro in this thread. We already provide the reason [here](https://github.com/ovity/octotree/blob/v3/HISTORY.md#v300). If you need advanced features, please consider paying to support our continued development effort. Or help fix a bug and I'll send you a discount code to use Octotree Pro for free. But it's quite off-putting when the only thing some people ever do to Octotree after benefitting from it for years is suggesting ways to circumvent our effort to build a sustainable project. Such posts will be deleted.

**Comment by buunguyen** [comment]
Alright, I've just published an update (3.0.1) that includes the option to show sidebar upon hover (enabled by default, so most people in this thread should explicitly uncheck it). Also include the fix of the bug where hovering the edge of the screen causes the sidebar to show. Should be available shortly. Thanks for everyone for reporting the issue and suggesting solution.

**Comment by tavr2009** [comment]
Oh that's was fine when you @buunguyen suggest to contribute for getting a free version. I would use this opportunity. But you also seems to ban me, That's a right way to go, on how this organization should treat a fans on the extension.

Two years ago I was promoting to use this extension in our company internally where we have more then 2000 users of this extension. I was even thinking to rise a poll on Monday for the Pro version.

But you hostility @ovity make me think that's not what I should do, Will write an article about that on company's inner forum tomorrow at Monday. Luckily for you at enterprise, decisions processing for some time. It take me two month to approve octo-tree usage and un-block internal access to it for everyone.

**Comment by SpencerPark** [comment]
Thanks @buunguyen and @nphi for the incredibly fast response and resolution of the issue!

@tavr2009 this seems a bit off topic and doesnt really belong on this thread. Also I think that as a community we should try to be a bit more considerate towards the developers that spend their free time over many years to bring us free and open software. 

Ive mentioned it in the original post but it cant be said enough, thanks again for all your work on octotree!

**Comment by buunguyen** [comment]
@SpencerPark thank you, we really appreciate your kind words and support.

**Comment by buunguyen** [comment]
@tavr2009 I don't remember blocking you. Unless you also possess a different GitHub account, which was blocked because of the aggressive tone and being off-topic. I'm not gonna block your account this time, but please stay on topic or create a new thread. But keep in mind I won't tolerate any level of abuse to the contributors and any such attempt will be reported and blocked. None of us deserves any of this just because we want to find a sustainable way to continue working on the project.

**Comment by nfour** [comment]
TBH This new update made me uninstall. Before, I had a dark theme via the many github dark theme options available, or Dark Reader etc. Now this sidebar looks out of place even without styling, and as this issue highlights, the drawer opens up when you dont want it, and presumably computes when you dont want it either.

Just some feedback, hope you figure out how to monetize better than dark themes n stuff in future.

**Comment by buunguyen** [comment]
@nfour sorry about that, it's unintentional, we certainly don't want to break whatever workflow people are using but it's impossible to test everything when we revamp the UI. We'll look into this. Meanwhile, if you want to use dark mode properly, I can send you a 50% discount coupon to use (and you can cancel after we fix this issue).

**Comment by hanzheteng** [comment]
Hi @buunguyen ,

Just want to report that the bug `hovering the edge of the screen causes the sidebar to show` hasn't been fixed. 

After unchecking `open sidebar on hover`, it's not open when my cursor hovers on `Octotree` now, but still open when my cursor hovers on the left edge of my browser. 

Now it's version `3.0.4`.
