### ISSUE TITLE
Non-repository pages have width adjustment issues.

### ISSUE THREAD

**Issue by maliming** [ovity/octotree#651]
### Environment

* Octotree version: 3.0.0
* Browser & version:  chrome Version 73.0.3683.103 (Official Build) (64-bit)
* OS & version: windows 10
* Screenshot, if any (drag an image here)

![](https://user-images.githubusercontent.com/6908465/56090127-47a95900-5ed0-11e9-8154-b9e12866f373.gif)

**Comment by nphi** [comment]
@maliming !
Thanks for reporting the issue. I have created PR to addressing it. It will be fixed soon.
