### ISSUE TITLE
What is the purpose of sending data with the user identification to octo-tree?

### ISSUE THREAD

**Issue by tamer1an** [ovity/octotree#652]
### Description
Hi, dear extension maintainer, please could u check is this response belongs to your extension?

What is the purpose of sending this data with the user identification?
 
![image](https://user-images.githubusercontent.com/956869/56092495-2db24b00-5ebd-11e9-89e9-d0e721b706fc.png)

**Comment by nphi** [comment]
Hi, @tamer1an! 
The request doesn't belong to the Octotree. Octotree doesn't collect/share/care about your data at all. Octotree solely cares how to improve user's productivity.

**Comment by tamer1an** [comment]
@nphi thanks for the quick response, you right. Github just not always sending that request that's why I missed it when I test it before opening this ticket.

Regards, 
Andrii
