### ISSUE TITLE
Can't add token after the 3.0 update

### ISSUE THREAD

**Issue by humazed** [ovity/octotree#653]
### Description
after updating to 3.0 the old token no longer works and after creating a new one and click apply the token is not even saved

### Environment (if bug)

* Octotree version: 3.0
* Browser & version: chrome latest version
* OS & version: windows
* Screenshot,
![image](https://user-images.githubusercontent.com/8838182/56094542-a0c7bb80-5ed5-11e9-990a-388c64557419.png)
![image](https://user-images.githubusercontent.com/8838182/56094548-afae6e00-5ed5-11e9-895a-a6810f435fa9.png)
![image](https://user-images.githubusercontent.com/8838182/56094551-b6d57c00-5ed5-11e9-800b-fafc9a45925b.png)

**Comment by buunguyen** [comment]
That's strange. Can you open the dev console to see if there's any error? How about checking local storage to see if the token is there? Also check to make sure you don't copy extra whitespace into the token.

**Comment by humazed** [comment]
I get this error in the console 

> Octotree cannot save its settings. If the local storage for this domain is full, please clean it up and try again. DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'octotree.access_token' exceeded the quota.
    at Storage.set (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:2886:20)
    at chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:4142:20
    at chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:4160:11
    at Storage.get (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:2898:13)
    at chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:4159:20
    at chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:2816:5
    at Array.forEach (<anonymous>)
    at parallel (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:2815:7)
    at OptionsView._eachOption (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:4153:5)
    at OptionsView._save (chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:4137:10)
set @ chrome-extension://bkhaagjahfmjljalopjnoealnfndnagc/content.js:2891
api

**Comment by buunguyen** [comment]
Thanks for posting. Looks like your local storage is full and thus the token can't be saved. Just open the console and do this: localStorage.clear(), then try again.

**Comment by humazed** [comment]
I get this 
![image](https://user-images.githubusercontent.com/8838182/56097156-ff4e6300-5ef0-11e9-9ed1-f970d907c973.png)

**Comment by buunguyen** [comment]
Just to be clear, you have to be on github.com when doing that. Then try reloading Octotree and add the token.

**Comment by humazed** [comment]
I'm on Github the home page and using chrome btw.

**Comment by humazed** [comment]
in the screenshot am I doing something wrong?

**Comment by buunguyen** [comment]
No, I don't think so. Does it work now?

**Comment by buunguyen** [comment]
Basically you need to free up your local storage for Octotree to work.

**Comment by humazed** [comment]
`localStorage.clear()` doesn't work so I searched for a way to clear the local storage but when I looked at it is basically empty. 

I'm not a web dev so I'm not sure I'm looking at the right place.

![image](https://user-images.githubusercontent.com/8838182/56097393-a46a3b00-5ef3-11e9-94c2-67cf41faf874.png)

**Comment by buunguyen** [comment]
Sorry, I don't know how else to help. If you clear the local storage, it should work. If not, send me more error log.

**Comment by humazed** [comment]
After trying to add a new token now it works.
I guess running `localStorage.clear()` solve it.

**Comment by buunguyen** [comment]
Great, thanks for reporting back!
