### ISSUE TITLE
NO code tree

### ISSUE THREAD

**Issue by 631068264** [ovity/octotree#658]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version: Octotree 3.0.1

* Browser & version: Google Chrome  73.0.3683.103
* OS & version:  OSX 10.14.4
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/8144089/56107772-bc38d200-5f7a-11e9-9fec-2d786075df90.png)

* Console error log below this line
![image](https://user-images.githubusercontent.com/8144089/56107807-ebe7da00-5f7a-11e9-8ff6-05a88464b796.png)

**Comment by buunguyen** [comment]
Hi, please do a localStorage.clear() on github.com, looks like your local storage is full.

**Comment by 631068264** [comment]
Oh thanks @buunguyen It works
