### ISSUE TITLE
Pro DarkMode

### ISSUE THREAD

**Issue by Nerdsolutions** [ovity/octotree#661]
Now you offer Dark Mode for pro Version. Wow. Time to copy octotree. 

This is how you destroy a good browser extension. 30 per for Dark Mode. Go fuck off.

**Comment by buunguyen** [comment]
Dark mode and a bunch other features. But of course you would choose to be rude. And no, it's not time to copy Octotree, I don't think someone who lacks the empathy to open source maintainers can maintain an open source project. You can't even handle this without resorting to cursing!
