### ISSUE TITLE
Add ability to disable popover for private repo's without github key 

### ISSUE THREAD

**Issue by chbonser** [ovity/octotree#663]
### Description
I use this extension exclusively for open source work and it is great! The recent update however causes the left bar to pop over every time I load a private repo and requires me to click the screen to make it go away. This so annoying I've had to disable the addon. 

Is there a feature to only display the sidebar which clicking on the tab? Or can one be added? Thanks!

### Environment (if bug)

* Octotree version: 3.0.1
* Browser & version: Firefox 66.0.3
* OS & version: Mac 10.14.4

**Comment by brockallen** [comment]
Ah, this is the exact issue I was coming to open:

https://twitter.com/BrockLAllen/status/1117779158132842496

**Comment by nphi** [comment]
I think it’s a bug instead of a feature. Will investigate on it and fix it ASAP. 

Thanks for reporting the issue

**Comment by vonHabsi** [comment]
The Octotree activation button was discreetly out of the way at the top of the screen and it was just a button with a `>` on it. Right now it floats halfway down the screen and it is labelled `Octotree`. It also opens the octotree sidebar when you accidentally scroll over it,with a bright blue message informing you about `Octotree Pro`.

It is happening a lot to me because I use Tree Style Tabs on the left sidebar.

I understand the need to promote the commercial version but I it should be done in a less intrusive manner.

**Comment by nphi** [comment]
Hi @vonHabsi !

Thanks for your constructive feedback ! Octotree offers the hover-to-open behavior to minimize the step user need to open the tree. But if you want to click instead of hover, you could uncheck the “open those sidebar on hover” option in the settings.

**Comment by vonHabsi** [comment]
I noticed the option to change the hover behaviour from the settings later. I think it will also be a good idea to replicate those preferences in the general Addon preferences page. It is the first place I looked when I wanted to see if it was possible to change that behaviour.

**Comment by nphi** [comment]
That’s a good idea. I will think about how to implement it properly. Thanks for your input ;)

**Comment by buunguyen** [comment]
This should have been fixed in 3.0.2. Gonna close the issue now, if it still happens, please let us know. Thanks.

**Comment by bpceee** [comment]
@buunguyen Still exist in 3.0.2. 

- Octotree version: 3.0.2
- Browser & version: Chrome 73.0.3683.103 (Official Build) (64-bit)
- OS & version: Mac 10.14.4

**Comment by buunguyen** [comment]
@vonHabsi thanks for the note.

wrt "with a bright blue message informing you about Octotree Pro."

I agree. Would appreciate a PR to make it seem more discrete to you and we'll be happy to merge.
