### ISSUE TITLE
Feature request: theme customization

### ISSUE THREAD

**Issue by jaychsu** [ovity/octotree#664]
### Description

I really like the simple interface in v2.x, so can the users customize the theme? BTW, in my macOS, the new interface in v3.0 is very slow (maybe from animation delay)... so for now, I just temporarily use a custom build in v2.5.6.

**Comment by buunguyen** [comment]
Sorry to hear that. Can you share a vid so that we can get a feel of how slow it is on your end?

**Comment by jaychsu** [comment]
Thank you for making a change to speed up the animation, I think it improved the experience a lot.

**Comment by buunguyen** [comment]
Awesome, great to hear and thanks for sending over the feedback!
