### ISSUE TITLE
LastPass asks to update password after octotree login

### ISSUE THREAD

**Issue by jameshounshell** [ovity/octotree#666]
### Description
Given:
- mac os and google chrome with specs from Environment section
- Have Lastpass and Octotree pro chrome plugins installed
- Be logged in to last pass
- Be logged into github.com
- Don't be logged in to octotree

Then:
- Navigate to github
- open octotree sidebar
- log in to octotree

Behavior:
- BUG: Lastpass will now ask if you want to update your github.com password, this is not desired behavior, had to fight lastpass to get it to reject the password update
- Desired Behavior: 
    - Octotree asks for login by clicking the octotree plugin icon 
    - OR (from github) redirecting to a new page for login (ideally a domain associated with octotree so that lastpass can store the credentials and associate them with the octotree domain)

Notes:
I do realize that this is tricky behavior to solve for. I love octotree and just want it to be the best product possible. I ran into this after becoming a paid subscriber this morning.

### Environment
* Octotree version: 1.0.3
* Browser & version: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* OS & version: mac os mojave v10.14.3
* Screenshot, if any : none available
* Console error log below this line: not needed

**Comment by buunguyen** [comment]
Thanks for the detailed bug report. I wish all bug reports are like this!

We'll look into it ASAP.

**Comment by jameshounshell** [comment]
No problem. I'm a developer too and I feel the pain of bad bug reports so I
try to do my best.

Tell me if you need any more info. I can even create a gif of the actions
taken if you need it.

Thank you again! Thank you for your work!

**Comment by buunguyen** [comment]
I believe this was fixed. Thanks again for reporting. If you still see it, please let me know.
