### ISSUE TITLE
Overlapping icons

### ISSUE THREAD

**Issue by K-Sato1995** [ovity/octotree#671]
### Description

![image](https://user-images.githubusercontent.com/32632542/56176017-93751300-6034-11e9-9cc0-3f4b98bbe92c.png)

### Environment (if bug)

* Octotree version:3.0.2
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by nphi** [comment]
Could you check if the issue is duplicated with this https://github.com/ovity/octotree/issues/650

**Comment by K-Sato1995** [comment]
@nphi 
This was a complete duplication of #650 .
Sorry and Thanks!

**Comment by nphi** [comment]
Always welcome to make Octotree better ;) Cheers
