### ISSUE TITLE
Add Dark Theme support?

### ISSUE THREAD

**Issue by saulojoab** [ovity/octotree#672]
It's been quite a while since I've been using a <a href="https://github.com/StylishThemes/GitHub-Dark">Dark Theme</a> on GitHub. Now that I've installed your extension, it really hurts my eyes because of the contrast.

![image](https://user-images.githubusercontent.com/37988252/56194025-66ab0680-6008-11e9-97ad-1659d0afb872.png)

As you can see, it doesn't look great. If you could add a Dark Theme support, it would be really awesome!

**Comment by lateek35** [comment]
There is a Dark Theme support, it's one of the Octotree Pro plan feature.
see [there](https://www.octotree.io/pricing)

**Comment by buunguyen** [comment]
Gonna close the issue now. Hope you would consider using Octotree Pro for this feature and support our ongoing development.
