### ISSUE TITLE
How to downgrade to specific version?

### ISSUE THREAD

**Issue by DarcySail** [ovity/octotree#674]
No offence, but how could I downgrade octotree v3.0.0 to v2.5.5. I'm not comfortable with new GUI.

**Comment by nphi** [comment]
@DarcySail Could you give me more specific UI feedbacks? What makes you feel comfortable ? I’d love to hear from you guys so that we could improve the Octotree ?

**Comment by DarcySail** [comment]
Thanks for your reply:)

Well, I'm a heavy Vim user, the most important change for me is that the disapper of "Hide button" in v3.0.0, the only way to hide Octotree is click outside the Octotree(or move mouse outside Octotree,) which means I have to move my hand from keyboard to mouse.  Before v3.0.0 version, I could simply use [Vimium](https://github.com/philc/vimium) or [Chromium-vim](https://github.com/1995eaton/chromium-vim) hide Octotree by press "f" on keyboard to simulate click on "Hide" button.

> In "Vimium" or "Chromium-vim", ["f"](https://github.com/philc/vimium/blame/3ed13fa2371910a0826abb100fea0959edb703e4/README.md#L40) means   open a link in the current tab

And in v3.0.0, "Vimium" and "Chromevim" even failed to activate Octotree, I would have to move my hand from keyboard to mouse and click(or hover) on "Octotree>" button to activate Octotree.

Not that important but affect, in v3.0.0 when Octotree is activated, search bar will be blocked.

**Comment by buunguyen** [comment]
@DarcySail doesn't the short key option of Octotree work? You can press key to open or hide the tree with a key.

Anyway, you can always download older version here: https://github.com/ovity/octotree/releases.
Look into the dist directory and load to your specific browser.

Hope you'll consider v3 later as we can't guarantee v2 will work forever should GitHub changes something that breaks it (e.g. the DOM changes).

**Comment by DarcySail** [comment]
@nphi @buunguyen
Great! Keymaster hotkeys works for me. Thanks for your excellent work:)

(But I still hope you could make "Octotree>" button works for "Vimium" and "Chromium-vim", which is more intuitive for Vim user)

**Comment by buunguyen** [comment]
@DarcySail thanks for the suggestion! Our team will look into it, but if you know what it takes to support Vimium (i.e. add some attribute to the button or what?), feel free to let us know, would save us some research time.

**Comment by DarcySail** [comment]
@buunguyen
I simplely tried adding keyword "button" to `<div>` or `<span>` "class" attribution, and it works.

Before:
```css
<span>Octotree</span>
```
After:
```css
<span class="button">Octotree</span>
```

> https://stackoverflow.com/questions/53918093/how-can-i-make-my-element-clickable-for-vimium
> https://github.com/philc/vimium/issues/1091
> https://github.com/philc/vimium/issues/425

Now, we still lack the "Hide" button. But the decision is on you:)
(I know adding a button isn't an easy decision)
