### ISSUE TITLE
chrome doesn't allow host : can't read site data

### ISSUE THREAD

**Issue by paka99** [ovity/octotree#676]
### Description
After major upgrade(to 3.x.x), the extension can't read my enterprise github source tree.
At chrome settings, although configure site access domain ( add 'github.my-enterprise.com' ), it still doesn't read data.

### Environment (if bug)
* Octotree version: 3.0.2
* Browser & version: 73.0.3683.103
* OS & version: Mac OS 10.14.3

**Comment by buunguyen** [comment]
Hi, Octotree 3.0 no longer supports GitHub Enterprise, please see the [release note](https://github.com/ovity/octotree/blob/v3/HISTORY.md#v300) for more information.

While we encourage you to consider Octotree Pro, you can always download and use an older version of Octotree that supports GHE (any 2.x will work): https://github.com/ovity/octotree/releases. Download, look into the dist directory, then load the extension to your specific browser.
