### ISSUE TITLE
Keep open & consume space?

### ISSUE THREAD

**Issue by lolmaus** [ovity/octotree#677]
I've been using Octotree with [GitHub Wide userstyle](https://userstyles.org/styles/108591/github-wide). It was very convenient on wide screens.

Now Octotree is constantly collapsed. I'm unable to use Vimium to navigate it.

Also, when expanded by hand, it takes time to load content whereas previously it would load content eagerly and save my time.

Finally, it overlaps GitHub UI.

The usability of the extension has dropped to a point I'm considering uninstalling it.

Please add an option for Octotree to start open and consume page width, so that it does not overlap GitHub UI.

**Comment by nphi** [comment]
@lolmaus !

Thanks for your constructive feedback. Regarding to the navigation issue, have you tried the shortkeys option of the Octotree ? For the UI overlap, could you give us a screenshot so that we could think a way to fix it. 

Many Thanks.

**Comment by buunguyen** [comment]
> Finally, it overlaps GitHub UI.

If you pin the tree, it won't overlap. In floating mode, which is supposed to be temporary for users to quickly click a file, it doesn't push the content. I know the changes are very different from the old behavior, but we hope eventually most users will like it more as it's more flexible to specific use cases. We'll reconsider the decision if enough users push back to the change ;).

**Comment by lolmaus** [comment]
Ah, that does it. I was looking for that option in settings. Thx!
