### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by zethra** [ovity/octotree#681]
### Description
The icons are not displaying properly.  It might be because it seems like it's trying to load from `chome-extension://` instead of `moz-extension://`

### Environment (if bug)

* Octotree version: 3.0.5
* Browser & version: Mozilla Firefox 66.0.3
* OS & version: Elementary OS (Linux) 5 
![Screenshot from 2019-04-17 12-55-48](https://user-images.githubusercontent.com/6034238/56306369-46666f00-6110-11e9-9adf-d532a47a3e72.png)

* Console error log below this line
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://c46c5769-4f35-4c0e-a136-d000b67304df/fonts/fontawesome.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://c46c5769-4f35-4c0e-a136-d000b67304df/fonts/octicons.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://c46c5769-4f35-4c0e-a136-d000b67304df/fonts/file-icons.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://c46c5769-4f35-4c0e-a136-d000b67304df/fonts/devopicons.woff2 (“font-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at chrome-extension://c46c5769-4f35-4c0e-a136-d000b67304df/fonts/mfixx.woff2 (“font-src”).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.github.com/_private/browser/stats. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.github.com/_private/browser/stats. (Reason: CORS request did not succeed).[Learn More]
Empty string passed to getElementById().

**Comment by buunguyen** [comment]
This was fixed in the latest version. Please try again.
