### ISSUE TITLE
The search box gets covered

### ISSUE THREAD

**Issue by ahatzz11** [ovity/octotree#682]
### Description
When making a search on github the octotree panel blocks the search bar

Gif here: http://www.giphy.com/gifs/dz0N1x0bN9YH8lASIu

### Environment (if bug)

* Octotree version: 3.0.4
* Browser & version: Chrome Version 74.0.3729.75 
* OS & version: MacOS 10.14.3 
* Console error log below this line

**Comment by nphi** [comment]
&ahatzz11 , thanks for reporting the issue. I’d love the gif attachment which make us understand the problem quickly and easily.  I will work on it and fix it soon.

**Comment by Hongarc** [comment]
+1
This bug makes me prefer the old version by this version.

**Comment by nphi** [comment]
@buunguyen, this PR is fixed

**Comment by Hongarc** [comment]
![image](https://user-images.githubusercontent.com/19208123/56851434-7ea05580-6939-11e9-8aad-57a3d320f7c7.png)
![image](https://user-images.githubusercontent.com/19208123/56851438-8cee7180-6939-11e9-8672-1cc42fe8e987.png)
@nphi Thank for this fix, but it doesn't the same margin when I change the size of panel

**Comment by buunguyen** [comment]
@Hongarc :))), your attention to detail is really great, I didn't notice until you pointed out. We probably deal with this later as it's not super critical I think.
