### ISSUE TITLE
Request on demand result click delay

### ISSUE THREAD

**Issue by exotfboy** [ovity/octotree#683]
After update to 3.0.4, I found that the click operation have a obvious delay, then I make it clear that octotree will request for child nodes when click a node even the  `Load entire tree at once`  is checked through chrome dev-tool.

Check this [repo](https://github.com/JetBrains/kotlin)

**Comment by buunguyen** [comment]
Hi, when a repo is too large to load in full, Octotree automatically switches to load it lazily. Previously, it shows an error and requires users to check off the full-load option, which is not great UX.
