### ISSUE TITLE
Octotree thinks topics are repositories

### ISSUE THREAD

**Issue by oganm** [ovity/octotree#685]
### Description
If you visit a topic link, such as https://github.com/topics/atom, the octotree will complain about this being a private repository that it's unable to access. Ideally, it should just make itself scarce.

### Environment

* Octotree version:3.0.4
* Browser & version: Chrome 72.0.3626.121 (Official Build) (64-bit)
* OS & version: Ubuntu 16.04

![Selection_279](https://user-images.githubusercontent.com/6352379/56396386-602cb280-61f3-11e9-8582-3350fefcec72.png)

**Comment by nphi** [comment]
@oganm, 
Thanks for letting us know this. I totally agree with you that it shouldn't appear in topics. We will plan working on this matter. Good call !!!

**Comment by buunguyen** [comment]
Fixed and should be available in store shortly.
