### ISSUE TITLE
Vivaldi Enterprise Support

### ISSUE THREAD

**Issue by rjhilgefort** [ovity/octotree#689]
### Description

Everything mostly works on Vivaldi, but I can't enable enterprise support. I just purchased pro for this feature. I have to use Vivaldi because of restrictions on Chrome that my company enforces. When I right click on the extension, I don't see an option to support this domain. It was working prior to the switch over to the standard/pro extensions.

**Comment by nphi** [comment]
@rjhilgefort , 

Thanks for supporting Octotree. We will investigate on this matter and come back to you ASAP.

**Comment by crashbell** [comment]
@rjhilgefort I have found a workaround to enable enterprise support on Vivaldi.

* Go to the Extension page
* Enable Developer mode
![Vivaldi-octotree-extension](https://user-images.githubusercontent.com/810139/57116596-62107d00-6d80-11e9-8579-0637bad3c574.png)

* Click on background page link
* In the new console, use the code: `chrome.permissions.request({origins: ["https://your-domain.com/*"]})`
* A new dialog will appear and you just confirm it

Hope it would help.

**Comment by buunguyen** [comment]
We'll revisit this to find a fix later.

**Comment by rjhilgefort** [comment]
@crashbell Thanks for the workaround! That worked great!
