### ISSUE TITLE
Crash if LocalStorage is full

### ISSUE THREAD

**Issue by krizka** [ovity/octotree#690]
### Description
Crashed if github localstorage is full. Tried to run extension first time today, and on my try to get it out from sidebar, "Octotree >" label just disappeared, "what a troll", I thought. 
I look down to the line with error here (`hugeRepos` was `undefined`): 
```
if (hugeRepos[key]) {
      // Update the last load time of the repo
```
I tried to call the line with `this.store.set(STORE.HUGE_REPOS, hugeRepos);` and that said, LS is full. So things become good after I cleared it.

### Environment (if bug)
MacOSX Chrome

* Octotree version:
3.0.0
* Browser & version:
Chrome 73.0.3683.103 (Official Build) (64-bit)
* OS & version:
Mac OSX 10.14
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by nphi** [comment]
@krizka,
Thanks for reporting the issue in such detail. I wish everyone would do the same like you when reporting the bug. :)

We will plan fixing the bug. Really appreciate your time and effort.

**Comment by buunguyen** [comment]
We change the approach to using storage & cache. Hope this won't happen, if it does, please open a new issue. Thank you.
