### ISSUE TITLE
Lack of padding between octotree and GH logo

### ISSUE THREAD

**Issue by jaymickey** [ovity/octotree#691]
Octotree and the GH logo are touching each other inappropriately.

### Environment (if bug)

* Octotree version: 3.0.6
* Browser & version: Chrome 73.0.3683.103
* OS & version: MacOS 10.14.4
* Screenshot, if any (drag an image here): 
![image](https://user-images.githubusercontent.com/7720995/56443730-bf6eed80-62ed-11e9-9081-0a22c04f1582.png)

**Comment by nphi** [comment]
@jaymickey,

Thanks for your report. It seems the issue only happens on the large screen. We will plan fixing the issue.

**Comment by nphi** [comment]
@buunguyen, this issue is fixed
