### ISSUE TITLE
Sidebar hides itself just after appearing

### ISSUE THREAD

**Issue by fiatjaf** [ovity/octotree#694]
### Description
I click on the sidebaar (set it to only appear on click), it shows up and then instantly hides itself again.

### Environment (if bug)

* Octotree version: 3.0.6
* Browser & version: Firefox 66.0.3
* OS & version: Ubuntu 17.10
* Screenshot, if any: 
![output](https://user-images.githubusercontent.com/1653275/56499976-4b943700-64df-11e9-99c4-0e5d9e23cd36.gif)

* Console error log below this line: None

**Comment by nphi** [comment]
@fiatjaf ! Thanks for reporting the issue. It seems like if the mouse doesn't move, it would cause the bug. I will try to fix it soon. Really appreciate the informative GIF.

**Comment by nphi** [comment]
@buunguyen, this issue is fixed.
