### ISSUE TITLE
Octotree thinks releases are private repos

### ISSUE THREAD

**Issue by tgdn** [ovity/octotree#697]
### Description
See title and screenshot.

### Environment (if bug)

* Octotree version: 3.0.6
* Browser & version: Chrome 73.0.3683.103
* OS & version: macOS Mojave 10.14 (18A391)
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/480050/56563971-f7ec2100-65a4-11e9-9f5f-12a8d88bd923.png)

* Console error log below this line

**Comment by nphi** [comment]
@tgdn 

In order to avoid Octotree displaying in non-code page, you could uncheck the option `Show in non-code pages` in settings. It would no longer show the tree in the non code page (e.g Release page)

Thanks for reporting this.
