### ISSUE TITLE
Octotree Free: can not activated

### ISSUE THREAD

**Issue by muescha** [ovity/octotree#700]
### Description

after installing octotree i can not activate the free subscription

- in octotree i see only this message:

```
You don't have an active subscription. Please go to our website to subscribe. Once finished, click here to reload.
```
- the https://www.octotree.io/subscription redirects directly to https://www.octotree.io/checkout
- on subscription page there is no free plan to select

### Environment (if bug)

* Octotree version: Octotree Pro
* Browser & version: Chrome 73.0.3683.103
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
Hi Michael, Octotree Lite and Pro are separate extensions. You can download the free one here: https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US

**Comment by muescha** [comment]
this should be more clear on the homepage that i need separate chrome plugins
