### ISSUE TITLE
can not delete my octotree account

### ISSUE THREAD

**Issue by muescha** [ovity/octotree#701]
### Description

on website account page i miss the option to delete my account

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
This is something we plan to implement in the future. Thanks for reporting.

**Comment by AlexVasiluta** [comment]
Hello!

Has this situation changed? Have a nice day!
