### ISSUE TITLE
possible phising of my GitHub credentials with password manager

### ISSUE THREAD

**Issue by muescha** [ovity/octotree#702]
### Description

- when i a see login with the octotree pro
- i accidently hit the autofill login from 1password
- my github credentials are filled in and submitted to octotree
- my github password is not safe anymore

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
Hi. The authentication with Octotree backend is via HTTPS. In addition, we don't log or store data in the auth POST request.

**Comment by muescha** [comment]
you say its not logged - but you can if you will

i think there should be some hint or a warning popup after i hit the login button (or the auto submit of the form) to avoid this security hole sending my github credentials to an other party then the github. 

this additional popup would be more trustabe then just accepting any credentials.

**Comment by buunguyen** [comment]
In that case, I think you should change your password since you don't trust us anyway :). I don't think showing some sort of warning popup after a login is a useful pattern. Users should be mindful of what they enter into any login form on the internet.

**Comment by muescha** [comment]
> think you should change your password

changed it already.

> Users should be mindful of what they enter into any login form on the internet.

if the login form send-to domain and the domain of the page match: yes! i fully agree

but in this case it is **injected login form** into a different domain: no! i disagree

**Comment by buunguyen** [comment]
I hear ya. But to disrupt the login flow of all users seems a bit too much. It's quicker for a user to just change their password when they happen to user it accidentally.

**Comment by muescha** [comment]
then you should change the error message if a login fails to hint that they should change the github credentials now

**Comment by muescha** [comment]
all this leaves a bad taste of security hole with methods like a phishing vector

**Comment by buunguyen** [comment]
The login can fail for any reason. We don't know if it's because users enter the wrong credentials or because they mistakenly fill the wrong credentials via 1password or what not.
