### ISSUE TITLE
Can Mouse Move Off Without Shrinkage

### ISSUE THREAD

**Issue by kangaroo711** [ovity/octotree#712]
not bug 。just suggest;

**Comment by bitfishxyz** [comment]
Oh, man, I just come here for this feature.
Shrinkage after Mouse off is really annoy.

**Comment by buunguyen** [comment]
Does pinning the sidebar work?

**Comment by nphi** [comment]
@kangaroo711 , @bitfishxyz 

Thanks for your feedback. You might already know Octotree offers the hotkey to show and hide the sidebar. 

![Screen Shot 2019-05-01 at 10 23 50 PM](https://user-images.githubusercontent.com/8633840/57024849-d1db1680-6c5f-11e9-9ad2-b322aa029ba5.png)
 
I hope it would be helpful !
