### ISSUE TITLE
Feature suggestion: list of recently viewed files

### ISSUE THREAD

**Issue by armstrjare** [ovity/octotree#713]
I have a feature suggestion:

I'm often browsing code via Github and end up going back/forth between a handful files as I'm following control flow. For example, when I'm exploring a 3rd party framework or library and it's not worth the effort to clone the repo and open in an IDE. 

**Suggestion:** It would be very useful to have a list of, say, the 5 most recent opened files that I can click to toggle back/forth between (i.e. recent history) without having to remember what their names were to search them.

PS: Thank you so much for this extension, what a life changer!

**Comment by nphi** [comment]
Thanks for your feedback. It's a good idea.

**Comment by buunguyen** [comment]
This is now possible with the multi-tabs available for Pro subscription. And it's fast too. Closing this now.
