### ISSUE TITLE
Suggestion: Disable auto-open for private repositories

### ISSUE THREAD

**Issue by armstrjare** [ovity/octotree#714]
I have this pinned open by default, as it is amazing for browsing open source projects.

But I don't (yet, at least) want to configure access to private repositories.

It would be useful if the extension didn't auto-open (when pinned) for private repositories that it can't access. Ideally it should stick out of the way for private repos unless it has access, and be visible by default for public repos.

**Comment by buunguyen** [comment]
I think this is a bit of an edge case that is suitable for those who don't want to supply tokens. But for most users, it would be annoying.
