### ISSUE TITLE
cpu usage very high on specific website

### ISSUE THREAD

**Issue by dukeP** [ovity/octotree#716]
when I visit [this page](https://github.com/llh911001/mostly-adequate-guide-chinese/blob/master/ch2.md), the CPU usage reaches 100% +

ps. I had stopped all chrome extension except octotree

* Octotree version: 3.0.7
* Browser & version: chrome 74.0.3729.131
* OS & version: macOS 10.14.4 (18E226)

![屏幕快照 2019-05-08 10 12 45](https://user-images.githubusercontent.com/17401244/57344737-f44ac380-717a-11e9-9ad8-61fa13295e55.png)

**Comment by buunguyen** [comment]
We can't reproduce this. Are you sure this is Octotree's problem?

**Comment by dukeP** [comment]
sorry, my mistake. it's caused by Markdown Preview Plus
