### ISSUE TITLE
[feat]should store github access token in extension's localStorage

### ISSUE THREAD

**Issue by oe** [ovity/octotree#717]
### Description
every time after I clear chrome browser data, github access token  and every other settings are cleared at the same time.

extension‘s settings should store in extension's localStorage, aka save data via extension's `background.js`, to avoid settings been cleared when clearing browser data.

**Comment by nphi** [comment]
It’s an interesting idea. I think we could store insensitive setting data in the extension local storage. I would investigate more on this idea. Thanks for your suggestion.

**Comment by buunguyen** [comment]
Moved discussion here https://github.com/ovity/octotree/issues/763
