### ISSUE TITLE
Add Setting to Enable Dark Mode for Just the Sidebar

### ISSUE THREAD

**Issue by macintacos** [ovity/octotree#718]
As simple as the title suggests. I use (and prefer) [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US) for the GitHub UI itself, and would just like Octotree to supply a dark theme for just the sidebar (since, surprisingly, it doesn't appear that Dark Reader can do this on its own; is Octotree purposefully disallowing editing the CSS of the sidebar?). 

Enabling the dark theme on Octotree appears to override Dark Reader, and I don't want that.

**Comment by buunguyen** [comment]
One option we're exploring is providing multiple themes. Maybe that will make this unnecessary?

**Comment by macintacos** [comment]
@buunguyen if one of the themes is "only theme the sidebar", I'm all for it 😅

**Comment by buunguyen** [comment]
Fair enough 😀.

Is there any reason why you wouldn't entertain other themes? What if a theme looks just like Dark Reader?

**Comment by macintacos** [comment]
Dark Reader gives you enough knobs to turn that getting it exactly the way I have it is probably more trouble than it’s worth. I’d be happy with just the sidebar changing color to be “dark”, and I can deal with the default GitHub interface (since I already have that set up just fine).

I like Dark Reader since it applies to more than just GitHub, and turning it on/off means that all sites behave the way I expect. If I turn off Dark Reader but GitHub stays dark (because of Octotree), I think that’d bother me. The sidebar staying dark wouldn’t bother me nearly as much as the entire GitHub interface staying dark when I turned Dark Reader off. 

Hopefully that makes sense.

**Comment by buunguyen** [comment]
Done! v4.0.1 has a "Sidebar only" dark mode.

**Comment by macintacos** [comment]
@buunguyen I see that 4.0.1 is out for OctoTree; any idea when it'll be coming to the Pro version of the app? That's the one I run 🙂

**Comment by buunguyen** [comment]
Hi, please download Octotree and login using your existing account. Pro features are now included. We'll deprecate Octotree Pro soon.
