### ISSUE TITLE
Add Keyboard Shortcut for Searching in Octotree

### ISSUE THREAD

**Issue by macintacos** [ovity/octotree#719]
Any chance we could get a keyboard shortcut to quickly jump to the search bar in Octotree Pro? Currently it seems like the only capability behind shortcuts is the ability to pin/unpin the sidebar (which, personally, I almost never want to do).

**Comment by buunguyen** [comment]
@macintacos good idea. Curious why you never use the existing shortcut though. Is it because you have the sidebar always pinned? Or what is your workflow?

**Comment by macintacos** [comment]
@buunguyen yeah I just always keep it pinned 😄 if anything, I switch sides on it more than I close it (depending on what context the window is in, whether it's on the right/left side of my screen).

**Comment by muescha** [comment]
i would also like to have a shortcut for the Octrotree Search (pro and normal)

just now i need a mouseclick to jump into the search.

**Comment by muescha** [comment]
i changed to always unpin the octotree otherwise i get after some usages a api rate error and the tree is not populated anymore. when i unhide octotree then api calls only on demand i don't see the rate limit

**Comment by gwatts** [comment]
+1 on the request for a keyboard shortcut for search; i'm used to hitting "t" to bring up the file search in github directly, but tbh i'd rather map it to octotree!

**Comment by buunguyen** [comment]
Supported in Octotree 6. You can configure in Settings page.
