### ISSUE TITLE
Sometimes unable to scroll

### ISSUE THREAD

**Issue by cnwangjie** [ovity/octotree#722]
### Description
Sometimes unable to scroll octotree.It doesn't always appear.It doesn't seem to have any rules, but it will be annoying when it appears. Hope that it can be solved.

![GIFrecord_2019-05-19_163150](https://user-images.githubusercontent.com/7459652/57979710-336af580-7a54-11e9-9104-842ce8d46926.gif)

### Environment

* Octotree version: 3.0.7
* Browser & version: Chrome 76.0.3783.0 (Official Build) dev (64-bit) (it appears in before several versions)
* OS & version: both in my ArchLinux and Windows

**Comment by nphi** [comment]
Thanks for your report. It seems hard to reproduce the issue but I will try to investigate in the code.

**Comment by nphi** [comment]
Hi !

After investigation, it's not a concerning issue because it only occurs when the scroll in the tree at  the very top and you try to scroll up more. As a normal user, you don't scroll up anymore if you already are at the top. I think this ticket could be closed. 

Thanks for your cooperation.

**Comment by cnwangjie** [comment]
Hi, I found this happening on many other pages. And when I google this problem I found that some other users have the same problem. After I tried some other versions of Chrome, this problem seems to disappear. I think it may be a problem with Chrome.

Thank you for your great work on octotree.
