### ISSUE TITLE
except github common path like topics

### ISSUE THREAD

**Issue by pynixwang** [ovity/octotree#728]
### Description
now it deel with private repo.
### Environment (if bug)

* Octotree version: 3.0.7
* Browser & version:  Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
* OS & version: macOS 10.14.4 (18E226)
* Screenshot, if any (drag an image here)
<img width="675" alt="QQ20190524-122455@2x" src="https://user-images.githubusercontent.com/1189879/58302684-fb323100-7e1e-11e9-96d1-63f0608e276a.png">

* Console error log below this line

**Comment by buunguyen** [comment]
This was fixed in the latest version, should be available for update shortly.

**Comment by pynixwang** [comment]
update to 3.0.8 fixed.
