### ISSUE TITLE
Will the Cache be available soon?

### ISSUE THREAD

**Issue by gixid192** [ovity/octotree#729]
I create this with the hope to know the whether you guys will implement the cache feature.
This is not a new issue, it has been around since 2014 (#104) and several related issues (#442, #489...)

With the new Cache API, I implemented my own version in my machine, seems to work well.
Please let me know the status of this feature, I will try to make a PR if needed.

**Comment by buunguyen** [comment]
No, we have discussed internally several times but haven't really got the time to commit to it. The biggest challenge is, unsurprisingly, when to invalidate the cache, e.g. the user adds a file, another user deletes a file etc. Maybe it's an option with a warning like "You won't see changes by other users in real time" when enabling cache. Any idea is welcome and a PR will of course be totally awesome.

**Comment by gixid192** [comment]
I personally don't work in the case a repo needed to update that frequently.
I also don't work largely on Github so could you confirm if the case you mentioned is a normal case?

I originally wanted to create a PR but then because of #442, I don't think it's a PR, it's just my personal code, not sure if it fit for everyone.
My current idea is attach a hash `#frc=1` in the URL so that the cache will be forced to reload if needed.
The cache will also automatically reloaded if it is `old enough`, here I hard-coded this to 30 days period. This should be the option for users and even more robust, for each of the repos.

What do you think about my approach? Should I create a PR anyway? Or just share the code via pastebin?

**Comment by buunguyen** [comment]
Maybe a good compromise is providing an option, "Cache repositories for 7 days". When caching is enabled, there should be a way for users to force cache invalidation. Maybe add an icon in the header (before to settings) to reload repo if caching is enabled?

A PR would be nice.

**Comment by gixid192** [comment]
I just created a PR.
To be honest, the code need to much improve, I just want to demonstrate my idea.

**Comment by buunguyen** [comment]
@gixid192 	thanks for creating the PR! We'll review and let you know any feedback.
