### ISSUE TITLE
Sidebar broken on release pages

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#732]
### Description
On release pages the sidebar shows a message that it cannot access private repositories - even for public ones.

### Environment (if bug)

* Octotree version: 3.0.8
* Browser & version: Firefox 67.0
* OS & version: Ubuntu 16.04
![image](https://user-images.githubusercontent.com/424602/58340430-23845480-7e4c-11e9-9830-4eb3e96f974d.png)

---

Is the intended solution to disable the "Show in non-code pages" option or should it be disabled on such pages code-wise (like for reserved user/repo names)?

**Comment by nphi** [comment]
Thanks for reporting the issue. I have tried navigating to the release without access token in public repo but I couldn't reproduce the issue. It would be helpful if you could give us a screenshot.

Cheers

**Comment by jdreesen** [comment]
Strange, I'm not able to reproduce it anymore, too.

Closing for now.
