### ISSUE TITLE
Feature request: Maximum size to download entire tree

### ISSUE THREAD

**Issue by eloyekunle** [ovity/octotree#733]
### Description
Currently there is an option to either `Load entire tree at once` or not.
We can also add an option to enter maximum tree size to load at once. If the tree exceeds that size, then it is not loaded at once.

**Comment by buunguyen** [comment]
This is a good idea. Currently, Octotree automatically switches to lazy loading if a repo is too large to load. With that already built, do you think this feature is still important to have?

**Comment by eloyekunle** [comment]
> if a repo is too large to load
What's the current limit for what's too large?

I know know the exact size of https://github.com/kubernetes/kubernetes (that repository inspired this issue) but when I visit it takes a few seconds to load, and it doesn't switch to lazy loading.

However, if computing the tree size involves some technical complexity, then this feature isn't that important.

**Comment by buunguyen** [comment]
Sorry, because the auto lazy load is part of the performance pack (together with caching and per-repo lazy load), it's available with Pro subscription only. If you frequently work with large repositories, please consider subscribing to support us.
