### ISSUE TITLE
Scroll is terribly laggy in Safari with dark mode

### ISSUE THREAD

**Issue by aSapien** [ovity/octotree#734]
### Description

Octotree scroll is terribly slow in Safari with dark mode enabled, but no lag occurs when not in dark mode. The bug can be reproduced in any Github repo but it is much more noticeable in large repos, e.g [ProvingGround](https://github.com/siddhartha-gadgil/ProvingGround). Toggling the `Load entire tree at once` option doesn't seem to have any effect in this case. 

Reproduction Steps:
1. Open [ProvingGround](https://github.com/siddhartha-gadgil/ProvingGround) repo in Safari (or any other mid-large repo).
1. Toggle some folders to make the tree scrollable.
1. turn on dark mode
1. Scroll up & down
1. (To see the difference) Turn off dark mode and repeat the scrolling

### Environment (if bug)

* Octotree version: Octotree Pro 1.0.8
* Browser & version: Safari 12.1.1
* OS & version: MacOS Mojave 10.14.5
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
Can you try the latest version (4.x) and let us know if the issue still persists?

**Comment by aSapien** [comment]
@buunguyen Yes, the issue still reproduces on Safari with Octotree Pro 4.0.4

**Comment by joecorkerton** [comment]
I also have this on the latest version

**Comment by buunguyen** [comment]
Please try Octotree 6.1.0. It's just published to the store. I've tried the ProvingGround repo and scrolling is much better even in dark mode.
