### ISSUE TITLE
Cannot reply to comments

### ISSUE THREAD

**Issue by eboayue** [ovity/octotree#735]
### Description
Using Octotree Pro in Chrome with GitHub Enterprise, I find I cannot reply to comments on pull requests unless I disable the plugin. The "comment" button is there and can be clicked, but it does not submit the comment. When the plugin is disabled the button works as expected.

### Environment (if bug)
* Octotree version: 1.0.9
* Browser & version: Chrome Version 75.0.3770.80 (Official Build) (64-bit)
* OS & version: macOS 10.13.6
* Screenshot, if any (drag an image here): nothing to see, the "comment" button simply does nothing when clicked
* Console error log below this line

**Comment by buunguyen** [comment]
Can you double check that this is really caused by Octotree? I haven't got any issue working on PR with Octotree. If it is a bug, I'm sure many people would have reported it or vote up this issue.

**Comment by buunguyen** [comment]
If this still happens, please let contact us https://www.octotree.io/contact so that we can support.
