### ISSUE TITLE
Hide octotree on Market Place item pages

### ISSUE THREAD

**Issue by joedf** [ovity/octotree#736]
### Description
If you go to https://github.com/marketplace , octotree is hidden and that's fine. However if you go to a select item's page e.g. https://github.com/marketplace/codefactor or https://github.com/marketplace/vuegg you get "Error: Private repository" which is misleading.

### Environment

* Octotree version: 3.0.8
* Browser & version: Firefox v67.0.2 x64
* OS & version: Windows 10 Pro x64

**Comment by muescha** [comment]
also with the `apps` link: https://github.com/apps/tap-release

**Comment by buunguyen** [comment]
Fixed and should be available in store shortly

**Comment by joedf** [comment]
Great 👍
