### ISSUE TITLE
Extension becomes corrupt every couple days

### ISSUE THREAD

**Issue by ahatzz11** [ovity/octotree#740]
### Description

After a couple of days this extension ends up corrupted. I've also tried using this by itself in incognito over a couple of days and it always ends up in this corrupted state.

I never had this issue before upgrading to the pro version.

![image](https://user-images.githubusercontent.com/6256032/61133334-4534ac00-a48b-11e9-8aea-e752a0b2dde4.png)

### Environment (if bug)

* Octotree version: 1.0.9
* Browser & version: Chrome Version 76.0.3809.46 (Official Build) beta (64-bit)
* OS & version: mac mojave Version 10.14.3 (18D109)

**Comment by buunguyen** [comment]
Which browser is this?

**Comment by ahatzz11** [comment]
Oops forgot that in original post - chrome!

**Comment by buunguyen** [comment]
Thanks. This is very strange, I've never seen it before. Can you uninstall and reinstall it from the store to see if it happens again?

**Comment by ahatzz11** [comment]
@buunguyen It's happened twice since I've uninstalled/reinstalled.

**Comment by buunguyen** [comment]
Gonna close now. Please have released a new version. Don't know if it helps, but if you still encounter, please update.
