### ISSUE TITLE
Extension not working with GHE on Safari

### ISSUE THREAD

**Issue by rmbaad** [ovity/octotree#754]
### Description
Hello!
I use Safari and Github Enterprise, but Github works on custom domain. In extension's permissions I see this text "Can read ... github.com". 
Is Octotree works with custom domains?

### Environment (if bug)

* Octotree version:Octotree Pro 1.0.8 (latest from AppStore)
* Browser & version: Safari 12.1.1
* OS & version: macOS Mojave 10.14.5

Thank you.

**Comment by buunguyen** [comment]
Hi, Octotree Pro doesn't support GitHub Enterprise on Safari. Sorry about the inconvenience.
