### ISSUE TITLE
Extension not working in version 3.0.9

### ISSUE THREAD

**Issue by a631807682** [ovity/octotree#756]
### Description
It not thing to change when i use Octotree v3.0.9 to access to github, and no console error. 
After that i install v3.0.8, it work fine.

### Environment (if bug)

* Octotree version: 3.0.9
* Browser & version: Chrome 67
* OS & version: Win7
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
Thanks for reporting the issue. Indeed it happens on Windows, we only tested on OSX. 

I've just released a hot fix (v3.0.10). It should be available within the next couple of hours.
