### ISSUE TITLE
Octotree 3.0.9 no longer runs on Windows

### ISSUE THREAD

**Issue by xovel** [ovity/octotree#758]
### Description

Can not load the plugin.

### Environment (if bug)

* Octotree version: v3.0.9
* Browser & version: Chromium v70
* OS & version: Win10

*****************

```js
class _DeXss {
  constructor() {
    this._$dummyDiv = $('<div/>');
  }

  deXss = (str) => this._$dummyDiv.text(str).html();
}
```

Seems that my browser does support static property of classes.

**Comment by buunguyen** [comment]
Hi, we already fixed it in the latest version (3.0.10). Chrome should update the extension automatically, if not, please uninstall and re-install. (Gonna leave this issue open this week in case others haven't updated.)
