### ISSUE TITLE
Octotree tab covers GitHub Actions UI

### ISSUE THREAD

**Issue by tedmiston** [ovity/octotree#768]
### Description

In the [GitHub Actions](https://github.com/features/actions) Beta, the Octotree tab covers up a critical part of the UI which shows the name of the workflow, the git event, and the build steps.

Resizing the window does not really help as Octotree stays in a spot that covers underlying content.

Unlike most other GitHub pages, the Actions UI is 100% full width vs a fixed width container.

A similar issue covering information also occurs on [GitHub Project](https://help.github.com/en/articles/about-project-boards) pages.

### Environment (if bug)

* Octotree version: 3.0.10
* Browser & version: Chromium 74
* OS & version: Debian Buster
* Screenshot, if any ![octotree](https://user-images.githubusercontent.com/366688/63820362-f3e75b80-c916-11e9-87c4-660da4dae5f7.png)
* Console error log below this line

**Comment by nphi** [comment]
Hi @tedmiston ,

You could go to Octotree settings and enable Octotree only in Code and Pull Request. For other pages, Octotree would be hidden.

![Screen Shot 2019-08-28 at 11 53 19 PM](https://user-images.githubusercontent.com/8633840/63876227-4431ec80-c9ef-11e9-9df0-be895fb13b02.png)

I hope it would be helpful !

**Comment by buunguyen** [comment]
We haven't come up with any better solution. For now, either right-docking or set Octotree to display in code & pull-request pages only would be the solution.
