### ISSUE TITLE
modify password

### ISSUE THREAD

**Issue by syshlang** [ovity/octotree#772]
i  forget my password ,but it can not modify by https://www.octotree.io/forgot-password,An internal server error occurred when i click button Send Instructions

**Comment by buunguyen** [comment]
Thanks for reporting the issue. We have fixed it. Please let us know if you have any other issue.

**Comment by syshlang** [comment]
all is ok，thank  you  very much！

**Comment by syshlang** [comment]
i reset my password，but i can not login when i input valid users and passwords.message:Invalid email and/or password .

**Comment by syshlang** [comment]
> 
> 
> i reset my password，but i can not login when i input valid users and passwords.message:Invalid email and/or password .



> 
> 
> Thanks for reporting the issue. We have fixed it. Please let us know if you have any other issue.

thank you  for your help!i reset my password，but i can not login when i input valid users and passwords.message:Invalid email and/or password .

**Comment by zzzhy** [comment]
situation keeps still
