### ISSUE TITLE
Feature Suggestion: Collapse/Expand Files Button

### ISSUE THREAD

**Issue by sharynneazhar** [ovity/octotree#774]
### Description

Hey! I've been using Octotree for a year and I'm loving it. It helps so much navigating GIthub especially with VERY large projects. 

It would be very useful to have a collapse/expand button for the files. VSCode has one and it's an amazing tool to be able to just collapse everything if I need to just start at the top. 

![Aug-30-2019 14-38-10](https://user-images.githubusercontent.com/10108593/64047222-d0e5c300-cb33-11e9-8fd4-8871cc70cf96.gif)

**Comment by stevennoto** [comment]
+1 to this. This was also discussed in #470. I will see if I can check this out this month, although the code has changed a bit since I last worked on the extension.

**Comment by sharynneazhar** [comment]
Hey @stevennoto. Not sure if you had a chance to look at this. Since it's been a while, I went ahead and implemented this feature. 🙂
