### ISSUE TITLE
Twillight dark theme white places

### ISSUE THREAD

**Issue by anpryl** [ovity/octotree#778]
Twillight dark theme has multiple places with white colors:
Pull request review:
![image](https://user-images.githubusercontent.com/5327697/64100845-2c52c380-cd75-11e9-9e28-5ed937b795eb.png)
Main page, Activity window:
![image](https://user-images.githubusercontent.com/5327697/64101047-a5521b00-cd75-11e9-9543-3ce0f3aafbbf.png)

**Comment by buunguyen** [comment]
Fixed in 2.0.2. Should be available in the extension stores soon.
