### ISSUE TITLE
GitHub issue text not readable in dark mode

### ISSUE THREAD

**Issue by desilinguist** [ovity/octotree#785]
### Description
The text in the various boxes in the issues page seems to be using a very dark font and is not really readable.

### Environment (if bug)

* Octotree Pro version: 2.0.1
* Browser & version: Safari 12.1.2
* OS & version: macOS 10.14.6
* Screenshot, if any 
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/161680/64449670-7d80f100-d0ae-11e9-866d-3298a0b7b271.png">

* Console error log below this line

**Comment by steshaw** [comment]
Same problem here (Firefox and Chrome).

Could the old dark theme be one of the new choices?

**Comment by buunguyen** [comment]
The old dark theme is github-dark, it's one of the choices.

We'll fix this asap.

**Comment by steshaw** [comment]
@buunguyen thanks, I thought it might be github-dark but I couldn't recall the bright redish colours.

![image](https://user-images.githubusercontent.com/45735/64464209-7a3b4300-d14a-11e9-9a40-eb94a5b642a5.png)

![image](https://user-images.githubusercontent.com/45735/64464220-84f5d800-d14a-11e9-9c0c-bee30f0944e9.png)

**Comment by buunguyen** [comment]
Yeah, we changed the accent color :)

**Comment by buunguyen** [comment]
Fixed in 2.0.2. Should be available in the extension stores soon.
