### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by UltramanTIGA** [ovity/octotree#786]
I have registered by gmail and verify email. But I can't log in with my email and password.
Then I try to change password. It showed I have changed success.But I still can't log in to use octoree pro

**Comment by buunguyen** [comment]
What error do you see in the console?

**Comment by UltramanTIGA** [comment]
> What error do you see in the console?

Invalid email and/or password

**Comment by buunguyen** [comment]
Maybe type password somewhere so you can see it and paste in? Sorry, but I don't know how to help. The login still works fine.

**Comment by UltramanTIGA** [comment]
> Maybe type password somewhere so you can see it and paste in? Sorry, but I don't know how to help. The login still works fine.

Well.I have reseted password again.And then copy and paste email address, password, still not work both in website and plugin. Maybe your system isn't support gmail or there have something wrong with the reset password? 
Unfortunately.I have to give it up.

**Comment by buunguyen** [comment]
That's super strange. Gmail works just fine for us. We have lots of customers using gmail. Anyway, I honestly I have clue.
