### ISSUE TITLE
New Dark Modes Class

### ISSUE THREAD

**Issue by macintacos** [ovity/octotree#792]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:
* Browser & version:
* OS & version:
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by buunguyen** [comment]
Sorry, what about this?

**Comment by macintacos** [comment]
Strange, I didn't think that I actually opened this, I started drafting and then closed the tab...will close this out, sorry for the confusion.
