### ISSUE TITLE
Bug: Octotree appears on a page that is not a repository

### ISSUE THREAD

**Issue by fjoshuajr** [ovity/octotree#797]
### Description
Octotree appears on a page that is not a repository, it shouldn't.

Steps:
- Visit any customer stories page on https://github.com/customer-stories (e.g. https://github.com/customer-stories/zendesk)

![image](https://user-images.githubusercontent.com/12100397/64822940-78440a80-d5b6-11e9-92d8-40562bc8fbda.png)

Adding `customer-stories` to a whitelist should solve the problem. Similar to #685

### Environment
* Octotree version: 3.0.10
* Browser & version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* OS & version: Windows 10

**Comment by stevennoto** [comment]
I opened a PR to address this. I can also alphabetize the list of excluded URL slugs if desired. Thanks!

**Comment by fjoshuajr** [comment]
Cool!

**Comment by buunguyen** [comment]
I believed this was fixed in recent releases. Gonna close.
