### ISSUE TITLE
Poor readability when dark mode enabled

### ISSUE THREAD

**Issue by desilinguist** [ovity/octotree#799]
### Description
Thank you for fixing a previous issue regarding comment readability in dark mode. However, several readability issues still remain (see attached screenshots):

1. The editor for the text when filing an issue is very very faint and not readable (screenshot 1).
2. The title when filing a new issue (screenshot 1).
3. The tabs at the top ("Code", "Pull requests", etc.) are barely visible as are the various text editor controls in the issue text editor (screenshot 1).
4. The buttons at the top ("Used by", "Watch", etc.) are pretty much invisible (screenshot 1).
5. In the PR view, the tabs are again not readable and neither is monospaced text (screenshot 2).
6. Comments submitted as part of reviews are still too grey to be readable and so is the number of reviewers, pending reviews etc. (screenshot 3).

Would it be possible to have a setting that restricts the dark mode _only_ to the Octotree sidebar and not to the whole GitHub site? I have another dark mode extension that seems to work quite well with the GitHub site and I can just use that and Octotree.io together?

### Environment (if bug)

* Octotree version: 2.0.3 (app store)
* Browser & version: Safari 12.1.2
* OS & version: macOS 10.14.6
* Screenshot, if any (drag an image here)
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/161680/64960887-4656d080-d862-11e9-8ca2-83142406cec4.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/161680/64961137-c9782680-d862-11e9-8300-358268111751.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/161680/64961185-e280d780-d862-11e9-89ec-0251d004f568.png">

* Console error log below this line

**Comment by buunguyen** [comment]
Thanks for reporting. Safari doesn't behave like other browsers, causing quite a bit of a problem. We'll fix this ASAP. We'll also consider the suggestion of adding a special "sidebar-only" theme.

**Comment by davelaflam** [comment]
The original dark theme you had before these changes worked great. Can we bring that one back or use that as an example for these newer dark themes?

**Comment by davelaflam** [comment]
any update yet?

**Comment by buunguyen** [comment]
@davelaflam we're addressing these Safari bugs as well as building a sidebar-only theme (a common request, not just in this thread), among many other things. Give us a few weeks.

**Comment by davelaflam** [comment]
@buunguyen that sounds great, can't wait to see it. Thank you for the update and all the hard work the team puts into making OctoTree awesome!

**Comment by buunguyen** [comment]
Sorry for taking long. This issue was fixed in the latest version. Also introduce a "Sidebar-only" theme, which only puts the Octotree sidebar in dark mode.
