### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by nugend** [ovity/octotree#8]
It'd be nice! You could add an option in the plugin about which sites to request permissions for maybe?

I actually don't know if that's possible.

**Comment by smitthakkar1** [comment]
@buunguyen  I can't use it for Github Enterprise.

**Comment by dstivanov** [comment]
@buunguyen Same here, cannot see the tree for corporate github repository. In the options I have enabled "Allow on all websites". Am I overlooking something?

**Comment by eligrey** [comment]
This issue was intentionally unfixed by the rent-seeking maintainer as a funding mechanism. If you wish to re-fix GitHub Enterprise support, undo and attempt to re-integrate these changes: https://github.com/ovity/octotree/commit/67c906004af1993bf9ae87f19e052323ef0a80dd
