### ISSUE TITLE
Integrate with GitHub's sticky headers

### ISSUE THREAD

**Issue by waldyrious** [ovity/octotree#802]
I love the idea and implementation of this extension, but currently it doesn't play along well with ~~the improvements done by [Refined Github](https://github.com/sindresorhus/refined-github#readme) to~~ the pull request page, in particular the sticky header. See for example one of the PRs in this repo:

Initial view:
![Screenshot_2019-09-27 ovity octotree](https://user-images.githubusercontent.com/478237/65774218-b9e7c000-e135-11e9-88bb-d397c4616b58.png)

After scrolling down a bit (~~Refined~~ GitHub introduces a sticky header):
![Screenshot_2019-09-27 ovity octotree(1)](https://user-images.githubusercontent.com/478237/65774219-ba805680-e135-11e9-91d5-82f596f95bbc.png)

**Comment by buunguyen** [comment]
Can you explain this a bit more? What do you mean by "not playing" well? What do you expect Octotree to do?

**Comment by waldyrious** [comment]
Ah, sorry, I just tested again and realized that this is actually native GitHub functionality, not a Refined GitHub feature. I've edited the initial comment accordingly.

What I would expect is for Octotree to adjust the sidebar's header height to match github's sticky header that shows up when one scrolls down, the same way the initial header height has the exact same height as github's own dark header bar (as shown in the first screenshot above).

The initial state seems intentional, and well-designed; but in the scrolled state, because the difference in height is so small, it looks misaligned, and seems more like an overlook than a deliberate choice.

**Comment by muescha** [comment]
i think you mean this part:

![Bildschirmfoto 2019-11-26 um 21 38 25](https://user-images.githubusercontent.com/184316/69670879-33981d80-1095-11ea-9dd4-5a74f08d6ba5.png)


BTW: this is also on the issues page...

**Comment by muescha** [comment]
if you would do a refinement and switch to a smaller header when the sticky header is visible then you should add a margin to the treeview so that the tree not jump around

**Comment by buunguyen** [comment]
So we discussed and thought it's better to keep the sidebar consistent instead of feeling like jumping around. Not worth it.
