### ISSUE TITLE
Feature request add button to scroll octotree to an opened file

### ISSUE THREAD

**Issue by kortov** [ovity/octotree#814]
When you open a big repo like [eugenep tutorials](https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-data-jpa-2)
you have to scroll view down to the file
I'd like to have a button near settings which scrolls you down to the file

**Comment by buunguyen** [comment]
In 6.0.1, the tree will scroll automatically the first time you load. I suppose that's sufficient for most use case.
