### ISSUE TITLE
Sidebar visibility while loading

### ISSUE THREAD

**Issue by a1tus** [ovity/octotree#82]
Hi. I'm using chrome plugin.
When you enter the page where it must be shown (opened by default) first u see initial github page and then after a few seconds sidebar appears. But when it's happening we have a page layout "jump" to the right which is quite annoying.
I would suggest to make sidebar visible from the very begginning of page loading (when its state is 'opened', of course) and just show some small loading animation in it.
Great extension, thanks.

**Comment by OliverJAsh** [comment]
This is still an issue for users who have the sidebar pinned. Would it be possible for Octotree to avoid this jump during page load?

**Comment by buunguyen** [comment]
@OliverJAsh should have been fixed in 5.2.0, but only if there's available space . If you have a small screen and Octotree overlaps GitHub content, then shifting is inevitable.

**Comment by OliverJAsh** [comment]
@buunguyen This is the shifting I was talking about. Happens on 5.2.0 and on a wide viewport. I was hoping Octotree would be able to reserve space for the pinned sidebar before it loads, so there's no jump.

![Screen Recording 2020-06-26 at 20 36 37](https://user-images.githubusercontent.com/921609/85894590-f5aad580-b7ec-11ea-93e2-e3dfa9092967.gif)

**Comment by buunguyen** [comment]
Thanks for posting. We'll figure something out.
