### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by sharynneazhar** [ovity/octotree#834]
### Description
As a new contributor to the project, I had to do a little digging on how to get started. It would be helpful to have a contributing guide or a section in the README on how to build/run the extension. 

(That is, if you intend to open-source)

**Comment by sharynneazhar** [comment]
@buunguyen  I just realized this is the free version. I personally use Octotree Pro. Are new feature PRs contributed to this version exported to the pro version as well?

**Comment by buunguyen** [comment]
The full Octotree version (Pro) is a superset of this open-source version. In other words, anything in this version is available in the full version. We rarely accept contributions but when we do, it comes without saying they're available for free in both versions.
