### ISSUE TITLE
Suggestion to add debounce / delay to panel activation

### ISSUE THREAD

**Issue by mattmazzola** [ovity/octotree#841]
### Description
Currently it seems there is no or very minimal delay between when your mouse hovers over the Octotree tab and the panel sliding open.  

In my case i'm working on two monitors (with github on the right monitor) so the mouse can often come from the left of this tab. I'm not reaching for the tab to imply octotree intent but passing over the tab for something else beyond it.

This still causes octotree to open and either obscures the target I was moving towards or at minimum is a general visual distraction / disturbance.

![image](http://g.recordit.co/I9LwmF01N8.gif)

### Environment (if bug)

* Octotree version: 3.0.10
* Browser & version: Chrome - Version 78.0.3904.97 (Official Build) (64-bit)
* OS & version: Windows 10 - Version	10.0.18363 Build 18363
* Screenshot, if any (drag an image here) https://recordit.co/I9LwmF01N8
* Console error log below this line

**Comment by buunguyen** [comment]
As a temp fix, I think you can uncheck "Show sidebar on hover". Then you need to explicitly click the button to open Octotree.

**Comment by xgdgsc** [comment]
I find it still appear with that option disabled when mouse is at left edge of window.  Is it possible to disable edge hover alltogether?

**Comment by buunguyen** [comment]
Mouse over edge should not trigger any more due to some fixes we add in Octotree 6. If you want to turn it off, please uncheck "Show sidebar on hover"
