### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by z2058550226** [ovity/octotree#843]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

Cannot connect to website. If your network connection to this website is fine, maybe there is an outage of the API. Please try again later.

I try to regenerate the token, but it doesn't work.
### Environment (if bug)

* Octotree version:last version
* Browser & version: chrome 78.0.3904.97
* OS & version: mac os 10.15.1
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/22285965/69205427-e5f74e80-0b84-11ea-90a0-51aec5f55c29.png)
* Console error log below this line
![image](https://user-images.githubusercontent.com/22285965/69205478-0cb58500-0b85-11ea-9d13-2be3cfe9d275.png)

**Comment by buunguyen** [comment]
This is likely a temporary API outage.

**Comment by ManiuLtd** [comment]
me too
