### ISSUE TITLE
combine with https://github.com/pomber/git-history, when click a file?

### ISSUE THREAD

**Issue by zhangenming** [ovity/octotree#848]

**Comment by buunguyen** [comment]
Can you explain a bit more?

**Comment by zhangenming** [comment]
I just wrote one on the spur of the moment
// ==UserScript==
// @name         GITHUB 打开切换 githistory.xyz
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://githistory.xyz/facebook/react/blob/master/.prettierrc.js
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    if(location.host === 'github.com' && location.pathname.split('/').pop().includes('.')){
        location.host = 'githistory.xyz'
    }
    // Your code here...
})();
