### ISSUE TITLE
Firefox Octotree Token State

### ISSUE THREAD

**Issue by pryorda** [ovity/octotree#851]
### Description
When using octotree, in firefox, with private org repos you will eventually get prompted for the token and will have to reenter it.

### Environment (if bug)

* Octotree version: 4.0.4
* Browser & version: FF  71.0
* OS & version: Mac 10.15.1
* Screenshot, if any (drag an image here)
<img width="328" alt="image" src="https://user-images.githubusercontent.com/5644316/70172543-1ca58c80-168e-11ea-9a7c-b6b7467a2195.png">
* Console error log below this line

**Comment by buunguyen** [comment]
You mean you already provide the token, but once in a while Octotree will re-prompt for it? That's quite strange. More info to help us reproduce would be great. For examples:

* How often is the re-prompt?
* Beside the token, do other options reset/disappear too? Or just the token?
* Did you happen to reinstall the extension by any chance? Or clean cookies/local storage?

**Comment by pryorda** [comment]
Thanks for responding! It does it after about 5-10 minutes or somethings browsing in and out of org projects to personal etc. Just the token. I've only reinstalled or cleaned cookies to try and fix the issue.

**Comment by buunguyen** [comment]
Just to confirm, when that prompt is shown, when you click Settings, does it still show the token in the settings screen? Or the textbox is empty?

**Comment by pryorda** [comment]
@buunguyen The screenshot in the op is what is shown and it is blank when you return to the settings.

**Comment by pryorda** [comment]
Any updates on this? I really wanted to use this, but if the token is always going to get lost in firefox I will have to move on.

**Comment by buunguyen** [comment]
We changed to use browser.sync storage. Available in 5.0. Hope that would fix this issue.
