### ISSUE TITLE
Error: GitHub API rate limit

### ISSUE THREAD

**Issue by hzb** [ovity/octotree#855]
### Description
I am not use GitHub often, but I always get error with information

```
You have exceeded the GitHub API rate limit. To continue using Octotree, you need to provide a GitHub access token. Please go to Settings and enter a token.
```

From the GitHub API doc [rate-limiting](https://developer.github.com/v3/#rate-limiting), I can make up to 5000 requests per hour, but actually I only make less than 100 requests per hour.

### Environment (if bug)

* Octotree version: 4.0.4
* Browser & version: Firefox 71.0 (64-bit)
* OS & version: macOS 10.15.1 (19B88)
* Screenshot, if any (drag an image here)
![error](https://user-images.githubusercontent.com/535675/70628958-19009f80-1c64-11ea-971c-e11079b0b67e.png)
* Console error log below this line

**Comment by buunguyen** [comment]
Note that 5000 is only when you authenticated, i.e. providing the access token.

**Comment by hzb** [comment]
Of course, I provided the access token, but each time I open GitHub, this error will show again.

**Comment by buunguyen** [comment]
Hmm, if you provide token, shouldn't run into limit that's easily. Can you check XHR request to see if the bearer header is sent with the correct token and the XHR response to see if the error returned by GitHub is indeed about API rate limit?

**Comment by hzb** [comment]
So interesting to reproduce:
1. Provide access token, and octotree works well.
2. Open a repositories list, such as https://github.com/buunguyen?tab=repositories
3. Open some repositories via Opening link in New Tab (This step is very important, must open more than one repository)
4. You will find that octotree doesn't work well, and give this error information. (Basically 100% appear)

**How to fix**
Close all opened GitHub pages and wait a few seconds, and then open a GitHub repository page, you will find that octotree works well without do anything else.

**Comment by buunguyen** [comment]
Just did that but couldn't reproduce. I suggest you look at the XHR request & response made by Octotree (the one hitting api.github.com). If you can provide screenshot of the error reported by GitHub, I might be able to help.

**Comment by rizkyramadhan** [comment]
Hi, 

I am octotree pro subscriber. This happens to my account, 


this is the response:

{
  "message": "API rate limit exceeded for user ID 126301.",
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}

**Comment by danhgit** [comment]
Hi, did you provide an access token? Please feel free to contact support@octotree.io as we might need more information to troubleshoot this.

**Comment by rizkyramadhan** [comment]
yup, I did. Sending it to that email now.
