### ISSUE TITLE
Please remove or allow disabling the bookmark feature

### ISSUE THREAD

**Issue by slikts** [ovity/octotree#858]
It's not very useful (there's already browser bookmarks and stars) and looks bad with a dark theme:

![image](https://user-images.githubusercontent.com/137872/71520215-91ea3300-28c3-11ea-9d14-ee131027be6a.png)

**Comment by buunguyen** [comment]
Many people and I personally use it. So not "completely pointless". I find it more convenient than browser bookmarks.

Now, I don't think the UI looks that bad. But I'm open for suggestion to improve it.

**Comment by jdreesen** [comment]
Sadly, Octotree doesn't care much about the compatibility with other add-ons, but it looks bad in combination with e.g. the green chec kmark that's added by [Refined GitHub](https://github.com/sindresorhus/refined-github) at some repos (the order is switching, too, depending on which extension loads faster): 
![grafik](https://user-images.githubusercontent.com/424602/71526159-c7981780-28d5-11ea-8f06-5ef3743a6ee3.png)

But maybe we can get an option to disable this feature nonetheless?

**Comment by buunguyen** [comment]
> Sadly, Octotree doesn't care much about the compatibility with other add-ons

It's not that we don't care. But we have limited bandwidth. Refined-GitHub does tons of things and keeps adding new things. There are many other GitHub extensions too. We don't use most of them. If people report problem, we'll try to fix it. But we can't be the only party to make sure we're compatible with every other extension at all times. 

As I said in my original comment, if anyone has a better idea to improve the UI, I'm all ears. An option to disable the feature is one option. Would love other ideas too.

**Comment by slikts** [comment]
There's several issues with the button:
 - it doesn't integrate with the existing look and feel; GitHub doesn't use buttons like that, and at the minimum it shouldn't have a round border around it
 - it doesn't integrate with other extensions like the aforementioned Refined GitHub
 - *it duplicates existing browser functionality*, which is a deal breaker for me

To expand on the last point, browser bookmarks use automatic sync, can be backed up easily, integrate with other tools, and have full support from the browser vendors. Extensions can recreate the builtin functionality poorly at best due to reasons like the low `storage.sync` quotas and no standard way to export data for backup.

So, the actionable points are making the bookmarks use actual bookmarks, possibly adding an option to toggle the feature off, and definitely at least removing the border.

**Comment by slikts** [comment]
It could look like this but with a bookmark icon instead of a heart:
![image](https://user-images.githubusercontent.com/137872/71527324-8dce0d80-28e3-11ea-8b03-5d84d42e812f.png)

**Comment by buunguyen** [comment]
Thanks for the great suggestions. Seems like these are 2 good options. We'll address the UI first to release an update ASAP.

**Comment by buunguyen** [comment]
Updated UI in v4.1.2. (Looks better, thanks for the suggestion!)

As for a separate option to disable the feature (aside from simply not using it), we'll consider that.

**Comment by fregante** [comment]
I agree with this issue, the feature seems a duplicate (to GitHub's own stars and the browser's bookmarks) and is also unrelated to Octotree

**Comment by sudhirkhanger** [comment]
I use Octotree for one simple reason which is to be able to browse repositories. Any other feature on top of it should be optional.
Bookmarking feature may be useful for some but for those who don't use it, it becomes intrusive.
Please allow users to disable the feature. Please open this or another ticket so this request can be tracked. I can open a fresh ticket if you would like me to.

**Comment by buunguyen** [comment]
We added option to disable bookmark feature in 4.1.5. Should be available shortly.

**Comment by jdreesen** [comment]
Nice, thx! :)

Will there be an option to disable "[Feature this repository](https://www.octotree.io/showcase)", too?
