### ISSUE TITLE
希望增加一个下载单文件的功能

### ISSUE THREAD

**Issue by lifetin** [ovity/octotree#862]
希望增加一个下载单文件的功能 如下面 图片
![44](https://user-images.githubusercontent.com/10474968/71579482-b2babe80-2b37-11ea-83ff-a692a8378c5c.png)

**Comment by lifetin** [comment]
可以 参考这个
https://github.com/camsong/chrome-github-mate/

**Comment by buunguyen** [comment]
I don't speak the language but I guess you want the download feature like chrome-github-mate. That's no longer possible AFAIK and that extension no longer works (see the Issues page).
