### ISSUE TITLE
PJAX event fired twice when navigating through native links

### ISSUE THREAD

**Issue by kidonng** [ovity/octotree#864]
### Description

Glad to see #490 got fixed, but we have new problems now. Extensions like Refined GitHub will be triggered twice when navigating through native links.

Take https://github.com/ovity/octotree/blob/master/README.md as an example, having Octotree and Refined GitHub installed:

- Direct access (like put the URL in the address bar and press Enter): OK
- Navigate through Octotree (click `README.md` in the sidebar): OK
- Navigate through GitHub's native interface (click `README.md` in the tree list): Duplicate *latest tag* and *Copy button* are shown (see screenshot below)

I assume the bug is PJAX related since it starts to appear in 4.1.2 (and affected extensions wouldn't work in the previous version). This may be fixed by not triggering PJAX event (only Octotree's) when navigating normally.

### Environment (if bug)

* Octotree version: 4.1.2
* Browser & version: Chrome 79.0.3945.88
* OS & version: KDE Plasma 5.17.4 on Arch Linux 5.4.6-zen3-1-zencjk
* Screenshot, if any (drag an image here) ![image](https://user-images.githubusercontent.com/44045911/71637945-a5631880-2c8c-11ea-8a53-82f34560ce34.png)

**Comment by buunguyen** [comment]
Thanks for the detailed bug report! Fixed in 4.1.3.
