### ISSUE TITLE
Underline besides the bookmark icon on hover when it isn't the only one

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#867]
### Description
The updated icon of the bookmark feature looks way better now, thx!

But when there are other icons (from e.g. Refined GitHub) an underline becomes visible left or right (depending on the placement of the other icon) besides the bookmark icon when hovering it.

When there's no other icon, everything is fine.

### Environment (if bug)

* Octotree version: 4.1.3
* Browser & version: Firefox 71.0 (64-Bit)
* OS & version: Windows 10 Pro 19.03
* Screenshots:

When the element is not hovered, everything is fine:
![grafik](https://user-images.githubusercontent.com/424602/71681117-2a812700-2d8c-11ea-9c40-71d6b314daa6.png)
![grafik](https://user-images.githubusercontent.com/424602/71681139-32d96200-2d8c-11ea-9e78-24f9453f3dea.png)

But when the element is hovered, the underline of the link is visible next to the icon:
![grafik](https://user-images.githubusercontent.com/424602/71681237-6ddb9580-2d8c-11ea-97c9-1e573ed8e9ff.png)
![grafik](https://user-images.githubusercontent.com/424602/71681206-5b615c00-2d8c-11ea-8bb0-9f029a803cf5.png)

**Comment by buunguyen** [comment]
Thanks for reporting. This was fixed in the latest release.
