### ISSUE TITLE
Doesn't show all files on large PR's

### ISSUE THREAD

**Issue by timglabisch** [ovity/octotree#873]
### Description
i've a PR with 200+ changed files. Some files are not listed in octotree. I am not sure if this is a bug or a restriction.

### Environment (if bug)

* Octotree version: 4.1.3
* Browser & version: Chrome 78 / 79
* OS & version: OSX Mojave

**Comment by buunguyen** [comment]
Dup https://github.com/ovity/octotree/issues/504
