### ISSUE TITLE
If repo is reached through bookmarks, GitHub search works use previous repo. 

### ISSUE THREAD

**Issue by scapital** [ovity/octotree#877]
### Description
Please, see an example in [the video](https://youtu.be/FeFo0EtYHc4).

### Environment (if bug)
* Octotree version: 4.1.3
* Browser & version: Google Chrome (Version 72.0.3626.121 (Official Build) (64-bit))
* OS & version: Ubuntu 18.04.2

**Comment by buunguyen** [comment]
Thanks for reporting. We'll work on it.

**Comment by buunguyen** [comment]
Thanks for reporting this. Fixed in 4.1.4.
