### ISSUE TITLE
Suggestion: hobbyist version

### ISSUE THREAD

**Issue by aroberge** [ovity/octotree#879]
Currently, there is a choice between a free version, free and suitable for hobbyists that are not part of a team, and a pro version, with many enhancements most of which are geared for people that are part of a team.
As a hobbyist, I would be willing to pay a small amount to have the option of different syntax themes.

**Comment by lolmaus** [comment]
+1 here.

I don't mind supporting the project, but 70 USD per year for an individual feels like being robbed.

**Comment by buunguyen** [comment]
Alright, I intended to leave this thread open, but this kind of language has no place in my repository.
