### ISSUE TITLE
Notifications Beta tab need some styling fixes

### ISSUE THREAD

**Issue by XCanG** [ovity/octotree#887]
### Description
Github have Beta version of notifications at: https://github.com/notifications/beta
and it have some styling issues on dark theme.

### Environment (if bug)

* Octotree version: 4.1.5
* Browser & version: Chrome 79.0.3945.117
* OS & version: Windows 10.0.18362 x64

**Comment by nicktimko** [comment]
Screenshot below. Lowest contrast on the *unread* items.

![image](https://user-images.githubusercontent.com/5297556/74676785-67f31580-517c-11ea-94a8-6940be13c5dd.png)

**Comment by buunguyen** [comment]
Fixed in 4.1.6. Should be available in store soon.
