### ISSUE TITLE
Custom styles break sticky "viewed" bar 

### ISSUE THREAD

**Issue by Maragues** [ovity/octotree#888]
### Description
Expected behavior (default if you use Github's theme):
When scrolling through PR files, the "Viewed" bar sticks to the top when you are reviewing a large file

Octotree custom theme behavior

The "Viewed" bar scrolls with the large file. To flag it as "viewed", I have to scroll up.

### Environment 

* Octotree version: 4.1.5
* Browser & version: Version 79.0.3945.130 (Official Build) (64-bit)
* OS & version: MacOS Catalina 
* Console error log below this line: none

**Comment by buunguyen** [comment]
Thanks for reporting! Fixed in 4.1.6. Should be available in store soon.
