### ISSUE TITLE
Automatically change to dark mode when browser changes to dark mode based on the OS

### ISSUE THREAD

**Issue by xeoneux** [ovity/octotree#889]
### Description
On my macOS, dark mode gets enabled automatically after sunset. In turn, the Chrome browser also changes to dark mode. Many websites which depend on `prefers-color-scheme` css media query also change the webpage automatically.

Please implement this feature where GitHub turns dark during the night. I'd be able to help contribute to this feature during the coming weekend.

### Environment (if bug)

* Octotree version: latest
* Browser & version: latest Chrome
* OS & version: macOS Catalina
* Screenshot, if any (drag an image here) NA
* Console error log below this line NA

**Comment by buunguyen** [comment]
Supported on Octotree 6 (require Pro subscription)
