### ISSUE TITLE
View full button missing

### ISSUE THREAD

**Issue by asafpelegcodes** [ovity/octotree#901]
### Description
Looking at a PR I'm noticing that the "View full" button is missing for one of the files.  See screenshot below. Also for the same file, I'm noticing when I click on it in the octotree window it does not navigate to the correct file.

* Octotree version: 4.1.7
* Browser & version: Chrome 80.0.3987.122
* OS & version: Mac 10.14.6
* Screenshot, if any (drag an image here)
![Screen Shot 2020-03-10 at 10 46 02 AM](https://user-images.githubusercontent.com/6590390/76324700-c82d3100-62bc-11ea-88dd-5b2d86d0ebdb.png)

* Console error log below this line

**Comment by buunguyen** [comment]
Hi, are you using Pro? And the button shows up for all other files?

**Comment by asafpelegcodes** [comment]
I'm using Pro and the button showed up for every file until I reached that
file and the ones after that were missing

**Comment by buunguyen** [comment]
That is strange. We have never seen this issue. If you could dig in a bit more and let us know if there's anything "special" about this PR and file, it would help debugging a lot. For example, is this a big PR, where is the location of the file (near the top, the bottom), what does its DOM look like etc.

**Comment by asafpelegcodes** [comment]
I've got another PR that this is occurring, what further information can I
provide?

**Comment by buunguyen** [comment]
Please see https://github.com/ovity/octotree/issues/874#event-2944016676
We haven't been able to reproduce. Nobody else seems to have this issue anyway. So unless you could provide info to help us reproduce, we can't fix it.

**Comment by asafpelegcodes** [comment]
I'm not sure why you linked 874? The PR i'm looking at is large, it
contains ~90 files changed and some of them are large. If there is some
specific action you want me to take and share with you let me know.

**Comment by buunguyen** [comment]
Was meant to link to this https://github.com/ovity/octotree/issues/901#issuecomment-603536957

Any common pattern you notice from the PRs or files that have this problem?

**Comment by asafpelegcodes** [comment]
I lost track of the one that I first noticed it in but I do believe it was
big both file numbers & file length.

**Comment by buunguyen** [comment]
@asafpelegcodes thank you. We were able to fix the issue. Will release in the next version.

**Comment by asafpelegcodes** [comment]
Yay thank you so much. I love your product and I'm really happy this will
be fixed soon.

**Comment by davidcreel** [comment]
Hi I started using Octotree today (version 4.2.1) and am trialing the pro version. I am experiencing the same issue described here. Where the view full button appears for the first X number of files but then almost never again after that. Is this fix in version 4.2.1? The latest release I see [here](https://github.com/ovity/octotree/releases) was quite a while ago.

**Comment by buunguyen** [comment]
Hi, we fixed this but need a bit more time to release with other things. Hopefully within a couple of weeks. thanks for your patience.

**Comment by buunguyen** [comment]
Released in 5.0
