### ISSUE TITLE
Octotree overlays repo navigation on the actions tab

### ISSUE THREAD

**Issue by FlorianDe** [ovity/octotree#902]
### Description
The problem occurs only when you are on the Actions tab of one of your own repositories.
When I browse someone else's repository actions, everything looks fine.

### Environment
* Octotree version 4.1.7
* Chrome version 80.0.3987.116 (64-Bit)
* Windows 10 x64

![image](https://user-images.githubusercontent.com/10079797/76411289-cc774e00-6391-11ea-81f8-54eab1165eea.png)

**Comment by Eirias** [comment]
Can be reproduced on the Projects Tab as well.
**Environment**
Octotree version 4.1.7
Chrome version 80.0.3987.132  (64-Bit)
macOS Catalina 10.15.3
![Bildschirmfoto 2020-03-11 um 13 12 11](https://user-images.githubusercontent.com/12933083/76415929-6ba04380-639a-11ea-96b7-e753d31c13b7.png)

**Comment by buunguyen** [comment]
Fixed in 5.0
