### ISSUE TITLE
Incorrect anchor paths to diffs in PR view

### ISSUE THREAD

**Issue by chmurson** [ovity/octotree#905]
### Description
**Where?:** PR view. Octotree file tree view. 
**What?:** Click on the file does not navigate browser to the diff content.

**more info**
The link generated by octotree to the diff content is wrong. 
e.g.
Octo tree link is:
`<domain + project>/pull/464/files#diff-5`
But the actually link to the diff is:
`<domain + project>/pull/464/files#diff-94d581cd97316846b447e9084fe9073a`

### Environment (if bug)

* Octotree version: 4.1.6 (the newest from App Store)
* Browser & version: Safari 13.0.5
* OS & version: macOS 10.15.3
* Screenshot

Paths/anchors from Octotree:
![Zrzut ekranu 2020-03-16 o 11 56 28](https://user-images.githubusercontent.com/3996881/76749732-48e8a300-677d-11ea-8aaf-fd8841d5797d.png)

Paths/anchors from Github:
![github paths](https://user-images.githubusercontent.com/3996881/76749753-53a33800-677d-11ea-83f2-5a87728048a2.png)

**Comment by rzaharenkov** [comment]
I have also noticed this bug. Interesting detail that first X anchors in PR works fine but after some point it fails to scroll to the file. So please test on big PRs (20+ files). It's very annoying issues.

**Comment by Lambeaux** [comment]
Can confirm, occurs on large PRs on Chrome `80.0.3987.149` but toggling the extension off then on again fixed the issue.

**Comment by chmurson** [comment]
@rzaharenkov
> I have also noticed this bug. Interesting detail that first X anchors in PR works fine but after some point it fails to scroll to the file. So please test on big PRs (20+ files). It's very annoying issues.
For me every link/anchors are wrong for every file, no matter of PR size

> Can confirm, occurs on large PRs on Chrome `80.0.3987.149` but toggling the extension off then on again fixed the issue for me.
Tried similar approach on Safari 13.0.5 and macOS 10.15.3. No effect.

**Comment by rzaharenkov** [comment]
@Lambeaux I've just updated to the same version. Tried to disable/enable extension and also re-install it. But nothing helps. Navigation is still broken. The reason is described above: github has changed anchor links format and Octotree doesn't reflect that.

**Comment by buunguyen** [comment]
This was reported here https://github.com/ovity/octotree/issues/895, so I'm gonna close it. Thanks for the additional details.

**Comment by Lambeaux** [comment]
@rzaharenkov Noted, I found it odd that I got it to work again and I'm not sure why. But sure enough later on it broke again and hasn't been working since. I'll probably do another test cycle later on but for now I've disabled the plugin.
