### ISSUE TITLE
Not listing the file diffs on PR pages

### ISSUE THREAD

**Issue by LandazuriPaul** [ovity/octotree#909]
### Description

Lately - I would roughly say around 1 week, the extension doesn't provide the PR diffs it used to have.

When browsing a PR page, the extension used to show only the files modified by the PR, with line count diffs (+ / -). And each file link would send us to the corresponding file diff view in GitHub.

This feature was really handy during PR reviews.

Now, when browsing a PR, the extension shows the full master branch files. And the links send us to the master file instead of the PR diff.

I was wondering if it is a bug or a new limitation, hence this issue :)

### Environment

* Octotree version: 4.2.1
* Browser & version: Brave Version 1.5.113 Chromium: 80.0.3987.149 (Official Build) (64-bit) & Chrome Version 80.0.3987.149 (Official Build) (64-bit)
* OS & version: macOS Catalina (10.15.3)

Thank you for this extension which is really helpful on a daily basis!

**Comment by jdreesen** [comment]
See #895 and #905 and especially https://github.com/ovity/octotree/issues/895#issuecomment-602321705.

**Comment by LandazuriPaul** [comment]
@jdreesen Thank you for your quick response!

Have a good one
