### ISSUE TITLE
Bug: Hostname for bookmarked Enterprise resources from public/github.com

### ISSUE THREAD

**Issue by anythingcodes** [ovity/octotree#910]
### Description

When clicking any private GitHub Enterprise bookmark from a public `github.com` repo, the bookmarked link's domain is `github.com` instead of the bookmarked private/Enterprise domain.

#### Steps to Reproduce
1. Bookmark a private GitHub Enterprise repo or other resource.
2. Navigate to a public `github.com`-hosted repo or other resource.
3. Click the bookmarked private GitHub Enterprise repo. 

Note that the link's domain is `github.com` instead of the private Enterprise domain, so clicking will typically 404.

### Environment (if bug)

* Octotree version: 4.2.1
* Browser & version: Chrome v80.0.3987.132 64-bit
* OS & version: macOS Catalina 10.15.3
* Screenshot, if any (drag an image here):

![Screen Shot 2020-03-25 at 1 46 20 PM](https://user-images.githubusercontent.com/3537575/77568569-2fdba280-6e9f-11ea-8094-959bae3799d2.png)

* Console error log below this line: Not applicable

Happy to PR this if you're accepting contributions! Thanks for the great tool.

**Comment by buunguyen** [comment]
Thanks for reporting. We have fixed and will release in the next version.

**Comment by buunguyen** [comment]
Fixed in 5.0
