### ISSUE TITLE
Sign up Failed, "Disposable email address is not allowed"

### ISSUE THREAD

**Issue by seymoe** [ovity/octotree#911]
### Description
When I'm ready to sign up, just get this tips -- "Disposable email address is not allowed". my Email address is `...@yeah.net`. However it's not a Disposable email format.

**Comment by Arelav** [comment]
My email is on Gmail.
I just want to make your guys a second chance after you disabled Safari extension and forced to pay.
I agree to pay if it's a free choice but this was dirty and made me angry. Now when I try to register with my Gmail address it makes me this message. I have another email but common... Perhaps you hired too many "effective managers".
Making a profit is always good. Make a good product and people will pay but don't make usage of the product painful. The mandatory registrations it was almost too much but I tried. This is a very, very bad customer experience...

**Comment by buunguyen** [comment]
@Arelav Octotree is free. Octotree Pro is paid. If you need help with registration, ask nicely.
