### ISSUE TITLE
Octotree Pro extension for GoogleChrome

### ISSUE THREAD

**Issue by Tiaki-Chanaka** [ovity/octotree#914]
### Description
* OS & version: Windows10
* Browser: Google Chrome

Today, I have started Monthly plan. But unfortunately, I couldn't find the "Octotree **Pro**" extension for Google Chrome. (I could found the "Octotree" extension. )

This link (https://chrome.google.com/webstore/detail/octotree-pro/fjcahddnekkgihjnjnimgiggdmlgcnbc?hl=ja) is not available now.

Has the development for Chrome been discontinued?

Now, I use Opera as a temporary browser to use OctotreePro's functions.

**Comment by buunguyen** [comment]
Hi, the correct link is here https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US

**Comment by Tiaki-Chanaka** [comment]
Thanks for your quick response. But I have already know the above link. That link is for "Octotree", not "Octotree Pro". I added "Octotree" extension to Chrome, but that doesn't have "Pro" function.  So I created this issue on this repository.

**Comment by buunguyen** [comment]
Please click the login link at the blue footer of the Octotree sidebar, sign in. Then you'll access Pro functionality.

**Comment by Tiaki-Chanaka** [comment]
Thanks. Sorry, I forgot to mention that I'm a GitHub Enterprise user.  
![image](https://user-images.githubusercontent.com/58283091/77973367-ea035c00-732e-11ea-9d57-cdfba1c67b02.png)
How do I add the GitHub Enterprise server address ?

**Comment by buunguyen** [comment]
Hi, instruction is here: https://github.com/ovity/octotree#github-enterprise

**Comment by Tiaki-Chanaka** [comment]
It's a bit of a tricky thing to do...
But I solved it.Thank you for your prompt response.
