### ISSUE TITLE
API deprecation notice from GitHub

### ISSUE THREAD

**Issue by willnode** [ovity/octotree#915]
### Description

Recently I have received this email from GitHub. I'm not sure if other people also have receiving this. Below the partial screenshot:

![image](https://user-images.githubusercontent.com/20214420/77930766-7e40d500-72d5-11ea-913a-f17b7759d531.png)

**Comment by buunguyen** [comment]
Hi, Octotree sets token via the Auth header: https://github.com/ovity/octotree/blob/master/src/adapters/github.js#L228. It doesn't use `access_token` query param. I think you probably reuse the same token in some other place/plugin which uses that deprecated method.
