### ISSUE TITLE
Distinguishable UI for bookmark states

### ISSUE THREAD

**Issue by gokatz** [ovity/octotree#916]
### Description
First of all, Octotree is becoming one of the must-needed extension for me. Thanks for your time.

One small UI suggestion is that the Icon and styles used in un-bookmarked and bookmarked state is hard to distinguish visually. PFA. In the attachment below, the repo is not bookmarked whereas the PR is. It's hard to know if a repo/PR is bookmarked at a single glance. Maybe a tick mark or changing the colour after being bookmarked would be a lot easier to know the state.

<img width="909" alt="Screenshot 2020-04-02 at 9 02 03 AM" src="https://user-images.githubusercontent.com/15158776/78208354-d1777b00-74c1-11ea-8b9a-7eb570c94402.png">

As a footnote, while searching through the issue to check if this is already reported, I found this one: https://github.com/ovity/octotree/issues/867. This issue contains a tick mark near to the Bookmark icon. Not sure if that was added by Octotree. Mentioned here just for references.

### Environment (if bug)

* Octotree version: 4.2.1
* Browser & version: Chrome 80
* OS & version: Mac 10.15

**Comment by buunguyen** [comment]
Thanks for reporting. Fixed in 5.1, we reduce opacity if not bookmark.
The tick shown in the pix is from another plugin, not by Octotree.
