### ISSUE TITLE
Sidebar shows all files instead of only changed ones

### ISSUE THREAD

**Issue by MichalMichalak** [ovity/octotree#917]
### Description
Sidebar always shows all files. Example, when I enter PR's files page https://github.com/torvalds/linux/pull/805/files I do expect to see only files that have been changed - but it still shows full files tree. It started to behave like that around 2-3 weeks ago - unfortunately can't tell exact date. It might be me, or my browser, or my system. Any help would be appreciated. Thanks.

### Environment (if bug)
* Octotree version: 4.2.1
* Browser & version: Firefox 74.0 (64-bit) also Chrome 80.0.3987.162 (Official Build) (64-bit)
* OS & version: macOS Catalina 10.15.4
* Console error log below this line: None, console is empty

**Comment by MichalMichalak** [comment]
I've must have missed that. It is paid functionality now. :(

**Comment by jdreesen** [comment]
See https://github.com/ovity/octotree/issues/895#issuecomment-602321705
