### ISSUE TITLE
Suggestion: Make PR pack free

### ISSUE THREAD

**Issue by tmseiler** [ovity/octotree#918]
### Description
Making a previously-free core feature into a paid-only one was incredibly frustrating to me. I think you should move this back to the free version. Additionally I had to spend almost an hour scouring the repo to figure out why the thing I relied on most stopped working.

**Comment by buunguyen** [comment]
Please see https://github.com/ovity/octotree/issues/895#issuecomment-602321705

I will make it free if you work for me for free, deal?

**Comment by tmseiler** [comment]
Thank you for the offer. I will have to consider those terms further before I make a decision.

In the mean time I have found this, in case anyone else encounters this issue later: https://github.com/berzniz/github_pr_tree
