### ISSUE TITLE
API token randomly disappears from settings

### ISSUE THREAD

**Issue by slikts** [ovity/octotree#919]
I *regularly* have to re-enter a GitHub token because the previous one gets seemingly randomly erased.

Octotree 4.2.1
Chrome 80.0.3987.163

![image](https://user-images.githubusercontent.com/137872/78988997-09726400-7b3b-11ea-949b-f632ae2dad87.png)

![image](https://user-images.githubusercontent.com/137872/78988983-011a2900-7b3b-11ea-91d8-ac18d9656c7d.png)

**Comment by buunguyen** [comment]
Did you happen to clear local storage regularly by chance?

**Comment by slikts** [comment]
This would be quite a silly bug report if I were clearing the storage for some reason, so no.

I just checked, and this extension is storing the token in the site's local storage instead of the extension's own. For one thing, this means that GitHub can clear it (and probably did), and for another it means that it's not synced between logged in browsers. The extension manifest includes the storage permission, so there's no reason for it to be implemented like this.

**Comment by slikts** [comment]
github.com storage:
![image](https://user-images.githubusercontent.com/137872/79044382-866e0e00-7c0d-11ea-8d93-a15e8bdfdcf6.png)

Meanwhile, the extension storage is empty:
![image](https://user-images.githubusercontent.com/137872/79044415-b1586200-7c0d-11ea-9c1e-a7d280282d47.png)

**Comment by buunguyen** [comment]
Yeah, we store it in local storage so that in a different domain (GH enterprise), a different token can be used. But yes, we can also store in the ext storage too, take a bit more effort but looks worth it now that this issue exists. Thanks for reporting!

**Comment by slikts** [comment]
Having to enter a token for each browser because it's not synced is an oversight, and associating the token with a domain can be done more simply than by using the site instead of the extension storage.

**Comment by buunguyen** [comment]
> Having to enter a token for each browser because it's not synced is an oversight

No it's not. Sync'ing cross browsers means we have to store tokens in our backend. I don't think that's a risk most users would accept while only a minority uses multiple browsers for GitHub purpose.

> associating the token with a domain can be done more simply than by using the site instead of the extension storage.

Now I'm confused. Are you with or against storing in local storage?

**Comment by slikts** [comment]
WebExtensions API has `storage.sync`; your own backend is not involved. It also has `storage.local` which could have been used instead of GitHub's storage.

**Comment by buunguyen** [comment]
Currently we store most settings except token in storage.local. My earlier response means we're considering storing the token in storage.local too, to avoid the token-cleaning problem that this issue is about. 

Do you think we should use storage.sync to store all settings? Any security concern?

**Comment by slikts** [comment]
And yet again I find the token randomly cleared.
![image](https://user-images.githubusercontent.com/137872/87478111-eb346c80-c631-11ea-8cbe-685984e2b8ee.png)

**Comment by buunguyen** [comment]
Weird, we store the token in `storage.sync`. Do you use multiple browsers and one override another? Any idea to help debug is appreciated.
