### ISSUE TITLE
Pops-up continuously when editing file / issue

### ISSUE THREAD

**Issue by ahmetcetin** [ovity/octotree#920]
### Description
Octotree pops-up/hides randomly and continuously when writing in issues in GitHub or edting a file. Basically when typing. In settings "Show sidebar on hover" is unchecked (Though it's the same when checked). It's irritating, as it gets the focus when pops up and you just cannot type. Just because of this, I'll ditch octotree probably.

### Environment (if bug)

* Octotree version: Latest
* Browser & version: Microsoft Edge
* OS & version: MacOS Catalina

**Comment by buunguyen** [comment]
Never saw that. Can you post GIF?
Or you can show Octotree only when you need it. There's a short key to show/hide.

**Comment by ahmetcetin** [comment]
indeed, it was hotkey problem, somehow it was set to key "s" and whenever i was typing s octotree was popping up. thx for the hint!

**Comment by buunguyen** [comment]
Thanks!
