### ISSUE TITLE
Doesn't show changed files on PRs

### ISSUE THREAD

**Issue by damemi** [ovity/octotree#926]
### Description
I just updated my octotree version, and now when I view PRs the extension doesn't show the files that were specifically changed in that PR (with the +/- count). Instead it just shows the normal navigation for the full repo.

### Environment (if bug)

* Octotree version: 4.2.1
* Browser & version: Firefox 75.0
* OS & version: Mac os catalina
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by damemi** [comment]
Update: downgrading to 4.1.7 fixed this. Perhaps this became a pro feature in 4.2?

**Comment by jdreesen** [comment]
See https://github.com/ovity/octotree/issues/895#issuecomment-602321705

**Comment by damemi** [comment]
@jdreesen ah thanks
