### ISSUE TITLE
In pull requests, changed file's url hash is not compatible with github

### ISSUE THREAD

**Issue by cmygray** [ovity/octotree#928]
### Description

In pull request > files changed tab (/pull/:number/files), github uses each file's hash for navigating in page. But octotree uses each file's index. So links of changed files in tree not work.

### Environment (if bug)

* Octotree version: 2.0.2
* Browser & version: 80.0.3987.163
* OS & version: macOS 10.15.4
* Screenshot, if any (drag an image here)

GitHub jump to file link (using hash)
![image](https://user-images.githubusercontent.com/26966551/80077226-291c7a00-8588-11ea-9fd5-5ab02c2764fd.png)

octotree jump to file link (using index)
![image](https://user-images.githubusercontent.com/26966551/80077449-7bf63180-8588-11ea-9503-23770ca38537.png)

* Console error log below this line

**Comment by buunguyen** [comment]
Hi, please see this. Basically GH changed approach and broke Octotree. https://github.com/ovity/octotree/issues/895
