### ISSUE TITLE
Pinned sidebar doesn't push new notifications header to the left

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#929]
### Description
When navigating from the new notifications overview to an issue/PR, there is a new blue header with some action buttons.

While Octotree pushes the items in the black header to the left when the sidebar is pinned, this does not happen for the new blue notifications header, which results in the `← Back to notifications` button being hidden.

### Environment (if bug)

* Octotree version: 4.2.1 (pro)
* Browser & version: Firefox 75.0 (64-Bit)
* OS & version: Ubuntu 18.04
* Screenshots:
Unpinned sidebar closed:
![grafik](https://user-images.githubusercontent.com/424602/80083244-ac70a800-8555-11ea-81bf-964583287872.png)
Unpinned sidebar open:
![grafik](https://user-images.githubusercontent.com/424602/80083504-fbb6d880-8555-11ea-9358-9b5fb4fc20c5.png)
Pinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/80083011-6a476680-8555-11ea-9c24-b769bede671c.png)

**Comment by jdreesen** [comment]
Thx, but now it isn't sticky anymore :(

When I scroll down in an issue/pr, there's a gap where the notification header should be:

![grafik](https://user-images.githubusercontent.com/424602/83816256-403fa300-a6c2-11ea-9d1a-7ea50b613149.png)

Maybe it has something to do with refined GitHub? When I disable Octotree, everything is fine, though.

**Comment by buunguyen** [comment]
Thanks for reporting. Looks like a new bug.

**Comment by buunguyen** [comment]
Fixed in 5.1

**Comment by jdreesen** [comment]
Awesome, thx!
