### ISSUE TITLE
Connection Error when google-analytics in repository name 

### ISSUE THREAD

**Issue by bbuivn** [ovity/octotree#931]
### Description
If repository contains `google-analytics` in its name there's the following error:
```
Cannot connect to website. If your network connection to this website is fine, maybe there is an outage of the API. Please try again later.
```

### Environment (if bug)
* Octotree version: 4.2.1
* Browser & version: Firefox 75.0
* OS & version: macOS Catalina 10.15.0
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/561357/80090131-51dc4980-855f-11ea-84d2-44e44c2fa877.png)

* Console error log below this line
I can't find any errors from the console log, there's nothing but HTTP 304 and 200
![image](https://user-images.githubusercontent.com/561357/80090112-4852e180-855f-11ea-9509-fa95c7d386d3.png)

I can't reproduce the error on Chrome 81.0.4044.122

**Comment by buunguyen** [comment]
I can access to repo with google-analytics just fine. Maybe a different problem.

**Comment by bbuivn** [comment]
I tested with private repositories.
`etl-google-analytics` gave the error mentioned.

`etl-google-dhfbbdi-analytics` was working fine, so it’s not a length issue, almost for sure.
`fei-google-analytics-djv` also gave the error, hence the hypothesis about google-analytics.

As a reminder I don’t have the issue on Google Chrome, only Firefox.

**Comment by buunguyen** [comment]
Maybe adblocker problem? Basically there's absolutely no reason Octotree would fail just because repo name contains the word "google-analytics".

**Comment by bbuivn** [comment]
Oh my god I can't believe I'm this kind of stupid...

It was indeed an adblocker issue, uBlock Origin has a rule matching `-google-analytics`...
I'm so sorry.

Closing the issue. Thanks a lot!
