### ISSUE TITLE
Octotree stopped filtering to the current PR

### ISSUE THREAD

**Issue by msorens** [ovity/octotree#942]
### Description
I have used Octotree for a year or more without incident. Until a couple days ago, Octotree would correctly filter the repo contents to show just the files relevant to the current pull request. Now, it is showing all files in the repository.
What changed? Is there something I need to do...?

I tried the following but I see the same problem constantly:
 * Uninstalling then reinstalling the plugin
 * With and without logging in
 * With and without GitHub token assigned
 * With and without lazy load setting enabled

Note that this is for a public repository (https://github.com/chef/automate).

### Environment (if bug)

* Octotree version: 4.2.1
* Browser & version: Firefox 75.0
* OS & version: macOS mojave 10.14.6
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by jdreesen** [comment]
See https://github.com/ovity/octotree/issues/895#issuecomment-602321705

**Comment by msorens** [comment]
Thanks for the pointer to that issue. 👍
