### ISSUE TITLE
Dark theme visual issue

### ISSUE THREAD

**Issue by XCanG** [ovity/octotree#944]
### Description
Twilight theme need adjust diff styling color to be easely readable, right now they are used colors for light theme.

Look with twilight theme on this block:
```diff
- red text, may be need to adjust slightly bright background
! bright text, hard to see, looks like bright block
+ green text, kinda ok
```

### Environment (if bug)

* Octotree version: 4.2.1
* Browser & version: 80.0.3987.149
* OS & version: Windows 10 x64
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/4011523/81202888-aa402c00-8fe0-11ea-9374-8d5c03c47675.png)

**Comment by buunguyen** [comment]
We use styles from https://github.com/StylishThemes/GitHub-Dark. Maybe open a request to their repo?
