### ISSUE TITLE
Octotree Content is being included in Browser's Search Results

### ISSUE THREAD

**Issue by cagdas001** [ovity/octotree#945]
### Description
Octotree's content is being included in the browser's (built-in) search results. Search function covers this area even though the sidebar is collapsed. See screenshots

It should be excluded in some way, either by excluding only when it's collapsed, or excluding the sidebar content completely

### Environment

* Octotree version: 4.2.1
* Browser & version: Chrome 81.0.4044.129
* OS & version: Windows 10 Education - Build 1809
* Screenshot(s)

| Expanded | Collapsed |
| ---- | ---- |
| ![chrome_2020-05-06_22-28-25](https://user-images.githubusercontent.com/28513447/81220160-8e8d5380-8fe9-11ea-9fa5-2cdeb4d54646.png) | ![chrome_2020-05-06_23-09-58](https://user-images.githubusercontent.com/28513447/81223512-c64aca00-8fee-11ea-81ee-05ac82a3e419.png) |

**Comment by buunguyen** [comment]
Interesting. Wonder how this can be done though. Any idea is welcome.

**Comment by cagdas001** [comment]
Hi @buunguyen I have researched & investigated this a bit when I opened this issue. You have some options

### Possible Solution(s)

1. Excluding only when it's collapsed

If you use `display: none;` to hide the panel, search function will not look into this element.
 
2. Completely excluding

In this case, the text content for list items should be added with CSS.

You can take these as reference:
* https://stackoverflow.com/a/19458116/3790180
* https://stackoverflow.com/a/32398699/3790180

**Comment by buunguyen** [comment]
Fixed in 5.2.0, now if collapsed, won't search sidebar.
