### ISSUE TITLE
Showing entire Repo tree in Pull Request

### ISSUE THREAD

**Issue by rycu** [ovity/octotree#953]
### Description

It the past Octotree has displayed only the changed files within a given PR when viewed (which was great).
Now I have noticed the the entire repo tree is displayed.

Any ideas how to return to the previous functionality?

### Environment

* Octotree version: 4.2.1
* Browser & version: Chrome 81.0.4044.138 
* OS & version: OSX 10.15.4

**Comment by jdreesen** [comment]
> Any ideas how to return to the previous functionality?

Use the Pro version ;)

See: https://github.com/ovity/octotree/issues/895#issuecomment-602321705
