### ISSUE TITLE
Pinning not working in project page

### ISSUE THREAD

**Issue by theapache64** [ovity/octotree#958]
Even though I've enabled the pinning, in project page, it's not working. (hides the page content)
![image](https://user-images.githubusercontent.com/9678279/82746928-8dfb0800-9db2-11ea-8542-e9c8a5772475.png)

**Comment by pengtianabc** [comment]
> Even though I've enabled the pinning, in project page, it's not working. (hides the page content)
> ![image](https://user-images.githubusercontent.com/9678279/82746928-8dfb0800-9db2-11ea-8542-e9c8a5772475.png)

I found this exception after enable new git style(Repo refresh feature of github).

**Comment by buunguyen** [comment]
Fixed in 5.0
