### ISSUE TITLE
Search - Configure Search To Search In Target Sub-Directory

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#960]
### Description

**The problem**:
I work against a super large mono-repository, and lazy-load in enabled. However, i only work in a specific sub-directory of this large mono-repo, and so I would like to target my searches inside a specific sub-directory rather than searching throughout the whole mono-repo (which i know slows down and really hit the UI performance).

At the moment, i am a Pro subscribed user, and i cannot actually utilise the Search facility in a lazy-loaded mono-repo, mainly due to the (known) big performance impact hit (when lazy load is off), and also when lazy-load is on, it currently only searches against **cached** files only, under which i've already opened a sub-directory against, which does not help either.

**Suggestion**:
A solution to the problem is to allow the user to enter a path (for example, `<SUB_DIR>/`, or even `<SUB_DIR>/<SUB_DIR>/`)  that begins from the root of the project to initiate a search to start from a user-specified sub-directory (even by-passing lazy load when sub-directory is set. But best let the user know as a warning perhaps). This can be configurable in **Settings**.

This will allow me and other users with large lazy-loaded mono-repos to really take advantage of the Search feature to better suit our needs without sacrificing much of a performance hit.

The suggested feature may even be considered to be a Pro only feature. A really enticing win-win for everyone.

**Comment by buunguyen** [comment]
Thanks for being a Pro subscriber. We improved rendering and search perf significantly in this release. I recommend turn off lazy load for this repo (and optionally enable cache) to see if the perf is acceptable. Search should be very fast. We  disable search in lazy-loading because it causes confusion more than anything. Please let us know how the new version works out for you.

**Comment by Sayvai** [comment]
@buunguyen One word. **WOW** 🎉 

I just automatically received the version `6.0` just now, and tried the search with `lazy-load` feature disabled on a mono-repository with 80+ microservices as top-level directories with possibly thousands of files, and the search is blazingly fast, and even subtly highlights the search term over file / folder names, showing the full nested tree structure! ⚡ ⚡  ⚡  

Fantastic effort of this major version upgrade, and this is well worth the **Pro** subscription. Well done 👍  🚀

**Comment by buunguyen** [comment]
Very happy to hear, Sayvai! Your kind words made our days.

If you work with search regularly, you can also use the new short key (Tab + S) that could be configured. Also we improved keyboard navigation, so you can press Tab or Down Arrow to go from search to the file tree.

**Comment by Sayvai** [comment]
> Very happy to hear, Sayvai! Your kind words made our days.
> 
> If you work with search regularly, you can also use the new short key (Shift + S) that could be configured. Also we improved keyboard navigation, so you can press Tab or Down Arrow to go from search to the file tree.

Nice! I wasn't aware of these keyboard shortcuts earlier. Now it'll speed up my development. Thank you 😎
