### ISSUE TITLE
Not showing changes in PR

### ISSUE THREAD

**Issue by trungdq88** [ovity/octotree#962]
### Description
Over the past few months, my octotree stopped to show changes in PR. Image:
![image](https://user-images.githubusercontent.com/4214509/83762257-8c2e2000-a6a1-11ea-835d-f35a2dcba1bd.png)

Things I tried:
- Generated new token
- Uninstall extension and install it again

### Environment (if bug)

* Octotree version: 5.0.0
* Browser & version: Chrome 83
* OS & version: macOS 10.14.6
* Screenshot: attached above
* Console error log below this line (in the image)

**Comment by jdreesen** [comment]
And again... 

it's a pro-feature now ;)

See: https://github.com/ovity/octotree/issues/895#issuecomment-602321705
