### ISSUE TITLE
can not access any repo!!!

### ISSUE THREAD

**Issue by dirklu** [ovity/octotree#963]
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.
can not access any repo!!  event if update new token

### Environment (if bug)

* Octotree version:  5.0.0 
* Browser & version: chrome 83.0.4103.61
* OS & version: mac os 
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/21187455/83822223-ff1bb300-a702-11ea-8ad4-ed7b7b74683b.png)
* Console error log below this line
https://api.github.com/repos/chromedp/chromedp/git/trees/%E9%95%9C%E5%83%8F%E5%88%97%E8%A1%A8?recursive=1&_=1591315640785 404 (Not Found)

**Comment by buunguyen** [comment]
chromedp/chromedp is public, I can access it without token. So the log maybe something else.

Try these:

* Make sure token is valid
* Make the right scope is granted for private repo

If still not work, we'll need much more info to deal with this.
