### ISSUE TITLE
Pro (Code Font Settings): Selecting the JetBrains Mono font does not set it

### ISSUE THREAD

**Issue by taneliang** [ovity/octotree#964]
### Description

Steps to repro:

1. Navigate to any code file (e.g. https://github.com/nusmodifications/nusmods/blob/master/docker-compose.yml)
1. Open Octotree settings
1. Select the JetBrains Mono font
1. Click "Apply settings"

The font family is not changed. Inspecting the code shows that the `font-family` CSS attribute was not set on the element. I've confirmed that other fonts are working, and that `data-octotree-font-family` is set on the `html` element.

Side note: it'll be awesome if you could add [Iosevka](https://typeof.net/Iosevka/) to the list of fonts! It's [open source](https://github.com/be5invis/iosevka). Thanks for working on this awesome tool - I've been using it for years and it only keeps getting better :D

### Environment (if bug)

* Octotree version: 5.0.0
* Browser & version: Chrome Version 83.0.4103.97 (Official Build) (64-bit)
* OS & version: Windows 10 Pro Version 2004 Build 19041.264
* Screenshot, if any (drag an image here)
	![image](https://user-images.githubusercontent.com/12784593/83985503-127d8700-a96c-11ea-8c9d-54da1546e44d.png)
* Console error log below this line
	No relevant errors

**Comment by buunguyen** [comment]
Fixed in 5.1
