### ISSUE TITLE
Filename containing non-ASCII characters get encoded in tabs

### ISSUE THREAD

**Issue by kidonng** [ovity/octotree#965]
### Description

If the filename contains non-ASCII characters, the tab will display the encoded filename.

Example: https://github.com/CyC2018/CS-Notes/blob/master/notes/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%B3%BB%E7%BB%9F%E5%8E%9F%E7%90%86.md

### Environment (if bug)

* Octotree version: 5.0.0
* Browser & version: Chrome 85.0.4164.4
* OS & version: Windows 10 19640.1
* Screenshot, if any (drag an image here)

![image](https://user-images.githubusercontent.com/44045911/83998666-add62280-a993-11ea-8a17-6218430de540.png)

* Console error log below this line None

**Comment by buunguyen** [comment]
Fixed in 5.1
