### ISSUE TITLE
Build status icons in dark mode all gray

### ISSUE THREAD

**Issue by hellogerard** [ovity/octotree#967]
### Description

Great product! Am a pro version user. With the latest update, my CI build status icons on PRs are all gray in any dark mode. They used to be green for success, red for failures, and yellow for "in progress."  This is somewhat minor, but I miss the ability to quickly scan a PR and know if it is merge-able or not.

### Environment (if bug)

* Octotree version: 5.0.0 (Pro)
* Browser & version: Chrome 83.0.4103.61
* OS & version: MacOS Catalina (10.15.5)
* No `console.error` message?

|Dark mode (build icons all gray)|Light mode (build icons are correct)|
|--|--|
|<img width="493" alt="Screen Shot 2020-06-08 at 2 28 34 PM" src="https://user-images.githubusercontent.com/200488/84066740-5edcbd00-a994-11ea-8f32-9a7f8e596ac3.png">|<img width="485" alt="Screen Shot 2020-06-08 at 2 28 07 PM" src="https://user-images.githubusercontent.com/200488/84066736-5e442680-a994-11ea-9ac7-a7e2732cb444.png">|

**Comment by Sayvai** [comment]
This seems to pretty much describe the same issue i raised the other week #959

**Comment by hellogerard** [comment]
Yes, closing in favor of #959.
