### ISSUE TITLE
The tooltip is hidden when sidebar to the right

### ISSUE THREAD

**Issue by ellreka** [ovity/octotree#968]
### Description
The tooltip is hidden when sidebar to the right

### Environment (if bug)
* Octotree version:5.0.0
* Octotree plan: free
* Screenshot, if any (drag an image here)
<img width="222" alt="スクリーンショット 2020-06-09 21 54 09" src="https://user-images.githubusercontent.com/28590054/84149706-d6494400-aa9b-11ea-9f0d-ca359dac5266.png">
<img width="238" alt="スクリーンショット 2020-06-09 21 53 57" src="https://user-images.githubusercontent.com/28590054/84149714-d9dccb00-aa9b-11ea-8ba9-7f589c989dbb.png">

### Suggestion
Change classname to `tooltipped-sw` or `tooltipped-nw` when sidebar to the right

<img width="237" alt="スクリーンショット 2020-06-09 22 00 34" src="https://user-images.githubusercontent.com/28590054/84150594-0b09cb00-aa9d-11ea-9977-bfbe100005cc.png">
<img width="1323" alt="スクリーンショット 2020-06-09 22 00 48" src="https://user-images.githubusercontent.com/28590054/84150608-0f35e880-aa9d-11ea-9061-d590b3f022a2.png">

<img width="220" alt="スクリーンショット 2020-06-09 22 01 41" src="https://user-images.githubusercontent.com/28590054/84150977-9b481000-aa9d-11ea-99ce-59ba5d5baf48.png">
<img width="1321" alt="スクリーンショット 2020-06-09 22 01 49" src="https://user-images.githubusercontent.com/28590054/84150981-9daa6a00-aa9d-11ea-85bc-6bd093cbd76f.png">

**Comment by buunguyen** [comment]
Thanks for reporting. Fixed in 5.1
