### ISSUE TITLE
Trouble configuring Octotree with private repo

### ISSUE THREAD

**Issue by msgirlperl** [ovity/octotree#969]
### Description
I went to Github and generated a personal token, then entered it into the 'Default Access Token' textbox in Octotree settings, and clicked apply.

I continue to get this error message: 
`Accessing private repositories requires a GitHub access token. Please go to Settings and enter a token.`
### Environment (if bug)

* Octotree version:Version 5.0.0
* Browser & version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
* OS & version: mac catalina 10.15.4
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/19295354/84181915-96f90400-aa57-11ea-9b3e-cd9083b0b838.png)

* Console error log below this line
api.github.com/repos/indigo-ag/growers-ui/git/trees/develop?recursive=1&_=1591724552826:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by buunguyen** [comment]
Please check if your token is correct for the account.
