### ISSUE TITLE
Sidebar overlaps project page when using full screen mode

### ISSUE THREAD

**Issue by OliverJAsh** [ovity/octotree#970]
### Description
The sidebar overlaps the project page when using full screen mode, and we can't scroll to see the content underneath the sidebar.

To reproduce, go to a GitHub project in full screen mode (append `?fullscreen=true`).

### Environment (if bug)

* Octotree version: latest
* Browser & version: Chrome latest
* OS & version: macOS latest
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/921609/84309819-93997180-ab58-11ea-8c34-eb771f08ea39.png)
* Console error log below this line

**Comment by buunguyen** [comment]
Fixed in 5.2.0
