### ISSUE TITLE
Reduced line-height

### ISSUE THREAD

**Issue by pelid** [ovity/octotree#971]
Octotree plugin unexpectedly change line height of code on GitHub site. How it looks like with and without plugin:

![image](https://user-images.githubusercontent.com/870324/84414147-39f97b80-ac1a-11ea-9510-670b48b7c028.png)

Number of code lines on the left differ from right.  It is a problem, because even after weeks of usage I can`t adapt to new code style. It's terrible.

### Environment (if bug)

* Octotree version: 5.0.0
* Browser & version: Chrome, Version 83.0.4103.97 (Official Build)
* OS & version: Ubuntu, 18.04.4 LTS

**Comment by conformist-mw** [comment]
Same for me. The font is compressed vertically and it becomes inconvenient to read the code. I thought it was Github who changed the fonts, but it turned out to be a plugin.

**Comment by buunguyen** [comment]
Fixed in 5.1
