### ISSUE TITLE
Extra padding of warning info in delete repository dialog will be added when sidebar is pinned

### ISSUE THREAD

**Issue by classicemi** [ovity/octotree#975]
### Description
When I pinned the sidebar there will be an extra padding of warning info in the delete repo dialog.

### Environment (if bug)

* Octotree version: 5.0.0
* Browser & version: Google Chrome 83.0.4103.97
* OS & version: macOS Mojave
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/3982491/84982884-2c884800-b16a-11ea-9f0d-c913883bd882.png)
* Console error log below this line

**Comment by buunguyen** [comment]
Thanks for reporting, fixed in 5.2.0
