### ISSUE TITLE
Disable "Open sidebar on hover" doesnt work

### ISSUE THREAD

**Issue by vaynelau** [ovity/octotree#976]
### Description
I've disabled the option "Open sidebar on hover", yet the sidebar stil autos to open when I hover above/below the "Octotree handle"

### Environment (if bug)

* Octotree version: 5.1.0
* Browser & version: Chrome 83.0.4103.106
* OS & version: Windows 10 1909  18363.836

**Comment by buunguyen** [comment]
Hi, we can't reproduce this. Any further info about your configurations to help reproduce?
