### ISSUE TITLE
[bug] Increase the number of titles If switching tabs.

### ISSUE THREAD

**Issue by ellreka** [ovity/octotree#977]
### Description
The cause and conditions aren't clear, but switching tabs three times will increase the number of titles.

### Environment (if bug)

* Octotree version:5.1.0
* Browser & version: Chrome / 83.0.4103.116
* OS & version: macOS Catalina 10.15.1
* Screenshot, if any (drag an image here)
* Console error log below this line

![octotree_issue](https://user-images.githubusercontent.com/28590054/85597858-fa08ae80-b685-11ea-8a6d-aa31d0bcdc27.gif)

**Comment by buunguyen** [comment]
Thanks for reporting. We fixed in 5.2.0. It should be available for auto update shortly.
