### ISSUE TITLE
Bug: does not handle '/' in branch name correctly 

### ISSUE THREAD

**Issue by Genteure** [ovity/octotree#978]
### Description
- Create a branch named `feature/test`
- "Error: Private repository"
- request sent to `https://api.github.com/repos/{user}/{repo}/git/trees/feature?_={time}`

### Environment (if bug)

* Octotree version: **5.2.0**
* Browser & version: **Chrome 83**
* OS & version: **Windows 10**
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/11240579/85969056-27908780-b9f9-11ea-8d78-66925e72ab43.png)
![image](https://user-images.githubusercontent.com/11240579/85969085-3ecf7500-b9f9-11ea-99a9-779c4e4a7331.png)
* Console error log below this line
**N/A**

**Comment by buunguyen** [comment]
Thanks for reporting. This was fixed in 5.2.1, should be available soon.
