### ISSUE TITLE
Improve UX for search feature with Vimium's Extension Chrome

### ISSUE THREAD

**Issue by harrytran998** [ovity/octotree#981]
### Description
You can see the image below, I can not see the keyword of Vimium to select it! It's too close together! Hope anyone can fix it!

* Octotree version:
Lastest
* Browser & version:
Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
* OS & version:
MacOS 10.15.4
* Screenshot, if any (drag an image here)
![image](https://user-images.githubusercontent.com/24296018/86546617-059a8600-bf60-11ea-9f5c-6e7816e734b0.png)

**Comment by buunguyen** [comment]
We add hotkey support for search feature (Tab+S by default). It can be configured. Hope it's an acceptable workaround.
