### ISSUE TITLE
Fix text color on release tagging in dark mode

### ISSUE THREAD

**Issue by tylersatre** [ovity/octotree#982]
### Description
The text that shows previous version tags is almost the same color as the background in dark mode, it can only be read when mousing over the option.  The highlighted option changes to a red background with white text, while normally a grey background with black text.  The screenshot below shows the box expanded and if you look closely you can see the text below where I've typed in `7.1.`.  I'm guessing an ID or class that was used for changing text color changed, I only noticed this bug within the past few days.

### Environment (if bug)

* Octotree version: 5.2.2
* Browser & version: Firefox Developer 79.0b4
* OS & version: macOS 10.15.4
* Screenshot:
![image](https://user-images.githubusercontent.com/917429/86938291-47692f00-c10e-11ea-8f20-d1e1cf241345.png)
* Console error log below this line - None

**Comment by buunguyen** [comment]
I don't see this dropdown to test it, but we upgraded the themes in Octotree 6 and I hope that would fix this. Gonna close but if it still happens, please let me know. Would be great if there's a link for me to check it out,

**Comment by tylersatre** [comment]
> I don't see this dropdown to test it, but we upgraded the themes in Octotree 6 and I hope that would fix this. Gonna close but if it still happens, please let me know. Would be great if there's a link for me to check it out,

It's working now, thanks!
