### ISSUE TITLE
Update VB.NET icon

### ISSUE THREAD

**Issue by Aoi-hosizora** [ovity/octotree#983]
Hope to use a new VB icon as C#, just don't use a VS icon.

![image](https://user-images.githubusercontent.com/31433480/87290934-374bb800-c531-11ea-8bbf-0ee278e02ae3.png)

**Comment by kidonng** [comment]
I wish Octotree to use a new set of icons like https://github.com/PKief/vscode-material-icon-theme

**Comment by buunguyen** [comment]
Thanks. We do plan to support new icon sets. Stay tuned!

**Comment by buunguyen** [comment]
We revamped icon support. The default set now uses GitHub's official file icons. Octotree Pro provides more file icon choices.
