### ISSUE TITLE
Pinned sidebar hides the review success message

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#984]
### Description
When submitting a review, GitHub shows a blue header bar with a success message. The message in this bar gets hidden by a pinned Octotree.

### Environment

* Octotree version: 5.2.2 (Pro)
* Browser & version: Firefox 78.0.2 (64-Bit)
* OS & version: Windows 10 Pro 19.09

Unpinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/87472928-05b21a00-c621-11ea-84c6-79f867928354.png)

Pinned sidebar with hidden message in header bar:
![grafik](https://user-images.githubusercontent.com/424602/87473000-1cf10780-c621-11ea-87b8-74eb7bdad1f4.png)

**Comment by mikernet** [comment]
It also overlaps the name of the repo

**Comment by jdreesen** [comment]
> It also overlaps the name of the repo

That was reported in #986 and is already fixed, please update.

**Comment by buunguyen** [comment]
Thanks for reporting. Should have been fixed in 6.1.0 (already submitted and should be available within hours).
