### ISSUE TITLE
Firefox gets logged out if multiple browser instances

### ISSUE THREAD

**Issue by jmickey** [ovity/octotree#985]
### Description
Firstly, love the extension, so thanks for that. I am a paid user and have a small issue. I use 2 browsers concurrently on the same machine (Firefox and Firefox Developer Edition), and I am logged into GitHub on both. 

When I login to Octotree in one browser, Alt-Tab to the second browser and login to that browser as well I get logged out of Octotree on the first browser. Can this be fixed at all?

### Environment (if bug)

* Octotree version: 5.2.0
* Browser & version: Firefox (78.0.1) / Firefox Developer Edition (79.0b2)
* OS & version: MacOS 10.15.5

**Comment by buunguyen** [comment]
> When I login to Octotree in one browser

You mean the extension itself or the octotree.io website?

In the browsers, do you login to the same Firefox account?

**Comment by jmickey** [comment]
The extension.

Different Firefox accounts.

**Comment by buunguyen** [comment]
Please upgrade to 6.0.3 and let us know if it fixes the problem

**Comment by jmickey** [comment]
@buunguyen It appears to be fixed, thanks!
