### ISSUE TITLE
Pinned sidebar hides the repo name in the header

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#986]
### Description
The repo name gets hidden by a pinned Octotree instead of being pushed to the right.

### Environment
* Octotree version: 5.2.2 (Pro)
* Browser & version: Firefox 78.0.2 (64-Bit)
* OS & version: Windows 10 Pro 19.09

Unpinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/87729499-d092fc80-c7c5-11ea-95e1-805992fe99c6.png)

Pinned sidebar with hidden repo name:
![grafik](https://user-images.githubusercontent.com/424602/87729519-db4d9180-c7c5-11ea-976b-803daed1a10c.png)

**Comment by buunguyen** [comment]
Thanks for reporting. GitHub has changed its DOM again...

**Comment by jdreesen** [comment]
Yeah, I thought so...

**Comment by buunguyen** [comment]
Fixed in 5.4.0. Should be available shortly.

**Comment by jdreesen** [comment]
I confirm that it works again. Thx for the quick fix! :)

**Comment by repodevs** [comment]
Hi @buunguyen version 5.4.0 not available in Opera.
Would you like to update it?

**Comment by buunguyen** [comment]
@repodevs hi, sorry. We released to Opera but they have been very slow in approving (they didn't even approve the previous version which was uploaded last month). I'll see if there's anyway we can do to boost this.
