### ISSUE TITLE
Repo name be hidden while resize window

### ISSUE THREAD

**Issue by wudi** [ovity/octotree#988]
![QQ20200717-173421-HD](https://user-images.githubusercontent.com/3753615/87772149-e8b15d00-c853-11ea-9f97-6970613d12e0.gif)

**Comment by jdreesen** [comment]
Which version do you use?
Does this occur on `5.4.0`?

**Comment by buunguyen** [comment]
Should have been fixed in latest version. If not please let me know and I'll reopen.
