### ISSUE TITLE
the bookmark icon is not displayed at all

### ISSUE THREAD

**Issue by xmhwws** [ovity/octotree#990]
Google Chrome 85.0.4183.26 dev x64
windows10
octotree 5.4.0

The bookmark function of the latest version 5.4.0 is invalid and the bookmark icon is not displayed at all
![image](https://user-images.githubusercontent.com/42903751/87841228-7f266280-c8d6-11ea-8f48-b97cb5494dcd.png)

![image](https://user-images.githubusercontent.com/42903751/87841280-de847280-c8d6-11ea-966d-1cf30779d04f.png)

**Comment by tylersatre** [comment]
It's also not displayed in the following setup:

Firefox Developer 79.0b6
macOS 10.15.4
Octotree 5.4.0

I'm assuming it's not a browser/OS specific issue but something related to github code and how the bookmark icon is placed.

**Comment by xusiyuan841028** [comment]
Actually, I can create a bookmark for an issue, PR, file, but except a repository!

**Comment by buunguyen** [comment]
We're aware of the issue and will release a fix soon.

**Comment by buunguyen** [comment]
This was fixed in 5.4.1. Closing now.
