### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by kidonng** [ovity/octotree#991]
### Description
GitHub updated their icons ([Octicons](https://primer.style/octicons/)) two months ago. I think Octotree should follow the changes to match GitHub's style.

**Comment by buunguyen** [comment]
Thanks, we'll use the new icons in the next release.

**Comment by kidonng** [comment]
The new interface looks really gorgeous, thanks for your work!

![image](https://user-images.githubusercontent.com/44045911/93439558-49ffb600-f901-11ea-9efd-f65d557a3b95.png)

**Comment by Nekonyx** [comment]
Even thought the previous icons did not match GitHub's style, they were very easy and convenient to navigate. Now they all look the same, and this is very big problem for UX. Please make it free to change\revert icon's style to the old one.

![image](https://user-images.githubusercontent.com/16444061/93451006-6fd48d00-f8f8-11ea-9add-ee6b9ea7dac0.png)
