### ISSUE TITLE
Suggestion: cache code tree

### ISSUE THREAD

**Issue by zingdle** [ovity/octotree#995]
### Description
First of all, thanks for your excellent work!

The code tree is retrieved every time I'm jumping around files inside one repo. It would take seconds to get the code tree result for some large code base. Would it be better if the result is cached and get displayed as soon as possible? Or is this feature is done but I'm not noticed?

**Comment by Fahme** [comment]
Octotree provides a performance pack if you're a PRO user for dealing with huge repos :
https://www.octotree.io/features#performance-pack

performance pack supports : 
-  Automatic or optional lazy load for a specified huge repo
-  Caching feature for big trees
