### ISSUE TITLE
Feature Request - Remove overflow

### ISSUE THREAD

**Issue by hyojaekim** [ovity/octotree#996]
### Description

I want to see the full name of the file, but I can't.

Would you consider clearing the overflow(hidden) so you can scroll through the file names to see them?

### Environment (if feature)
Octotree version: 5.4.1
Browser & version: Chrome 84.0.4147.105
OS & version: macOS 10.15.6

### Screenshot

***Before***

![image](https://user-images.githubusercontent.com/41109150/90328666-2af7c680-dfd9-11ea-824c-1b5c1ffc394f.png)

***After***

![image](https://user-images.githubusercontent.com/41109150/90328724-9a6db600-dfd9-11ea-86f8-d98f4dee1251.png)

![image](https://user-images.githubusercontent.com/41109150/90328711-81650500-dfd9-11ea-8d8a-c62983c2d6d3.png)

**Comment by danhgit** [comment]
We haven't been able to find a way to do this without breaking things. However, it should be possible to view full name by hovering at a file. Sorry there's no better solution for now. I'm gonna close this.
