### ISSUE TITLE
Pinned sidebar hides new `OctoLinker` update notification

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#997]
### Description
[OctoLinker](https://github.com/OctoLinker/OctoLinker) has a new update notification since [version 6.5](https://github.com/OctoLinker/OctoLinker/releases/tag/v6.5.0) which appears in the bottom left corner.
A pinned Octotree sidebar hides this notification:

Unpinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/90697134-02dcc180-e27e-11ea-9f06-c41561ebc06d.png)

Pinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/90697179-1851eb80-e27e-11ea-9cd8-fc073a2db65f.png)
 
### Environment (if bug)

* Octotree version: 5.4.1
* Browser & version: Firefox 79.0 (64-Bit)
* OS & version: Windows 10 Pro

**Comment by buunguyen** [comment]
Thanks for reporting. It would be very hard to keep up with all the changes in other extensions. Our focus is keeping up with the changes of GitHub itself. Unless an issue causes Octotree or said extension to break, I'm afraid we're not going to address it. Thanks for your understanding.
