### ISSUE TITLE
Many tabs has color

### ISSUE THREAD

**Issue by inikonorov** [ovity/octotree#998]
When I stay at issues tab and try to open file from via octotree, after file's loading I see this
![image](https://user-images.githubusercontent.com/30556799/90808405-a1256180-e328-11ea-9acc-8cd74d78d1f2.png)
Is it GitHub bug or Octotree? If it is Octotree bug, I wanna solve this :)

**Comment by buunguyen** [comment]
Yeah, it's annoying. Will fix.

**Comment by buunguyen** [comment]
Fixed in 6.0
