### ISSUE TITLE
Pinned sidebar pushes header of `Open with` button flyout on PR pages to the right

### ISSUE THREAD

**Issue by jdreesen** [ovity/octotree#999]
### Description
When the sidebar is pinned, the header of the `Open with` button flyout on PR pages is pushed to the right and hidden behind a scrollbar.

After clicking on the `Open with` button:
![grafik](https://user-images.githubusercontent.com/424602/90870665-33b21900-e39a-11ea-8cb6-31479d7dbf6b.png)

After clicking on the `Open with` button and scrolling to the right:
![grafik](https://user-images.githubusercontent.com/424602/90870682-3c0a5400-e39a-11ea-8b54-00cef1857475.png)

With unpinned sidebar:
![grafik](https://user-images.githubusercontent.com/424602/90870718-44fb2580-e39a-11ea-9f26-05c12cca83af.png)

### Environment (if bug)

* Octotree version: 5.4.1
* Browser & version: 79.0 (64-Bit)
* OS & version: Ubuntu 18.04

**Comment by buunguyen** [comment]
Thanks for reporting. Should have been fixed in 6.1.0 (already submitted and should be available within hours).

**Comment by jdreesen** [comment]
I confirm it is fixed, thx!
